### ISSUE TITLE
[0.50.01-SNAPSHOT] Overview of portraits that fail to import.

### ISSUE THREAD

**Issue by Tzahr** [MegaMek/mekhq#4917] opened 2024-09-26 21:35 UTC
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Low (Minor/Nuisance): Minor glitches or cosmetic issues that don’t affect gameplay and occur rarely.

### Brief Description *

For this test, a save was created containing one of every personnel type in a previous version (MHQ revision: d6d435c2ed8ce6fc0c411bacf88f7c948ac069af) and loaded into the current Nightly to identify which personnel types failed to import with their correct portraits.

The following roles were affected: 
- ProtoMek Pilots
- Mek Techs

Mek Techs additionally also fail to generate with portaits at all in the new build - see #4898

### Operating System *

Windows 11

### Java Version *

21.0.3

### MekHQ Suite Version *

Free Text (type manually)

### Custom MekHQ Version

Nightly 0.50.01 - 621775698d20e6bb8b6ef8d55600a79af7d4593a

### Attach Files

[savegames.zip](https://github.com/user-attachments/files/17156252/savegames.zip)
[mekhq.log](https://github.com/user-attachments/files/17156254/mekhq.log)

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by IllianiCBT** [comment] 2024-09-26 21:36
I'm fairly certain I know the cause here, I'll put in a fix tomorrow

**Comment by IllianiCBT** [comment] 2024-09-28 20:37
Closing as resolved

**Closed by IllianiCBT** 2024-09-28 20:37 UTC
