### ISSUE TITLE
Illegal state error causes lock

### ISSUE THREAD

**Issue by Ward-B** [MegaMek/mekhq#3696] opened 2023-06-14 19:04 UTC
### Environment
What version of MekHQ does your issue apply to?
- 0.49.14-SNAPSHOT
What operating system are you using?  Windows, Mac, or Linux?
- Windows 11
What java version are you using?  If unsure it will state your java version at the top of the mekhq.log file.
- 11.0.19

### Description
I have no clue how to replicate the issue, it just pops up during gameplay (in MegaMek, not in MekHQ, but it is in a MekHQ campaign). At some point after (or during...?) physical phase I get a pop-up with an error, exclamating there has been an illegal state exception. The log files mention something about a unit not knowing its elevation. Subsequently, the game 'sort of' freezes. I can click units, but can't click done in order to progress to the next turn.

Another (the newest, I think) mentions something about the internal structure of a battle armor unit. Hope it helps...

### Files
[CustomsAndCampFile.zip](https://github.com/MegaMek/mekhq/files/11749677/CustomsAndCampFile.zip)
[mekhq.log](https://github.com/MegaMek/mekhq/files/11749654/mekhq.log)
[megamek.log](https://github.com/MegaMek/mekhq/files/11749655/megamek.log)

**Comment by kuronekochomusuke** [comment] 2023-06-14 20:07
duplicate of https://github.com/MegaMek/megamek/issues/4523

**Closed** 2023-06-14 20:18 UTC
