### ISSUE TITLE
MekHQ Endo Steel Customization

### ISSUE THREAD

**Issue by Cimbri** [MegaMek/mekhq#693] opened 2018-04-01 06:22 UTC
Fill out the fields below with as much pertinent information as possible to help the developers solve the issue.
Search for your issue inside open and closed issues first before reporting so as not to make duplicates.

### Environment
What version of MekHQ does your issue apply to? 43.8 and 43.9
What operating system are you using?  Windows, Mac, or Linux? Windows
What java version are you using?  If unsure it will state your java version at the top of the mekhqlog.txt file. Java 8.161

### Description
Describe the issue and provide screenshots ingame if able. 
When customizing a mech in the mechlab if you use Endo-Steel parts they cannot be placed into a crit slot rendering them unusable.
Provide the rulebook, page number, and text if you feel like this is a rules issue.
And provide the steps you have taken to reproduce the issue in the campaign file if applicable.
It occurs in any and all campaigns I've started using 43.8 and 43.9. I've tested it on a fresh install of each version and on a fresh campaign as well.
### Files
Provide the .cpnx campaign file that this issue occurs in. 
Provide any custom units that you are using in this campaign so that it will load on the developers machine. 
Provide any other files that you have customized in this campaign like the factions.xml for example. 
And provide the mekhqlog.txt file for any NPE's or errors that MekHQ might be reporting. 
[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/1866136/mekhqlog.txt)
[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/1866144/mekhqlog.txt)
Do not paste the entire logfile text into this ticket. Just attach the actual mekhqlog.txt file

**Comment by neoancient** [comment] 2018-04-01 13:48
Duplicate of #688

**Closed by neoancient** 2018-04-01 13:48 UTC
Labels: duplicate
