### ISSUE TITLE
Mek HQ NI #1641 - Mission spawns may be out of bounds

### ISSUE THREAD

**Issue by RaozSpaz** [MegaMek/mekhq#5039] opened 2024-10-12 23:10 UTC
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Medium (Gameplay Limitation): Non-core functionality is impaired, providing a suboptimal but playable experience.

### Brief Description *

![image](https://github.com/user-attachments/assets/d3a600eb-2fac-4125-98c1-c40b986b9eb4)

The above is the seed lance for all of the following. As it was the only lance in my TOE at the time. Note this issue is posted using a Green Campaign setting and with this as the contract
![image](https://github.com/user-attachments/assets/67a2cc37-4126-4d16-b622-9e8eb1fdbbf2)

Mission Images
![mission1](https://github.com/user-attachments/assets/802d6988-e577-47de-a9cb-95bb142e3c7f)
![mission2](https://github.com/user-attachments/assets/b61a4266-235f-4e94-a5b5-128273fc72df)
![mission3](https://github.com/user-attachments/assets/d38b5b6b-ede9-42b3-a91f-51d7ee7397fa)
![mission4](https://github.com/user-attachments/assets/95242360-5ce8-4042-bfa6-a5470d6f3a37)
![mission5](https://github.com/user-attachments/assets/3926c06e-ca4f-4cc9-a76e-6c493d56e93f)
![mission6a](https://github.com/user-attachments/assets/5f604a81-6a66-4832-9443-049dad31232c)
![mission6b](https://github.com/user-attachments/assets/e6b3a996-b5a1-4e7f-bb33-2b29d2efb6d9)

And the logs
[mission 1-3.log](https://github.com/user-attachments/files/17351738/mission.1-3.log)
[mission 4 - 6.log](https://github.com/user-attachments/files/17351739/mission.4.-.6.log)

Obviously mission 6 can pretty well be ignored due to the Dropship spawning bug. However most of these other missions seem very . . . odd. Balance wise. In the first 2, there is a tank base belonging to the enemy which isnt spawning. So thats part of why the forces are so small. The third and the other set of 3 are with said base flipped and are quite a bit larger.

The issue arises is the fact that this is apparently spawning on a Green Campaign Setting on a 1Green - 2Red 'difficulty?'. I couldn't imagine trying to play these missions if they were on a Regular campaign setting, let alone a higher built in difficulty/rating. 

The complete polarized difference between the first 3 and the second set of 3 is astounding. Im going to try and aquire some data using more veteran crews and see what happens.

### Operating System *

Windows 10

### Java Version *

Java 17

### MekHQ Suite Version *

Free Text (type manually)

### Custom MekHQ Version

NI #1641

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by IllianiCBT** [comment] 2024-10-13 17:04
After checking using the changes in #5042 and the save you sent me, everything appears to be working as intended. However, we want to keep an eye on this once the changes in #5042 have been merged. As that PR gives us better logging, which will help narrow down any problems.

Closing as resolved, with awareness that we may need to reopen this if #5042 doesn't fully resolve the problems.

**Closed by IllianiCBT** 2024-10-13 17:04 UTC
