### ISSUE TITLE
Paid recruitment rolls being debited multiple times per instance

### ISSUE THREAD

**Issue by OrbMonky** [MegaMek/mekhq#4767] opened 2024-09-02 19:28 UTC
### Environment
Windows 10, Java 17, 0.50.00 release

### Description
One week's paid recruitment recursed 7 times after the original, all on the same date.
![image](https://github.com/user-attachments/assets/00627a49-b2d6-400a-9869-55d752151c6b)
Using ATB Market if that matters. Is it possibly rolling for each potential recruiting admin?
It did seem to give results commensurate with such an expenditure (or I just got really lucky) but definitely an unintuitive 'where did all my money go' thing.
### Files
[mekhq.log](https://github.com/user-attachments/files/16840804/mekhq.log)
[customs.zip](https://github.com/user-attachments/files/16840822/customs.zip)
[RECRUITMENT.zip](https://github.com/user-attachments/files/16840823/RECRUITMENT.zip)

**Comment by OrbMonky** [comment] 2024-09-02 19:41
Went back and ran it again and got 9 instead of 8 so it looks like a possible 'roll to failure' effect that is happening?

**Comment by Algebro7** [comment] 2024-09-20 13:37
So I'm not sure what's going on, but when I loaded your save and had a play around with it, I was only only getting 1 debit each week afterwards as expected. I was also unable to replicate with other saves. Are you still seeing this behavior if you restart MekHQ and continue advancing days to the following Mondays?

My _guess_ having looked at the code is that there was some kind of bad state, possibly due to switching between Campaign options. There is [no loop involved](https://github.com/MegaMek/mekhq/blob/master/MekHQ/src/mekhq/module/atb/AtBEventProcessor.java#L76) , so the only way I can see that this could fire multiple times on the same day is if there are multiple `AtbEventProcessor` instances registered for the `NewDayEvent`. This shouldn't normally happen and I've been unable to induce it again, but it's something we should keep an eye out for and fix if we can figure it out.

**Comment by OrbMonky** [comment] 2024-09-20 13:41
I have had it on every roll except for one period after the latest contract, when it started back up again after a few weeks of just making one roll. It seems random in number, not pertaining to any number of staff or other discernible quality of the campaign. I can repro on my end, but I am not sure what to look for in terms of traceable behavior.

**Comment by IllianiCBT** [comment] 2024-09-25 20:53
We're having a really hard time replicating this issue. My best guess is that you managed to find yourself in a weirdly specific game state that we've been update to recreate.

My recommendation: turn paid recruitment off. Save and exit the game. Load back in, turn on paid recruitment and see if the issue persists. If it does, remove all units from your hangar and resave, dropping the save file here. I'll then re-open the case and investigate further.

Closing as 'unable to replicate'

**Comment by OrbMonky** [comment] 2024-10-05 20:54
Having played a few years in this campaign, it seems that this behavior resets at the end of a contract and slowly builds up over time. Recruitment rolls post contract are normal... until they aren't. It seems to gradually build up as time progresses outside of contract.

**Comment by WeaverThree** [comment] 2024-10-07 01:33
Dang, I had this happen once yesterday when I was testing for multiple people in the hiring market, before I learned that having paid recruitment as an option in camops is actually wrong. I haven't a clue what caused it and I didn't think to keep the save though.

**Comment by IllianiCBT** [comment] 2024-10-07 01:44
Do we want to just remove paid recruitment? It has no basis in CamOps and causes so many problems. We'd want to include an optional table that expands the official table to include all necessary roles. But other than that, simply removing the option is the way forward imo.

**Comment by Algebro7** [comment] 2024-10-07 02:00
We are planning to remove it for CamOps already but it seems like a lot of AtB and Dylan's folks still use it. Maybe we could use the CamOps acquisition roll system for all of them instead when that's implemented? It would probably be pretty market-agnostic so possibly not much effort.

**Comment by IllianiCBT** [comment] 2024-10-07 02:25
So the plan is to remove the various recruitment methods and to only offer CamOps, but with enough campaign options that users can customize their experience. To reduce the amount of methods we’re needing to support.

**Comment by OrbMonky** [comment] 2024-10-07 03:29
I think I found the point where the issue is happening - going on contract (possibly just traveling) is exactly when the issue reoccurred this game year. It also happened to be the first week of February so it could be at the start of a new year it slowly has a chance to creep in over the year month over month.

**Comment by Algebro7** [comment] 2024-10-07 13:02
> I think I found the point where the issue is happening - going on contract (possibly just traveling) is exactly when the issue reoccurred this game year.

Thanks for the extra info, we can give that a shot.

> So the plan is to remove the various recruitment methods and to only offer CamOps, but with enough campaign options that users can customize their experience. To reduce the amount of methods we’re needing to support.

What kinds of options are we thinking about adding? It feels like at some point the complexity of supporting interactions between a bunch of different options could be greater than supporting a couple of discrete methods, although I guess that might not be true once you consider that each method has its own options.

**Comment by Thom293** [comment] 2024-10-07 16:32
Going to remove legacy methods completely?

**Comment by IllianiCBT** [comment] 2024-10-07 16:34
In places where it makes sense, yeah. The reality is that we don't have the dev team to support current and legacy options. A line has to be drawn somewhere, and for users who want to continue playing with cut options those options will still exist in older versions.

Also, as this issue is still present (now we've started to narrow in on why it wasn't reproducible), I'm re-opening it.

**Comment by IllianiCBT** [comment] 2024-12-18 05:15
Tentatively we believe this has been fixed. I'm going to close this case, but if you find the issue reappears in 50.02 let us know and we'll reopen it :)

**Closed by IllianiCBT** 2024-12-18 05:15 UTC
Labels: Needs More Info
