### ISSUE TITLE
[0.50.02-SNAPSHOT] Unusual FG3 opfor as well as "null" turn timer goal on "avoid recon" mission

### ISSUE THREAD

**Issue by PhoenixHeart512** [MegaMek/mekhq#5433] opened 2024-12-18 20:41 UTC
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Medium (Gameplay Limitation): Non-core functionality is impaired, providing a suboptimal but playable experience.

### Brief Description *

Unusual opfor and also null turn timer objective

### Steps to Reproduce

N/A

### Operating System *

Windows 10

### Java Version *

Java Version: 17.0.6

### MekHQ Suite Version *

Free Text (type manually)

### Custom MekHQ Version

megamek.MegaMek.initializeLogging(MegaMek.java:146) - Starting MegaMek v0.50.02-SNAPSHOT     Build Date: 2024-12-18T03:29:15.602420287     Today: 2024-12-18     Origin Project: MegaMekLab     Java Vendor: Eclipse Adoptium     Java Version: 17.0.6     Platform: Windows 10 10.0 (amd64)     System Locale: en_US     Total memory available to MegaMek: 4 GB     MM Code Revision: 73e2ba3ec6090e9da223cb0a80fe684f16fd7ec1     MML Code Revision: 543ecc92823ad4c939d7f5316c0075cd50616d25     MHQ Code Revision: c8b3364a938a8f4599c02ffaa4c03519af91da1b

### Attach Files

[FG3 opfor.zip](https://github.com/user-attachments/files/18188598/FG3.opfor.zip)

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by PhoenixHeart512** [comment] 2024-12-18 20:58
Also the mekHQ log appears to be malformed and full of NULL when opened in N++. The log did not populate until mekHQ was fully closed, which itself is also unusual.

[mekhq.log](https://github.com/user-attachments/files/18188744/mekhq.log)

**Comment by IllianiCBT** [comment] 2024-12-19 00:44
Closing as resolved.

The `null` logger issue is not related to the root cause of this issue report and should be logged separately. Though, I'll be honest, I have no clue what could have caused that. Everything logs correctly for me (which I know doesn't help either of us).

**Closed by IllianiCBT** 2024-12-19 00:44 UTC
