### ISSUE TITLE
Post scenario awards issused in multiples

### ISSUE THREAD

**Issue by Stm316** [MegaMek/mekhq#4826] opened 2024-09-13 10:39 UTC
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Low (Minor/Nuisance): Minor glitches or cosmetic issues that don’t affect gameplay and occur rarely.

### Brief Description *

I have multiple award sets, all except 1 filtered in personnel options. Standard set enabled. Ran a scenario, and, afterwards, any awards earned were issued multiple times.  It's probable custom awards are not defined correctly. Otherwise game runs just fine.
**EDIT** It turns out I had not filtered the sets. I still don't understand why this error occurs.

![image](https://github.com/user-attachments/assets/dc17de16-1e19-45d1-becc-ae734c31f4a1)

### Steps to Reproduce

Load game
Run scenario
Auto-awards issues multiple instances of award.

### Operating System *

Windows 10

### Java Version *

17.0.11

### MekHQ Suite Version *

0.50.1 Nightly 1609

### Attach Files

Award xml files
[Awards.zip](https://github.com/user-attachments/files/16992499/Awards.zip)

Pre-scenario save 
[Bridger's Bandits29400415.cpnx.gz](https://github.com/user-attachments/files/16992506/Bridger.s.Bandits29400415.cpnx.gz)
Post-action Mul
[Bridger's Bandits.zip](https://github.com/user-attachments/files/16992526/Bridger.s.Bandits.zip)

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by IllianiCBT** [comment] 2024-09-16 03:18
Can you do me a favor and send me a screenshot of your award filter list in campaign options? Specifically this section:

![image](https://github.com/user-attachments/assets/40369db1-fc8b-49d9-a052-29b604da8408)

Trying to identify why it's empty for me, as I assume it isn't for you.

**Comment by IllianiCBT** [comment] 2024-09-16 03:20
Actually, checking the file-save itself I can see that save is empty:

![image](https://github.com/user-attachments/assets/b6255c98-56e3-455e-8bde-b4593ee67ad8)

This is likely the cause of the problem your experience. Can you confirm that if you add the custom sets you want to ignore to the ignore list, whether they're ignored and whether that persists between saves?

**Comment by Stm316** [comment] 2024-09-17 07:48
I realised I'd initially created the problem myself by loading an older save. Since then, adding the sets to the filter (the deleting the older save) they are ignored, but the multiple-issue persists. I did notice that I had 17 sets listed, but I have 21. Could this be a factor?

[SLDF 824th Support Regiment28071016.cpnx.gz.zip](https://github.com/user-attachments/files/17024384/SLDF.824th.Support.Regiment28071016.cpnx.gz.zip)

**Comment by Stm316** [comment] 2024-09-27 21:50
New note: Using custom rank insignia, 1st of month auto-awards re-issues. If I don't skip, log contains entry with new date. Only new award can be removed (matching date). They are tagged in XML as "inclusive", not "promotion". Possibly need stackable tag set to "false" and have that in documentation.
![image](https://github.com/user-attachments/assets/95e7dbca-f294-413d-b0ee-230a3053c803)


 
![image2](https://github.com/user-attachments/assets/5f816280-3922-4cf0-b045-86989782498b)

**Comment by IllianiCBT** [comment] 2024-09-29 01:11
Closing as resolved

**Closed by IllianiCBT** 2024-09-29 01:11 UTC
Labels: Awards
