### ISSUE TITLE
47.10-Dev Unexpected campaign options changes

### ISSUE THREAD

**Issue by gsparks3** [MegaMek/mekhq#1939] opened 2020-08-19 02:49 UTC
### Environment
v47.10-Dev (downloaded on 8/17/2020)
Windows 10
Java version 1.8.0_261

### Description
First, a little context. This AtB campaign save originated in v47.7, was moved to v47.9, and was then further moved to the current dev-build in order to get update #1931 (having encountered severe issues with issue #1922). This fix seems to work quite well, and I have not encountered #1922 since. 

However, while things seemed to be working fine for several hours of use yesterday, today I have encountered an odd issue: campaign options changes that I didn't initiate. Finding/reproducing this one might be a pain, because I'm not sure exactly when the changes _occurred_. The first change (significant changes in the "Skills" tab of Campaign Options, altering the base Target Number for all Gunnery skills in addition to a variety of other parameters on that page) I only noticed after loading the campaign save today. I manually corrected this, and continued playing. The _second_ issue (changes in the XP costs for Special Pilot Abilities) may have occured at the same time, or possibly not; either way I did not notice it until significantly later, after finishing a Base Defense battle. I will say that the change in the "Skills" tab definitely did not occur immediately upon loading the campaign in MekHQ v47.10-Dev, because the change in the listed Gunnery values of units in the TO&E is distinctive, and I did not see that yesterday. Therefore, it is possible that this bug is intermittent. I apologize that I cannot provide more detailed reproduction steps. 

### Files
The below file is the last save of the campaign file from v47.9, to serve as a reference for Campaign Options. 
[Coppercoats.47.9.cpnx.zip](https://github.com/MegaMek/mekhq/files/5093748/Coppercoats.47.9.cpnx.zip)

The below file is the most recent save of the campaign file from v47.10-Dev. If you open both campaign files, you can see that the XP costs for Special Abilities are different in this file (or at least, that is how it shows up on my machine ...). I did _not_ initiate this change myself. There may be other changes; I have not exhaustively cross-checked the Campaign Options, or any other parameters. Unit and personnel details not being identical is expected, as this save is two months of in-game time ahead of the "baseline" save. 
[Coppercoats.zip](https://github.com/MegaMek/mekhq/files/5093753/Coppercoats.zip)

Logs are included, but I suspect they have nothing useful in them. 
[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/5093727/mekhqlog.txt)
[megameklog.txt](https://github.com/MegaMek/mekhq/files/5093728/megameklog.txt)

No custom units or other files.

**Comment by Windchild292** [comment] 2020-08-21 02:36
I could not find anything on investigation, and am discussing with the opener to try to discern the cause.

**Comment by Windchild292** [comment] 2020-08-21 03:36
Closing as per discussion with the opener, although I've got no idea from inspection how this could have happened.

**Comment by MageOhki** [comment] 2020-09-06 14:01
I receive the same error, via same pattern.

**Comment by Windchild292** [comment] 2020-09-07 03:26
Yup, once I reopened with the pattern provided I could recreate immediately.

**Closed** 2020-09-16 03:21 UTC
Labels: Personnel, bug
