### ISSUE TITLE
50.00 - Unit Veterancy Skill Level seems incorrect.

### ISSUE THREAD

**Issue by Thom293** [MegaMek/mekhq#4802] opened 2024-09-07 18:35 UTC
Generate brand new company, seems to always be rated as Veteran.  It was explained that it should calculate average level across combat only personnel.  

To repeat - generate company, advanced a week so unit report would change, look at roster and compare.  

My personal Preset - Zero Vets:
![image](https://github.com/user-attachments/assets/e0df2716-e818-437d-aa2e-dd520ff8b1eb)
Campaign Ops Preset - 3 Vets
![image](https://github.com/user-attachments/assets/b8955959-16b1-417b-8e32-6fc0ccb40f0c)
Complete Experience Preset - 1 Elite, 1 Vet, 2 Green, 3 Ultra Green.
![image](https://github.com/user-attachments/assets/152e83d4-3202-4b06-8d60-4cb7bc4e320c)

**Comment by ObviousTech** [comment] 2024-09-07 18:49
seeing this as well.   combat 2 veteran, 6 regular, 5 green   (or if counting only TOE units it's 2 vet, 4 reg, 4 green)

techs: 5 vet, 4 reg, 2 green, 1 ultra-green.

even after removing the 5 veteran techs (and advancing a week), the experience level is still calculating as Veteran.

If I switch the campaign options to FM-Mercs reputation, the experience changes to Regular.  So it may be something specific to Campaign Ops reputation

**Comment by Tzahr** [comment] 2024-09-07 18:53
MHQ Code Revision: 1348549171cc252f673c8856fef775e5e2b96a91

My combat personnel is composed of: 
56 Regulars, 62 Veterans, 52 Elites.
Not counting Techs, the vast majority of which are Veterans. 
    
![image](https://github.com/user-attachments/assets/dc53a5a9-c455-47bd-b738-16b4493a4ac2)

I'll append my full savegame and customs, in case a dataset is needed.

[1st Rimward Hussars.zip](https://github.com/user-attachments/files/16919487/1st.Rimward.Hussars.zip)
[customs.zip](https://github.com/user-attachments/files/16919486/customs.zip)

**Comment by IllianiCBT** [comment] 2024-09-07 18:54
So my first inclination is that one of a couple things could be happening:

- we only calculate personnel assigned to units (this is RAW) which could skew player expected values 
- As the reputation calculation is based on actual skill levels, not experience level, it might not match up with listed experience level. This is RAW.
- similar to the above, if the non-standard skill averaging is being used that might throw off player expected values, as it doesn’t apply to reputation
- The calculation could be returning an incorrect value - it shouldn’t be, as it was tested thoroughly but it’s always a possibility.

Unless investigation shows the final option is true this is working as intended.

**Comment by IllianiCBT** [comment] 2024-09-07 19:41
Closing this report as upon investigation the system was found to be working as intended. This can be confirmed by manually totally all relevant skill levels (the ones visible in the Edit Person screen) and then comparing that value to the value shown in debug logging.

**Comment by Thom293** [comment] 2024-09-07 20:23
Please re-open as this bug report is accurate.

**Closed** 2024-09-07 20:28 UTC
