### ISSUE TITLE
A... summary of several bugs... found in 44.0, but at least not major.

### ISSUE THREAD

**Issue by Mekslayer** [MegaMek/mekhq#782] opened 2018-07-03 17:45 UTC
I use both versions of HQ for Macbook pro  and PC win 7.

1) when I went to have aero battle and I output my starting mum file for the aerospace fighters... I had an added sequence at the end of fighters summary in the mud file..
"			<location index="4"> Wings
				<armor points="Destroyed"/>
			</location>
"
the wings armor points should not be described as "Destroyed" prior to battle.

2) when I finished the aero battle, and looked at the output mul file at the end of the fight, I saw that my Aero fighter was suddenly describe as "wheeled" when I could have taken off (I believe)

"		<entity chassis="Gotha" model="GTHA-600" type="Wheeled" commander="false" offboard="false" hidden="false" deployment="0" deploymentZone="-1" neverDeployed="false" velocity="0" altitude="0" externalId="1a92dc56-9635-4962-aa10-0684232a796f" camoCategory="-- No Camo --">
			<pilot size="1" name="Umer Azagba" nick="" gunnery="4" piloting="5" externalId="0c1830bb-eb40-4bb9-8d8f-fcec53fe1f0e" ejected="false"/>
			<fuel left="480"/>
			<bombs>
			</bombs>
			<structural integrity="3"/>
			<heat sinks="12"/>
      <acriticals gear="none"/>
      The first slot in a location is at index="1".
			<location index="0"> Nose
				<armor points="26"/>
			</location>
			<location index="1"> Left Wing
				<armor points="14"/>
         <slot index="1" type="SRM 6" isHit="true" isDestroyed="true"/>
				<slot index="4" type="IS Ammo SRM-6" shots="15"/>
			</location>
			<location index="2"> Right Wing
				<armor points="Destroyed"/>
         <slot index="2" type="SRM 6" isHit="true" isDestroyed="true"/>
         <slot index="3" type="SRM 6" isHit="true" isDestroyed="true"/>
				<slot index="4" type="IS Ammo SRM-6" shots="13"/>
			</location>
		</entity>
"

3) Even though the battle output mul file called the Aero Fighters as "Wheeled", the salvage output file called the same units as "aerodyne"... eg.

"		<entity chassis="Riever" model="F-700b" type="Aerodyne" commander="false" offboard="false" hidden="false" deployment="0" deploymentZone="-1" neverDeployed="false" velocity="3" altitude="5" externalId="8b6f6bd7-2951-43c3-b2d2-aadb36a0e00d" camoCategory="-- No Camo --">
			<pilot size="1" name="CMD MAVERICK" nick="" gunnery="3" piloting="4" externalId="b331ec6d-6b62-492b-9708-6ffe671f2882" ejected="false"/>
			<fuel left="400"/>
			<bombs>
			</bombs>
			<structural integrity="0"/>
			<heat sinks="18"/>
      <acriticals avionics="1"/>
      The first slot in a location is at index="1".
			<location index="0"> Nose
				<armor points="83"/>
				<slot index="3" type="IS Ultra AC/20 Ammo" shots="5"/>
				<slot index="4" type="IS Ultra AC/20 Ammo" shots="5"/>
				<slot index="5" type="IS Ultra AC/20 Ammo" shots="5"/>
				<slot index="6" type="IS Ultra AC/20 Ammo" shots="5"/>
				<slot index="7" type="IS Ammo LRM-10" shots="12"/>
				<slot index="8" type="IS Ammo LRM-10" shots="12"/>
			</location>
			<location index="1"> Left Wing
				<armor points="Destroyed"/>
         <slot index="3" type="ISStreakSRM6" isHit="true" isDestroyed="true"/>
				<slot index="4" type="IS Streak SRM 6 Ammo" shots="15"/>
				<slot index="5" type="IS Streak SRM 6 Ammo" shots="15"/>
			</location>
			<location index="2"> Right Wing
				<armor points="25"/>
         <slot index="3" type="ISStreakSRM6" isHit="true" isDestroyed="true"/>
				<slot index="4" type="IS Streak SRM 6 Ammo" shots="15"/>
				<slot index="5" type="IS Streak SRM 6 Ammo" shots="15"/>
			</location>
			<location index="3"> Aft
				<armor points="Destroyed"/>
			</location>
		</entity>
"

this was all from the Megamek 44.0 output file and MekHQ 44.0.

there were more issues that i found, but it was late and a few days ago, as such I have forgotten the details.

at least nothing has crashed so far... thanks for the new stable!

-Mek

### Environment
What version of MekHQ does your issue apply to?
What operating system are you using?  Windows, Mac, or Linux?
What java version are you using?  If unsure it will state your java version at the top of the mekhqlog.txt file.

### Description
Describe the issue and provide screenshots ingame if able.
Provide the rulebook, page number, and text if you feel like this is a rules issue.
And provide the steps you have taken to reproduce the issue in the campaign file if applicable.

### Files
Provide the .cpnx campaign file that this issue occurs in.
Provide any custom units that you are using in this campaign so that it will load on the developers machine.
Provide any other files that you have customized in this campaign like the factions.xml for example.
And provide the mekhqlog.txt file for any NPE's or errors that MekHQ might be reporting.
Do not paste the entire logfile text into this ticket. Just attach the actual mekhqlog.txt file

**Comment by wildj79** [comment] 2018-07-03 18:11
@Mekslayer I would suggest zipping up the files and attaching them to the ticket. The formatting on the issue is off and it would appear that a lot of the information your trying to convey is missing.

**Comment by neoancient** [comment] 2018-07-03 18:32
The `WINGS` location is a virtual location used only for firing arcs (and even then only for fighters that are part of a squadron) and never has any armor assigned to it. The wing armor is assigned independently to the left and right wing locations. When formatted for MUL output any location without armor shows as having the armor destroyed, but in this case it's irrelevant and ignored. I haven't looked at an example, but I suspect the broadside locations on warships do the same thing.

2. An aerodyne unit on the ground (aerospace or conventional fighter, fixed-wing support vee, small craft, or dropship) has the movement mode set to `WHEELED` because it uses the same movement rules as wheeled vehicles. This is reset by MM at the beginning of the game based on the unit's altitude, so the movement mode in the MUL file is irrelevant. I suspect that a post-game mul file for a mech equipped with UMU would show the type as "Biped Swim" if you ended the game with it underwater.

3. See above. The MUL file preserves the persistent condition of the unit, but not the game state.

All I see here is issues with the way data is written to the mul file. Did you have any issues with the way the units were restored in MekHQ?

**Comment by Mekslayer** [comment] 2018-09-03 17:06
These problems come up in the outputted mul file and the end of battle files.

**Closed** 2019-06-30 22:16 UTC
Labels: Needs More Info
