### ISSUE TITLE
20 base turnover threshold TN occurring on with TN of 3 set in campaign settings

### ISSUE THREAD

**Issue by OrbMonky** [MegaMek/mekhq#4783] opened 2024-09-04 19:53 UTC
### Environment
Windows 10, Java 17, 0.50.00 release

### Description
TN is set to 3, but on turnover roll at contract end, base TN is 20. This results in a large portion of the company trying to leave with unattainable TN's to retain.
![image](https://github.com/user-attachments/assets/28c5f82c-128f-4c7c-8219-6fcf56cdad8e)
![image](https://github.com/user-attachments/assets/e556e348-f65e-44d0-8a7f-7105366b9a61)
This campaign was imported from a nightly from late August, and I followed the import steps recommended. It is possible I screwed something up but I am fairly certain it imported correctly. I have xml files in my main folder that show a correct TN of 3 for turnover, as well. Discussion on discord indicates this is likely to be a bug.

### Files
[Helena's Valkyries30230418.cpnx.gz](https://github.com/user-attachments/files/16879288/Helena.s.Valkyries30230418.cpnx.gz)
[customs.zip](https://github.com/user-attachments/files/16879313/customs.zip)

**Comment by IllianiCBT** [comment] 2024-09-04 20:00
The issue here is caused by the 'hide loyalty' option. I don't immediately know why but it's completely massacring your TNs. I recommend turning it off and I'll properly investigate once I'm back from vacation.

**Comment by IllianiCBT** [comment] 2024-09-04 20:06
Note to self: when hide loyalty is enabled we're probably using the raw loyalty value instead of loyalty modifier. As loyalty modifier didn't exist when that code was written and I must have forgotten to change the call.

**Comment by IllianiCBT** [comment] 2024-09-12 18:13
Closing as resolved

**Closed by IllianiCBT** 2024-09-12 18:13 UTC
Labels: Bug, Personnel
