### ISSUE TITLE
Loading save erases ToE, renames entire unit randomly

### ISSUE THREAD

**Issue by repligator** [MegaMek/mekhq#4666] opened 2024-08-17 19:57 UTC
### Environment
Java 17
Linux
https://github.com/MegaMek/mekhq/pull/4656 (The same behavior on save load is exhibited under latest master https://github.com/MegaMek/mekhq/commit/b3e0e4457a766489e5545398116ef0d341862003)

### Description
I was trying to edit my ToE when I encountered an NPE. I wanted to make sure the NPE wasn't intermittent, so I saved the game, and loaded the save. I was greeted by an empty TOE for "The Leaky Bounty Hunters". I saved this file, closed MHQ, and opened the first save again, to find an empty TOE for "X-Ray's Cataphracts".

Loading the autosave works fine, but the manual saves erase the TOE and randomize the unit name.

### Files
[Yakuza3830420101.cpnx.gz](https://github.com/user-attachments/files/16646694/Yakuza3830420101.cpnx.gz)

[whatisthisidonteven-mekhq.log](https://github.com/user-attachments/files/16646351/whatisthisidonteven-mekhq.log)
[mekhq.log](https://github.com/user-attachments/files/16646352/mekhq.log)
[Autosave-1-Yakuza38-30411231.cpnx.gz](https://github.com/user-attachments/files/16646353/Autosave-1-Yakuza38-30411231.cpnx.gz)
[Leaky Bounty Hunters-what.cpnx.gz](https://github.com/user-attachments/files/16646354/Leaky.Bounty.Hunters-what.cpnx.gz)
[Autosave-1-Yakuza38-30411231.cpnx.gz](https://github.com/user-attachments/files/16646355/Autosave-1-Yakuza38-30411231.cpnx.gz)

**Comment by Tzahr** [comment] 2024-08-17 22:32
I don't seem able to replicate this. 
The error in the log ref. unit commander makes me think this _might_ be to do with the work on force commanders Illiani might have done recently, but it's a stab in the dark.

**Comment by repligator** [comment] 2024-08-17 23:05
> I don't seem able to replicate this. The error in the log ref. unit commander makes me think this _might_ be to do with the work on force commanders Illiani might have done recently, but it's a stab in the dark.
I uploaded the wrong save file. This is the one that will cause the bug. I've edited the original post as well.
[Yakuza3830420101.cpnx.gz](https://github.com/user-attachments/files/16646690/Yakuza3830420101.cpnx.gz)

**Comment by Tzahr** [comment] 2024-08-18 01:11
That'll explain it. Does replicate now.

**Comment by IllianiCBT** [comment] 2024-08-18 23:37
Confirming resolved by Nick's PR.

This was caused by me not correctly handling units who are in the TOE, but lack a crew (and therefore a commander), such as your Cronus. This interrupted the loading of your save, which meant the placeholder campaign name was never overwritten - hence the weird renaming issue.

Closing as resolved.

**Closed by IllianiCBT** 2024-08-18 23:37 UTC
Labels: Bug
