### ISSUE TITLE
No Stratcon map on contract

### ISSUE THREAD

**Issue by repligator** [MegaMek/mekhq#5150] opened 2024-10-29 17:26 UTC
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Critical (Game-breaking/Crash): The game crashes or a core feature (like saving, loading, or network connection) is completely unusable.

### Brief Description *

While on a self created contract, I can't see the Stratcon Map. Saving/loading doesn't solve the issue, nor does making a new contract.

### Steps to Reproduce

1. Load attached save
2. Press ATB Campaign State
3. Note lack of map

### Operating System *

Linux

### Java Version *

17

### MekHQ Suite Version *

Free Text (type manually)

### Custom MekHQ Version

https://github.com/MegaMek/mekhq/commit/a0778044a5c33d90011ab7a7f1c913a00cab7212

### Attach Files

[mekhq.log](https://github.com/user-attachments/files/17560814/mekhq.log)
[CGB306230640201.cpnx.gz](https://github.com/user-attachments/files/17560816/CGB306230640201.cpnx.gz)

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by IllianiCBT** [comment] 2024-10-29 20:59
Please could you detail the exact steps you took to get to this situation? Of particular interest is whether this contract taken from the market or whether it was one you created using the Add Mission button.

**Comment by repligator** [comment] 2024-10-30 02:32
Sorry for the late reply. I think this is limited to self created contracts, I will try to confirm in a second.

1. Briefing room.
2. Add mission
3. New Contract
4. Screenshot shows contract settings (not sure if this was the exact contract but it would be very similar)

![Screenshot_20241029_130751](https://github.com/user-attachments/assets/8cb741ef-6624-4ce4-892a-38f846e5b1ec)

**Comment by IllianiCBT** [comment] 2024-10-30 02:36
What employer?

**Comment by repligator** [comment] 2024-10-30 02:38
Ghost Bear Dominion, since I'm playing as a state force (as opposed to mercs).

**Comment by IllianiCBT** [comment] 2024-12-18 05:02
To my knowledge this was caused by an issue with custom mission creation that has since been resolved.

Closing as resolved, but let us know if this is wrong so the case can be reopened if necessary :)

**Closed by IllianiCBT** 2024-12-18 05:02 UTC
Labels: StratCon, Blocker, Severity: Critical
