### ISSUE TITLE
Unable to right click individual personnel.

### ISSUE THREAD

**Issue by Stm316** [MegaMek/mekhq#4289] opened 2024-06-25 11:51 UTC
### Environment
Nightly #1532
Build Date: 2024-06-24T01:16:57.498256100
Today: 2024-06-25
Origin Project: MekHQ
Java Vendor: Eclipse Adoptium
Java Version: 17.0.11
Platform: Windows 10 10.0 (amd64)
System Locale: en_AU
Total memory available to MekHQ: 2 GB

### Description
I can't right click individual ACTIVE personnel without an error. A group works fine.
I can change the status of a group, then right-click on individuals works. If I change them back to ACTIVE, right-click throws the error again. I have tried starting mulitple campaign with different presets, and loading existing games (both with and without resarting program). It seems consistent.

### Files

[My Campaign30250101.cpnx.gz](https://github.com/user-attachments/files/15970390/My.Campaign30250101.cpnx.gz)

![image](https://github.com/MegaMek/mekhq/assets/156564469/088cc41f-2ed9-4c98-bc13-42ea09564fc3)

[mekhq.log](https://github.com/user-attachments/files/15970410/mekhq.log)

**Comment by IllianiCBT** [comment] 2024-06-25 11:54
This is one of mine. I’ll push a fix once I’m done with yard work

**Comment by IllianiCBT** [comment] 2024-06-25 14:45
This error is caused by an instance of 'Bonus XP' in one of your academies. However, 'Bonus XP' was replaced by 'XP last week and no longer appears in any of the local or prestigious academies.

Are you using a customized academy set? If not, it's worth reinstalling your nightly environment because it's not using the most current version of the academy files.

**Comment by Stm316** [comment] 2024-06-25 20:15
Maybe because with the save I tried being from an older build they were clan educated? <eduAcademyFaction>CFM</eduAcademyFaction> was buried in there. Possible culprit?

**Comment by IllianiCBT** [comment] 2024-06-25 20:28
That shouldn't be an issue, as the right-click menu is only pulling current data. Are you doing a clean install whenever you update across Nightlies, or are you transferring things across nightlies? I'm wondering whether you might still have the Clan academies file - as that would still be using 'Bonus XP'?

**Comment by Stm316** [comment] 2024-06-25 20:30
I did. New d/l, new folder. Custom awards is all i've got. I'll get the latest and try again.

**Closed** 2024-06-25 20:42 UTC
Labels: Won't Fix
