### ISSUE TITLE
[0.49.19.1] Weapon Specialst SPA frequently picks unrelated weapon when granted from skill-up random SPA award

### ISSUE THREAD

**Issue by PhoenixHeart512** [MegaMek/mekhq#4244] opened 2024-06-19 19:13 UTC
### Environment
megamek.MegaMek.initializeLogging(MegaMek.java:118) - Starting MegaMek v0.49.19.1
	Build Date: 2024-05-10T20:11:07.453164161
	Today: 2024-06-18
	Origin Project: MegaMekLab
	Java Vendor: Eclipse Adoptium
	Java Version: 17.0.6
	Platform: Windows 10 10.0 (amd64)
	System Locale: en_US
	Total memory available to MegaMek: 4 GB

(probably also affects 49.20)

### Description
When a vehicle pilot or gunner uses XP to rank up from regular to veteran, or veteran to elite, if they are randomly awarded either Sandblaster or Weapon Specialist, the weapon it is assigned for is very often NOT a weapon that is equipped to the vehicle they are asigned to. For example, I have seen vehicle pilots get assigned Protomech/BA weapon specialist, such as the screenshot below where this gunner received "Weapon Specialist [MRM 4]"
![image](https://github.com/MegaMek/mekhq/assets/101755917/6e870f45-849e-41dd-b38c-3f6f1ee10faa)

This does not ALWAYS happen though, sometimes when ranking up it WILL consistently pick a weapon from the vehicle they are assigned to. In the last mission I did, after coming back and ranking up several vehicle gunners, all 3 that received Weapon Specialist received it for a weapon from their assigned vehicle, which is statistically (almost) impossible given how many possibilities for that skill exist in the game code:

![image](https://github.com/MegaMek/mekhq/assets/101755917/6e302844-db21-4352-8c5e-581a2d217f42)

From what I remember, every instance where it assigned it for a weapon from the person's vehicle occurred immediately after a scenario was finished. However, other times I have finished a scenario and it assigned completely random weapons, so it's not consistent.

The conditions that were in place when it assigned the correct weapons today were:

- Scenario was generated and played without closing/re-opening mekHQ (weekly Monday mission in stratcon)
- just returned from a scenario
- game has not been saved/loaded and mekHQ has not been closed and re-opened yet
- These vehicles were teh primary assigned lance of the mission (both as the seed lance and also the ones I actually sent as the primary)
- One of the vehicles had some injured crew but no deaths

It's also worth noting that this behavior does NOT affect opfor pilot SPA's generated for mekHQ scenarios. When loading a mekHQ scenario, all enemy units with Weapon Specialist or Sandblaster SPA's are valid for the vehicle they are driving.

Attached are my campaign save file and the previous day autosave.

### Files
[Weapon Spec SPA.zip](https://github.com/user-attachments/files/15905113/Weapon.Spec.SPA.zip)

**Comment by repligator** [comment] 2024-06-19 19:52
Okay, done some testing.

During Company Generator, `mekhq/campaign/personnel/SpecialAbility.java` is used. Because the SPA occurs before the pilot is assigned a mech, a random weapon is chosen.
When Weapon Specialist is randomly called upon when increasing skills, and the pilot in question is in a mech, it will use one of the weapons on the mech. See `mekhq/gui/adapter/PersonnelTableMouseAdapter.java` .
When Weapon Specialist is randomly called upon when increasing skills, and the pilot in question is **not** in a mech, `mekhq/campaign/personnel/SpecialAbility.java` is used, and a random weapon is chosen.

The following save has all SPA's disabled except for cluster hitter and weapon specialist, for ease of testing.
[SPA Testing.cpnx.gz](https://github.com/user-attachments/files/15905379/SPA.Testing.cpnx.gz)

**Comment by PhoenixHeart512** [comment] 2024-06-19 20:59
Any idea why SOMETIMES vehicle crews do actually pick from the list of weapons equipped to their attached vehicle? 

It's happened far too many times to be random chance, because when it happens (like in the screenshot above), ALL of the new Weapon Specialist's get a weapon from their tank, not just one or two.

Most of the time though (like 75-90% of the time) it matches with what you described above and is pure random.

**Comment by repligator** [comment] 2024-06-19 21:35
Don't ask me why it didn't occur to me to test this on vehicle crews instead of mech pilots until now...

When using Hire Minimum Compliment, `mekhq/campaign/personnel/SpecialAbility.java` is used. The roll is random, and does not use the unit they are being hired to crew.
When Weapon Specialist is randomly called upon when increasing skills, and the person in question is in a vehicle, it will use `mekhq/campaign/personnel/SpecialAbility.java`, randomly selecting a weapon from the vehicle.

I'm guessing that there is something to do with scenarios/missions/TOE that is affecting the result.

**Comment by repligator** [comment] 2024-06-19 22:17
Still working as intended when...
...the vehicle is stripped of all functional parts.
...the person is injured.
...the person is pregnant.
...the person has a secondary role.
...the person is deployed to a scenario.
...the person is deployed to a scenario on the day of the scenario.
...the person is returning from a scenario.
...the person is the highest ranking individual in the vehicle.
...the person is the lowest ranking individual in the vehicle.
...the person is not ranked at all, but others in the vehicle are.
...the vehicle has only a single type of weapon.
...the vehicle is on the TOE.
...the vehicle is not on the TOE.
...the person is married.
...the person has returned from a scenario.
...the skills are increased from the mass personnel training menu.
...the person is the unit commander.


Possibly related, but still working as intended; the weapon will be randomly assigned if the person is Clan in a vehicle with all IS weapons.

**Comment by IllianiCBT** [comment] 2024-06-19 22:36
...its a Wednesday
...the commander is drunk
...its overcast
...the moon is in its third quarter

**Comment by PhoenixHeart512** [comment] 2024-06-19 23:16
Let's be honest, ANY of those could be the culprit xD

**Comment by repligator** [comment] 2024-06-20 18:59
...the date is in "the future" of Battletech (past 3152).
...the unit name has `""` in it.
...the unit name has a`-` in it.
...the unit has a model name that is **not** written in `()`
...the unit has been given a name by the player.
...the unit is lacking a full crew.
...the unit is tagged as custom.
...the unit is the persons original unit (ie they own it).
...the unit is somebody else's original unit.

and a not-sure-if-working-as-intended:
If the unit is above the tech level (ie experimental in a campaign set to standard), the person will receive a random weapon, even if the weapons on the vehicle are within the campaigns tech level.

**Comment by repligator** [comment] 2024-06-20 19:40
Alright, I've finally been able to make some progress.
If the vehicle has only 1 weapon, AND that weapon is an Introductory Small Laser, a weapon will be randomly selected, instead of automatically choosing Small Laser. If you manually assign Weapon Specialization by spending XP for it, small laser is still considered a valid option.

**Comment by IllianiCBT** [comment] 2024-11-19 22:04
#5225 renders this no longer relevant. Closing.

**Closed by IllianiCBT** 2024-11-19 22:04 UTC
Labels: SPA
