### ISSUE TITLE
3.27 : Megamek options -> Tech level is stuck on Standard

### ISSUE THREAD

**Issue by Question2** [MegaMek/mekhq#83] opened 2016-05-23 16:19 UTC
If you go into file -> megamek options and change the tech level to anything other than standard, and then reload the campaign save, the tech level will go back to standard again. It seems mekHQ cannot remember the tech level setting and will just keep resetting it to standard tech level. Oddly enough, it can remember all the other megamek settings, just not the tech level.

[#battletech.zip](https://github.com/MegaMek/mekhq/files/277817/battletech.zip)

**Comment by pheonixstorm** [comment] 2016-05-23 16:46
Duplicate of #84 One or the other should be closed.

**Comment by pheonixstorm** [comment] 2016-05-24 04:04
I've been digging around on this and I believe it is rooted around this error

> Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at mekhq.gui.CampaignGUI.setCampaignOptionsFromGameOptions(CampaignGUI.java:8726)

**Comment by Question2** [comment] 2016-05-24 07:43
Oh my bad, i got an error while posting this one so i thought it didnt go through and posted #84.

**Closed** 2016-09-26 05:22 UTC
