### ISSUE TITLE
Can Replace Weapons When A Spare Does Not Exist

### ISSUE THREAD

**Issue by BLOODWOLF333** [MegaMek/mekhq#462] opened 2017-09-18 23:07 UTC
Testing Kipsta's rush_jobs branch/PR.  I sold all medium lasers in my warehouse, destroyed the med lsr in my Stinger's RA and some other components.  Repair icon did not change red to indicate a part needs to be ordered. Advanced day and made no difference.  HQ allows techs to replace weapons/components when a spare does not exist in the warehouse whether through the mass repair or manually, tested both ways.

[HQWeaponReplace.zip](https://github.com/MegaMek/mekhq/files/1312541/HQWeaponReplace.zip)

**Comment by BLOODWOLF333** [comment] 2017-09-18 23:27
Actually it has been repairing the medium laser, misread.  Checking the box should mean destruction for a single crit component but HQ is reading it as damaged.  How could the player specify between the two states of damage?

**Comment by neoancient** [comment] 2017-09-18 23:49
Per StratOps, p. 177ff, an item that takes a critical hit can be repaired on a 2d6 roll of 10+. I'm working from memory, but I believe this determination is made during scenario resolution. If the part is considered destroyed it is removed from the unit. Any damaged part found on a unit is therefore considered repairable. I believe it's working as intended.

**Comment by BLOODWOLF333** [comment] 2017-09-18 23:52
Yeah this was a waste. ooops

**Comment by kipstafoo** [comment] 2017-09-19 10:29
@neoancient I agree with you, with caveats. What @BLOODWOLF333 didn't mention is that this damage didn't come from a scenario, it came from GM editing a unit within MHQ. I haven't looked at the code recently, so it may be using the same code, but this is also confusing. If you, as GM, go in a mark all the crits as destroyed I agree with @BLOODWOLF333 that one would assume the item itself is destroyed.

Maybe the solution here is to have an additional 'destroyed' checkbox next to the crit boxes when editing a unit?

**Comment by neoancient** [comment] 2017-09-19 13:16
Here is the part of the code that test for destroyed vs. damaged (this example comes from `EquipmentPart`; other parts follow a similar procedure).
>			if(checkForDestruction
>					&& hits > priorHits
>					&& Compute.d6(2) < campaign.getCampaignOptions().getDestroyPartTarget()) {
>				remove(false);
>				return;
>			}
If a part is destroyed it is removed from the unit and discarded. The way to do this by editing the unit is to scrap the part.

**Comment by kipstafoo** [comment] 2017-09-19 16:33
I agree... but also thinking about this for other uses. For example, I use MHQ to manage my tabletop game. I build a scenario then edit the incoming MUL to apply damage. Having more fine grained control over the destroyed/damaged flag would be helpful.

I'll re-close this issue as it's really not a problem, but a future enhancement.

**Closed by kipstafoo** 2017-09-19 16:33 UTC
