### ISSUE TITLE
Base Attack (Defense) mission generate with no Allies or OpFor in AtB

### ISSUE THREAD

**Issue by BlueThing00** [MegaMek/mekhq#695] opened 2018-04-02 02:35 UTC
### Environment
MekHQ: 0.43.9
OS: Windows 10
Java: 1.8.0_161-b12

### Description
A Base Attack (Defense) mission was generated with no Allies or Opfor.

This exception is in mekhqlog.txt:
```
Exception in thread "AWT-EventQueue-0" java.lang.ArrayIndexOutOfBoundsException: -1
	at mekhq.campaign.mission.atb.scenario.BaseAttackBuiltInScenario.setExtraMissionForces(BaseAttackBuiltInScenario.java:83)
	at mekhq.campaign.mission.AtBScenario.setStandardMissionForces(AtBScenario.java:722)
	at mekhq.campaign.mission.AtBScenario.setForces(AtBScenario.java:655)
	at mekhq.campaign.mission.atb.AtBScenarioFactory.createScenariosForNewWeek(AtBScenarioFactory.java:286)
	at mekhq.campaign.Campaign.newDay(Campaign.java:2415)
	at mekhq.gui.CampaignGUI.advanceDay(CampaignGUI.java:1406)
	at mekhq.gui.CampaignGUI.access$2100(CampaignGUI.java:163)
	at mekhq.gui.CampaignGUI$48.actionPerformed(CampaignGUI.java:1224)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
	at java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
```

### Files
[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/1866944/mekhqlog.txt)

**Comment by NickAragua** [comment] 2018-04-02 02:45
For future reference, a saved game (with custom units included) is generally very helpful in reproducing a defect. 

This issue is probably a duplicate of #674 (where the allies or opfor don't have a RAT entry for the given year), although I'll keep it open in case the saved game shows different results.

**Comment by BlueThing00** [comment] 2018-04-02 15:15
I've tried using my latest saved game to try to reproduce this several times, but even when a Base Attack mission is generated, it does not reproduce the bug.

**Closed** 2018-05-08 00:58 UTC
Labels: bug
