### ISSUE TITLE
0.48 Tech Specialist Not Applied to Maintenance Rolls

### ISSUE THREAD

**Issue by ndilday** [MegaMek/mekhq#2535] opened 2021-04-20 21:06 UTC
### Environment
What version of MekHQ does your issue apply to? 0.48
What operating system are you using?  Windows, Mac, or Linux? Windows 10
What java version are you using?  8.0.2610.12 (though I don't see this in the log file as suggested)

### Description
The text for the "Tech Specialist" Abilities states that the modifiers apply to "repair and maintenance", but those abilities are currently only being applied to repair. ​Part.getAllModsForMaintenance ​seems like the right place for it.

**Comment by Windchild292** [comment] 2021-04-20 21:52
Duplicate of #2496

**Closed by Windchild292** 2021-04-20 21:52 UTC
Labels: bug
