### ISSUE TITLE
Base Attack (Defender): No base appears on StratCon map

### ISSUE THREAD

**Issue by repligator** [MegaMek/mekhq#4584] opened 2024-08-08 16:55 UTC
### Environment
Linux
Java 17
Master (latest PR https://github.com/MegaMek/mekhq/commit/a45a5251c44f7ab1cc47069bbc66e66f61ecd4c4)

### Description
I'm testing the new presets for the first time, so this may just be some sort of misunderstanding on my part. A Base Attack (Defender) scenario generated. However, there are no bases on the StratCon map. There was at one point an enemy base, but I destroyed it earlier. This a regular Base Attack mission, not the "if you lose mission over" kind.

![Screenshot_20240808_125112](https://github.com/user-attachments/assets/ff14c98c-0688-4072-904a-864b1d0486d2)
![Screenshot_20240808_125038](https://github.com/user-attachments/assets/84592cc2-d188-4ff0-8917-36089a26e962)

### Files
[where is the base Harold's Hunchbacks31511008.cpnx.gz](https://github.com/user-attachments/files/16551146/where.is.the.base.Harold.s.Hunchbacks31511008.cpnx.gz)
[mekhq.log](https://github.com/user-attachments/files/16551164/mekhq.log)

**Comment by Thom293** [comment] 2024-08-08 17:56
That appears to be the "Unbreakable Morale" Base Attack mission.  It will happen weekly until their morale drops and does not appear on the map. Working as intended I believe.

**Comment by IllianiCBT** [comment] 2024-08-08 19:44
Unbreakable base attacks are a legacy scenario and don’t appear on the StratCon map.

closing as working as intended :)

**Closed by IllianiCBT** 2024-08-08 19:44 UTC
Labels: StratCon
