### ISSUE TITLE
50.00 "Use StratCon Rules" appears twice on that Campaign Options tab.  

### ISSUE THREAD

**Issue by Thom293** [MegaMek/mekhq#4550] opened 2024-08-05 04:28 UTC
Also the top one seems confusingly named.  

![image](https://github.com/user-attachments/assets/4ec764a0-bd72-4e1e-b601-fb309468ee4d)

**Comment by IllianiCBT** [comment] 2024-08-05 04:31
That looks like an error caused by a bad merge.

**Comment by Thom293** [comment] 2024-08-05 04:38
Its the OID version updated today, if it matters.

**Comment by IllianiCBT** [comment] 2024-08-05 04:45
Wait, this is actually working as intended. It looks like the verbiage was changed to show that this option also relates to StratCon

**Comment by Thom293** [comment] 2024-08-05 04:49
Then if you scroll to the bottom - that one should be deleted I think?

**Comment by IllianiCBT** [comment] 2024-08-05 04:52
I think the top option might need to be reworded. They’re both needed, because the top one enables AtB, while the bottom enables StratCon. I can’t remember which contributor changed the wording, but it was part of a greater attempt to help clear things up. I do agree that here it’s probably not as clear as they hoped.

**Comment by Thom293** [comment] 2024-08-05 04:55
Yeah in the past always needed both for SC.  

I always thought it was odd that SC one was at the bottom off the bottom of the page.  Now that its been promoted to beta, perhaps both should be at top?  Regardless, top one is kinda confusing.

**Comment by IllianiCBT** [comment] 2024-08-05 04:56
The AtB tab is full of legacy formatting so it’s a bit of a pain to change

**Comment by repligator** [comment] 2024-08-05 10:55
> I can’t remember which contributor changed the wording, but it was part of a greater attempt to help clear things up. I do agree that here it’s probably not as clear as they hoped.

Ha, that'd be me. See https://github.com/MegaMek/mekhq/pull/4396 . I agree that the wording leaves a lot to be desired.

**Comment by IllianiCBT** [comment] 2024-08-07 01:34
> Ha, that'd be me. See #4396 . I agree that the wording leaves a lot to be desired.

Do you want to handle the fix, or should I see if I can conjure some fancy words?

**Comment by repligator** [comment] 2024-08-07 02:30
> > Ha, that'd be me. See #4396 . I agree that the wording leaves a lot to be desired.
> 
> Do you want to handle the fix, or should I see if I can conjure some fancy words?

If it's all-right I'll leave the wording to you.

**Comment by IllianiCBT** [comment] 2024-08-07 16:15
Closing as resolved

**Closed by IllianiCBT** 2024-08-07 16:15 UTC
Labels: GUI
