### ISSUE TITLE
0.45.2 cant handle battlearmor

### ISSUE THREAD

**Issue by Numero-Five** [MegaMek/mekhq#1025] opened 2019-01-01 07:45 UTC
What version of MekHQ does your issue apply to? 0.45.2
What operating system are you using?  Windows
What java version are you using?  Java 8?

I started a new campaign and I tried to add battlearmor units to my unit. the battlearmor units showed up in my hanger bay, but when selected no details show up in the side window

![image1](https://user-images.githubusercontent.com/46292554/50571093-70f50d80-0d55-11e9-8701-2c4ee7bc4afe.png)

![image2](https://user-images.githubusercontent.com/46292554/50571095-75212b00-0d55-11e9-88c3-eaac827cb55b.png)

I also found that Meklab will not save battlearmor files.

non-battlearmor infantry works just fine in both Mekhq and Meklab

**Comment by sixlettervariables** [comment] 2019-01-01 13:41
Duplicate of #1010. Fixed in #1011.

**Closed by sixlettervariables** 2019-01-01 13:41 UTC
