### ISSUE TITLE
The Campaign File could not be loaded

### ISSUE THREAD

**Issue by CorvidQuixote** [MegaMek/mekhq#1323] opened 2019-11-03 23:10 UTC
[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/3802256/mekhqlog.txt)

### Environment
version of MekHQ:  0.46.0
operating system: Windows
java version  8

### Description
I closed my game because it froze, and when I tried to load my autosave it was unpopulated. When I went to load a previous manual save, I got the error "The campaign file could not be loaded. please check the log file".  This error effects the last six or so saves. The log file lists some errors with a battle armor quirk, though I did not use that armor in my units. I also had a mech being refitted in MekLab - I didn't see an error attached there, but that is the main difference between the older saves that work and the new saves that do not.

### Files

GitHub does not allow me to load the .cpnx file - it says that file type is not supported. I do not know how to get around this.

**Comment by HammerGS** [comment] 2019-11-03 23:14
You can zip the files and attach them. We'll need logs, custom units and the cpnx file.

**Comment by CorvidQuixote** [comment] 2019-11-03 23:34
Non working save:
[Amazons30670726.zip](https://github.com/MegaMek/mekhq/files/3802310/Amazons30670726.zip)

Last working save:
[Amazons30670103.zip](https://github.com/MegaMek/mekhq/files/3802312/Amazons30670103.zip)

This is the Mech that was being refitted, that's the only custom unit. I have custom pilot photots, if that would make a difference?:
[Marshal MHL-XD.zip](https://github.com/MegaMek/mekhq/files/3802314/Marshal.MHL-XD.zip)

**Comment by HammerGS** [comment] 2019-11-03 23:39
We still need the Megameklog.txt and MekHQ.txt file from the logs folder, from when you try to load the non-working save.

**Comment by CorvidQuixote** [comment] 2019-11-03 23:41
[megameklog.txt](https://github.com/MegaMek/mekhq/files/3802319/megameklog.txt)
[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/3802320/mekhqlog.txt)

**Comment by HammerGS** [comment] 2019-11-04 00:19
NPE from log

```
java.lang.NullPointerException
	at mekhq.campaign.personnel.Injury.getModifiers(Injury.java:242)
	at mekhq.campaign.personnel.Person.lambda$getPilotingInjuryMod$5(Person.java:3634)
	at java.util.stream.ReferencePipeline$7$1.accept(Unknown Source)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.ReferencePipeline.forEach(Unknown Source)
	at mekhq.campaign.personnel.Modifier.calcTotalModifier(Modifier.java:57)
	at mekhq.campaign.personnel.Person.getPilotingInjuryMod(Person.java:3634)
	at mekhq.campaign.unit.Unit.calcCompositeCrew(Unit.java:3151)
	at mekhq.campaign.unit.Unit.resetPilotAndEntity(Unit.java:2906)
	at mekhq.campaign.io.CampaignXmlParser.parse(CampaignXmlParser.java:584)
	at mekhq.campaign.CampaignFactory.createCampaign(CampaignFactory.java:88)
	at mekhq.gui.dialog.DataLoadingDialog$Task.doInBackground(DataLoadingDialog.java:210)
	at mekhq.gui.dialog.DataLoadingDialog$Task.doInBackground(DataLoadingDialog.java:129)
```

**Comment by CorvidQuixote** [comment] 2019-11-04 01:04
Sadly, I don't really know what to do with that information?

**Comment by HammerGS** [comment] 2019-11-04 01:05
Nothing, that's likely the bug. It's to save the coders a little time when they start looking at it.

**Comment by CorvidQuixote** [comment] 2019-11-04 01:10
Thanks - on my end, any way I could get into that save, or should I just restart from the older one?

**Comment by HammerGS** [comment] 2019-11-04 01:12
Your best, to go with an older one. I'm not one of the coders but I *think* something involving an injury is causing the issue.  

You could try down loading 0.47 and making a copy of your save game and trying it under that version.  But you'll likely not be able to go back to 0.46 with that version.

**Comment by neoancient** [comment] 2019-11-04 04:46
0.47.0 has the same problem. In the problem campaign file the injury types are not recorded. The last working file does not have any injuries to the personnel listed. When I edited the problem file and added the injuries it loaded fine, and I was also able to save it and load the saved file, so the problem is not a matter of writing the campaign data to the file. It will take some more work to figure out how the type field ended up blank. But in the meantime here's the fixed file: 
[Amazons30670726_fixed.zip](https://github.com/MegaMek/mekhq/files/3802708/Amazons30670726_fixed.zip)

**Comment by sixlettervariables** [comment] 2021-03-14 18:54
Closing for now as we've not seen any other reports of this, and its not obvious how this would come about through normal MekHQ usage. Please re-open this issue if you see it again @CorvidQuixote.

**Closed by sixlettervariables** 2021-03-14 18:54 UTC
Labels: Needs Investigation, bug
