### ISSUE TITLE
Return value of "mekhq.campaign.Campaign.getSystemById(String)" is null

### ISSUE THREAD

**Issue by repligator** [MegaMek/mekhq#4434] opened 2024-07-18 00:10 UTC
### Environment
Developmental
Java 17
Linux

### Description
NPE when advancing from December 31st to January 1st. May be education related(?)

`20:06:28,199 ERROR [mekhq.MekHQ] {AWT-EventQueue-0}
mekhq.MekHQ.lambda$main$1(MekHQ.java:280) - Uncaught Exception Detected
java.lang.NullPointerException: Cannot invoke "mekhq.campaign.universe.PlanetarySystem.getPopulation(java.time.LocalDate)" because the return value of "mekhq.campaign.Campaign.getSystemById(String)" is null
	at mekhq.campaign.personnel.education.EducationController.checkForAcademyDestruction(EducationController.java:704)`

### Files
[mekhq.log](https://github.com/user-attachments/files/16275991/mekhq.log)
[system_id_NPE_Fronc Marshals30720101.cpnx.gz](https://github.com/user-attachments/files/16276002/system_id_NPE_Fronc.Marshals30720101.cpnx.gz)

**Comment by IllianiCBT** [comment] 2024-07-18 00:21
Yeah, that looks like one of mine. That error usually means that it’s been unable to find the system. Are you using a custom academy set?

**Comment by repligator** [comment] 2024-07-18 00:28
> Yeah, that looks like one of mine. That error usually means that it’s been unable to find the system. Are you using a custom academy set?
Nope, everything is stock. I'm operating out in the Fronc Reaches FWIW.

**Comment by IllianiCBT** [comment] 2024-07-18 20:57
I don't suppose you have a save from the 31st December? It would be helpful if I could see the issue in action, so I can better identify what caused it.

**Comment by IllianiCBT** [comment] 2024-07-18 21:09
Nevermind, I was able to find the cause by going through the save file

**Comment by IllianiCBT** [comment] 2024-07-18 21:14
Closing as resolved (manually closing to make it easier for me to see what issues still need actioning).

**Closed by IllianiCBT** 2024-07-18 21:14 UTC
Labels: Bug, Personnel
