### ISSUE TITLE
3.32 Mass Training Tool allows KIA personel to spend XP

### ISSUE THREAD

**Issue by VampireSeraphin** [MegaMek/mekhq#189] opened 2016-10-06 18:53 UTC
Pretty much what it says on the tin. I discovered that the tool does not seem to know the difference between regular and KIA personnel. Might also apply to retired and MIA as well, but I did not check that.

**Comment by Akjosch** [comment] 2016-10-06 18:56
Duplicate of #185. Already fixed in the most recent release.

**Closed by Akjosch** 2016-10-06 18:56 UTC
