### ISSUE TITLE
[0.50.0 Nightly CI #1600]: Mercenary OpFor has no Faction - Loses Generated Name on Save Reload

### ISSUE THREAD

**Issue by UlyssesSockdrawer** [MegaMek/mekhq#4757] opened 2024-08-31 19:25 UTC
### Environment
Version: 0.50.0 CI#1600 Nightly - StratCon MHQ campaign
Java: 17
OS: Win11

### Description
When a mercenary opfor is generated for a contract, including when opfor is regenerated after the original opfor routs, they will initially generate with an auto-faction name.

However, once the save file is reloaded, the name is gone and the opfor is listed as 'Unknown'.

This relates to #4755 as the Mercenary faction does not seem to get assigned (@Sleet01 probably butchering what's going on behind the scenes here - please add more detail if you can!)

![image](https://github.com/user-attachments/assets/8e1d0a58-a613-4972-baf3-175a024d4ccd)

### Files
[The Nova Dragoons-PreNPEScenario.cpnx.gz](https://github.com/user-attachments/files/16825788/The.Nova.Dragoons-PreNPEScenario.cpnx.gz)

Save is the same one from #4755

**Comment by IllianiCBT** [comment] 2024-08-31 19:27
I’m on a coding break until the 8th. I’ll take a look then, assuming nobody else gets there first

**Comment by IllianiCBT** [comment] 2024-09-25 17:40
So this is interesting, 'Mercenary' as a faction doesn't appear to be a valid enemy for the Fed Suns, which seems to be the root cause of this issue.

**Comment by UlyssesSockdrawer** [comment] 2024-09-25 17:43
I've also had this issue occur on a campaign for the Lyran Alliance.
Mercenary doesn't appear on the dropdown list on my current contract.

**Comment by IllianiCBT** [comment] 2024-09-25 20:43
Mercenaries are a special case, it seems, as they don't really have planetary holdings, so they need to be assigned via the 'show all factions' option.

**Comment by IllianiCBT** [comment] 2024-09-25 20:47
Closing as resolved

**Closed by IllianiCBT** 2024-09-25 20:47 UTC
