### ISSUE TITLE
Vehicle crewmembers throwing off vehicle crew experience rating.

### ISSUE THREAD

**Issue by pheonixstorm** [MegaMek/mekhq#3610] opened 2023-02-19 10:30 UTC
Issue appears to be as old as the vehicle crewmember role

Support vehicles have three types of crew, driver, gunner, and crewmember. When calculating the experience rating for a vehicle crew it is not ignoring crewmembers who use the mechanic skill rather than the two vehicle skills. For a vehicle with a driver, no gunner, and several crewmembers this can result in an experience rating of green or worse for the gunnery rating of the unit. This in turn causes the overall unit rating to be worse than it should be, and that in turn affects the rating score for setting up contracts

**Comment by IllianiCBT** [comment] 2024-08-11 23:49
I have closed off the Reputation side of this bug in #4605, but the part where we transfer data to mm will need to be handled separately

**Comment by IllianiCBT** [comment] 2024-08-11 23:53
Investigating how we calculate composite Gunnery and Piloting skills shows we're only taking into account characters whose possess the relevant Gunnery or Piloting skills. At least insofar as I can see, it does appear to being calculated correctly on our side.

Would you be able to provide an example of where this is an issue? That will help me narrow it down.

**Comment by pheonixstorm** [comment] 2024-08-12 05:34
Looking at this again it seems the unit rating no longer is affected but the experience rating in the Unit/Graphic tab and right TOE pane are showing the incorrect experience rating. Left pane shows correctly. Before, all three locations were showing incorrect values

![TOE View](https://github.com/user-attachments/assets/a2f966a2-272f-49d6-b194-5b8a1d3fe1bd)

**Comment by pheonixstorm** [comment] 2024-08-12 05:37
Campaign file for testing
[My Campaign30670101.cpnx.gz](https://github.com/user-attachments/files/16577736/My.Campaign30670101.cpnx.gz)

**Comment by IllianiCBT** [comment] 2024-08-12 05:37
Can you chuck up a save demonstrating the issue, I can then take a look. I think it’ll be a lot easier for me to appreciate the issue if I can see it in action :)

**Comment by IllianiCBT** [comment] 2024-08-12 05:37
Nevermind, you’re one step ahead of me!

**Comment by IllianiCBT** [comment] 2024-08-14 04:53
So this is actually (kinda) working as intended. The reason why it's showing those crew members is because those are the unit commanders. If you give a rank to any other character in the unit, they will become the unit commander and that's who you'll see as the 'face' of the unit.

Which raises the question: why is it picking crew members instead of other, more experienced, personnel as the commander.

Closing this issue as 'working as intended' and I'll investigate how we pick unit commanders separately.

**Closed by IllianiCBT** 2024-08-14 04:53 UTC
Labels: Bug, Personnel

**Comment by pheonixstorm** [comment] 2024-08-14 05:11
Well wonder what happened... When I posted this that was not the case as it happened even when the driver was the ranked crew. Otherwise SPAs would be limited to whoever was the vehicle officer.

**Comment by IllianiCBT** [comment] 2024-08-14 05:37
Really glad you highlighted this issue, @pheonixstorm. It turned out we were over prioritizing crew members over all other types of unit crew type.

**Comment by IllianiCBT** [comment] 2024-08-14 06:11
It led to us identifying and resolving a related bug (#4634) so it was a net positive :)
