### ISSUE TITLE
Being able to print the mechs and pilots deployed to a scenario in HQ

### ISSUE THREAD

**Issue by Mekslayer** [MegaMek/mekhq#913] opened 2018-09-03 16:56 UTC
So I wanted to print out the mechfiles/mul from HQ for use in a TT battle, but when I click on the print button, nothing comes out in the print out file, just  bunch of blank sheets. Why is that?
Happens in both iOS ad Windows. I only use versions of java 8.

### Environment
What version of MekHQ does your issue apply to?
What operating system are you using?  Windows, Mac, or Linux?
What java version are you using?  If unsure it will state your java version at the top of the mekhqlog.txt file.
(Delete the above lines)

### Description
Describe the issue and provide screenshots ingame if able.
Provide the rulebook, page number, and text if you feel like this is a rules issue.
And provide the steps you have taken to reproduce the issue in the campaign file if applicable.
(Delete the above lines)

### Files
Provide the .cpnx campaign file that this issue occurs in.
Provide any custom units that you are using in this campaign so that it will load on the developers machine.
Provide any other files that you have customized in this campaign like the factions.xml for example.
And provide the mekhqlog.txt file for any NPE's or errors that MekHQ might be reporting.
Do not paste the entire logfile text into this ticket. Just attach the actual mekhqlog.txt file
(Delete the above lines)

**Comment by HammerGS** [comment] 2018-09-03 16:58
Can you review the fields under your comments labelled Environment, and Files.  To help - 

**Environment**
What version of MekHQ does your issue apply to?
What operating system are you using? Windows, Mac, or Linux?
What java version are you using? If unsure it will state your java version at the top of the mekhqlog.txt file.
(Delete the above lines)

**Files**
Provide the .cpnx campaign file that this issue occurs in.
Provide any custom units that you are using in this campaign so that it will load on the developers machine.
Provide any other files that you have customized in this campaign like the factions.xml for example.
And provide the mekhqlog.txt file for any NPE's or errors that MekHQ might be reporting.
Do not paste the entire logfile text into this ticket. Just attach the actual mekhqlog.txt file
(Delete the above lines)_

Without the information we will be unable to determine the issue.

**Comment by Mekslayer** [comment] 2018-09-04 04:57
unable to email you, why?   On Monday, September 3, 2018, 9:55:38 PM PDT, J. T. <mekslayer@yahoo.com> wrote:  
 
 i use both windows 7 and iOS 10+
both didn't work. i use java 8 everywhere... and one of the most recent on the mac.
My cpnx file is really big, and it would take me a while to find and send all the customs. but here is my log file and an attempt to send the cpnx anyways. tell me which customs you need.
-McM


   On Monday, September 3, 2018, 9:58:39 AM PDT, Dave N <notifications@github.com> wrote:  
 
 
Can you review the fields under your comments labelled Environment, and Files. To help -

Environment
What version of MekHQ does your issue apply to?
What operating system are you using? Windows, Mac, or Linux?
What java version are you using? If unsure it will state your java version at the top of the mekhqlog.txt file.
(Delete the above lines)

Files
Provide the .cpnx campaign file that this issue occurs in.
Provide any custom units that you are using in this campaign so that it will load on the developers machine.
Provide any other files that you have customized in this campaign like the factions.xml for example.
And provide the mekhqlog.txt file for any NPE's or errors that MekHQ might be reporting.
Do not paste the entire logfile text into this ticket. Just attach the actual mekhqlog.txt file
(Delete the above lines)_

Without the information we will be unable to determine the issue.

**Comment by Mekslayer** [comment] 2018-09-04 23:40
i use both windows 7 and iOS 10.11.6

both didn't work. i use java 8 everywhere...

[megameklog.txt](https://github.com/MegaMek/mekhq/files/2350614/megameklog.txt)

.

My cpnx file is really big, and it would take me a while to find and send all the customs. but here is my log file and and my cpnx file anyways. tell me which customs you need and I can try to send them to you. There are probably more than a few.

-Mek

**Comment by Mekslayer** [comment] 2018-09-04 23:42
Trying cpnx again.

But it doesn't support this file type... Try again.... is the response.

**Comment by Mekslayer** [comment] 2018-09-05 00:06
ok trying to send my cpnx as a zip file.

no good. .zipx format not accepted... will have to try again later from pc.

**Comment by Mekslayer** [comment] 2018-09-05 18:11
OK Hammer, Here is my cpnx and the custom mech files you might need. Everything else should already be in HQ. Thanks for making sure it prints.
[For_printing.ZIP](https://github.com/MegaMek/mekhq/files/2354031/For_printing.ZIP)

**Comment by neoancient** [comment] 2018-09-06 16:36
Also, we need the mekhqlog.txt file.

**Comment by neoancient** [comment] 2018-09-13 18:31
User has failed to provide all needed files. The required files were stated clearly in the issue template, and even after repeated requests we only have some of the files. It has been a week since the last request with no further activity. Closing as unable to reproduce.

**Closed by neoancient** 2018-09-13 18:31 UTC
Labels: Can't reproduce
