### ISSUE TITLE
When can we get the ability to repair Large Vessels / Warships with more than 1 Tech?

### ISSUE THREAD

**Issue by Mekslayer** [MegaMek/mekhq#3384] opened 2022-06-29 14:50 UTC
Self Explanatory

**Comment by HammerGS** [comment] 2022-06-29 16:33
Duplicate of https://github.com/MegaMek/mekhq/issues/3140

Please review issues tracker prior to opening new issue.

**Closed by HammerGS** 2022-06-29 16:33 UTC
Labels: Duplicate
