### ISSUE TITLE
0.49-DEV-StratCon - Null BotForce PlayerColour

### ISSUE THREAD

**Issue by Kailan7401** [MegaMek/mekhq#2503] opened 2021-04-10 11:46 UTC
### Environment
StratCon alpha test build
Windows 10
OpenJDK 11.0.10

### Description
I have an unable to save error popping as of 08/23/2505 in my game, but I'm not sure what specifically happened to cause it. It looks like MekHQ did attempt to make a save, but it's corrupted and I can't open it. 
On 08/23, I reconned several hexes, revealing two battles, and I sent reinforcements to one of them. I'll attempt to backtrack and duplicate my steps to see if I can provide more detail, but in the meantime I've attached the last file I was able to save (08/20/2505) as well as the corrupted 08/23/2505 save and my most recent logs. 
![image](https://user-images.githubusercontent.com/32316785/114268529-7ebd9100-9a3c-11eb-8bfd-0775119e9bc0.png)

### Files
[megameklog.txt](https://github.com/MegaMek/mekhq/files/6289739/megameklog.txt)
[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/6289740/mekhqlog.txt)
[Campaign Info.zip](https://github.com/MegaMek/mekhq/files/6289743/Campaign.Info.zip)

**Comment by sixlettervariables** [comment] 2021-04-10 12:34
Proximate cause:
```
20:33:49,581 ERROR [mekhq.gui.CampaignGUI] {AWT-EventQueue-0} 
saveCampaign(), line 1339 : null
java.lang.NullPointerException
	at mekhq.campaign.mission.BotForce.writeToXml(BotForce.java:234)
	at mekhq.campaign.mission.AtBScenario.writeToXmlEnd(AtBScenario.java:1583)
	at mekhq.campaign.mission.AtBDynamicScenario.writeToXmlEnd(AtBDynamicScenario.java:406)
	at mekhq.campaign.mission.Scenario.writeToXml(Scenario.java:308)
	at mekhq.campaign.mission.Mission.writeToXmlBegin(Mission.java:215)
	at mekhq.campaign.mission.Contract.writeToXmlBegin(Contract.java:697)
...
```

**Comment by NickAragua** [comment] 2021-04-13 01:00
Fixed with commit 52905d6975e3cd97a4babfbb3b2093702769b837

The error implies that there's no color selected for the bot force, so it'll just be whatever the default color is. Better than failing to save, anyway.

**Comment by Windchild292** [comment] 2021-04-13 01:55
PlayerColour is nonnullable by design. If it is null, that's an issue that goes beyond just saving.

**Comment by Windchild292** [comment] 2021-04-13 03:40
Resolved after reopening, closing once more

**Closed by Windchild292** 2021-04-13 03:40 UTC
Labels: Needs Investigation, StratCon, bug
