### ISSUE TITLE
Large Game Suggestion 2:  Pregenerating lists of Techs able to do refits/customization and assignment

### ISSUE THREAD

**Issue by MageOhki** [MegaMek/mekhq#1985] opened 2020-09-04 10:02 UTC
Environment
47.9, WIndows 10, Latest Java.
Description
Suggestion for speeding up refit process (where it's the most noticeable, but it'd not surprise me if it's elsewhere)  During dayroll, generate a list of techs, instead of doing the list on the fly, for refits/assignment to projects.

Files

Should not be needed

Please delete this, was duplicate

**Comment by Windchild292** [comment] 2020-09-04 12:46
Duplicate of #1943

**Closed by Windchild292** 2020-09-04 12:46 UTC
