### ISSUE TITLE
Unit Rating unsustainable

### ISSUE THREAD

**Issue by bczretribution** [MegaMek/mekhq#570] opened 2017-12-21 10:06 UTC
In the units rating table, the # of units listed under technology seems to grow arbitrarily over time (clicks, not game days) accordingly the required maintenance hours also grows.  Multiple numbers in the support category seem to grow.  I have confirmed their escalation increments as further actions are taken, however, I have not yet been able to identify what actions specifically cause it.  as can be seen in the side by side image bellow, 2 identical forces on the same day have very different ratings.
![unit rating glitch](https://user-images.githubusercontent.com/34722287/34251005-9dfcaee4-e60c-11e7-8e33-11d0db206742.jpg)

**Comment by jslater89** [comment] 2017-12-21 14:08
Likely duplicate of #557 (fixed in PR #565).

**Comment by jslater89** [comment] 2017-12-21 14:14
Hmm. Maybe not. I'll look at this later.

**Comment by jslater89** [comment] 2017-12-21 17:11
@bczretribution Could you post your save game? If you figure out what actions trigger the issue, that would be helpful too.

Just reading the code, it _looks_ like this issue shouldn't be happening anymore, but I'd like to be sure.

**Comment by bczretribution** [comment] 2017-12-21 17:47
https://drive.google.com/file/d/1aTveqkXdcKMNnJiBN6y42cbaV7k3IvMz/view?usp=sharing
Had to sleep, but I will continue to troubleshoot today.

**Comment by bczretribution** [comment] 2017-12-24 05:04
ok, after a bit more troubleshooting (now in 0.43.6) I've figured some things out.  The first image is my rating after a fresh load of my save.  the second is after having done nothing but complete a battle where I took no losses and 1 unit as salvage and sold it (so no net unit change).  In the 3rd image, the only thing I did after taking the second picture was hit end turn.  As can be seen, the # of units it claims I own goes up in each instance causing a gradual decline in that portion of my rating.  It seems that my tech hours, however, remains unchanged.  This would seem to be a different error than #557.  I have Included a save of the campaign file from before the mission (mercmission) and after the advance of a day (merc glitch) in case it helps.  

![unit rating glitch pt1](https://user-images.githubusercontent.com/34722287/34324320-d1d3f59c-e83c-11e7-9091-410757d5be80.png)

![unit rating glitch pt2](https://user-images.githubusercontent.com/34722287/34324321-d871d036-e83c-11e7-8675-6d461e179279.png)

![unit rating glitch pt3](https://user-images.githubusercontent.com/34722287/34324322-db1c117a-e83c-11e7-9515-801b8ed4ee2c.png)

https://drive.google.com/file/d/17Cbe41MQoDip94ZHVguqbnX3V1xqvsAE/view?usp=sharing

https://drive.google.com/file/d/1GkGwYa0LI5-nxnpqbKz_nOUlMy3sc4--/view?usp=sharing

**Comment by jslater89** [comment] 2017-12-28 00:08
Thanks, that's a big help. I'm off work for the next week or two, so I'll see if I can get this sorted out in the next few days. (Probably a similar issue to 557.)

**Closed** 2018-01-13 17:37 UTC
Labels: bug, unit rating
