### ISSUE TITLE
RFE: Load infantry into vehicles in TO&E via assign unit to transport

### ISSUE THREAD

**Issue by DynamicWorlds** [MegaMek/mekhq#4629] opened 2024-08-13 22:15 UTC
### Environment
v0.50.0-SNAPSHOT (2024-08-12 evening's nightly) and earlier
Win 10
Java Vendor: Eclipse Adoptium
Java Version: 17.0.11

### Description
Enable infantry units to be loaded into combat and support vehicles with transport-capacity/infantry-compartment for them (as per how vehicles can be loaded into dropships via "assign unit to transport") so that they don't have to be loaded in the megamek setup window after clicking "start game" and don't count their movement speed toward slowing down lance deployment delay/reinforcement speed.

EX: if I have a lance consisting of infantry loaded into Karnovs or some other transport unit, the lance should be able to reinforce per the speed of the transport rather than taking the normal 30 turns to deploy as per if the infantry were marching to the battle.

### Files

**Comment by Saklad5** [comment] 2024-08-16 20:53
This is a duplicate of https://github.com/MegaMek/mekhq/issues/3650.

**Closed** 2024-08-16 21:08 UTC
Labels: (RFE) Enhancement
