### ISSUE TITLE
MekHQ GM mode Restore unit hang

### ISSUE THREAD

**Issue by monbvol** [MegaMek/mekhq#687] opened 2018-03-30 18:57 UTC
### Environment
MekHQ 043.9 RC3
Windows 10 64 bit
Java 1.8

### Description
In attempting to work around the Infantry field gunners consuming infinite ammo I tried GM mode Restore unit and now MekHQ hangs.
[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/1864497/mekhqlog.txt)
![mekhqgmmoderestoreunithang](https://user-images.githubusercontent.com/17420975/38149907-60c64d3e-3411-11e8-862e-1229fd75afee.png)

### Files
Since MekHQ won't let me save the campaign for now have the log and a screen shot.

**Comment by NickAragua** [comment] 2018-03-30 19:03
From looking at the log, there appears to be some kind of issue with the data/canonUnitQuirks.xml file. Have you modified it at all? If so, can you grab the one from github and see if that helps? https://github.com/MegaMek/mekhq/blob/master/MekHQ/data/canonUnitQuirks.xml

**Comment by monbvol** [comment] 2018-03-30 22:37
I did append some quirks for some custom designs and looks like some
extranious stuff got copied in.

Clearing it out seems to have solved it.

**Comment by NickAragua** [comment] 2018-04-02 01:09
I think we can close this one for now, to be re-opened if we encounter more issues with restoring units.

**Closed by NickAragua** 2018-04-02 01:09 UTC

**Comment by dericpage** [comment] 2018-04-03 14:40
As a aside, if you have custom units that you want to add quirks to, don't edit the cannonUnitQuirks.xml file.  Instead, you should add those to the mmconf/unitQuirksOverride.xml file.

**Comment by arlith** [comment] 2018-04-03 14:41
You don't have to edit the file anymore.  In the MM lobby, you can right click a unit and save its quirks, which will save it to mmconf/unitQuirksOverride.xml.

**Comment by dericpage** [comment] 2018-04-03 14:42
Ah, been out of the loop a bit.  Still, the main point is: don't edit cannonUnitQuirks.xml.

**Comment by arlith** [comment] 2018-04-03 14:43
No problem; my comment was intended to be informative.
