### ISSUE TITLE
[MEKHQ V.50.01] TO&E forces wiped on campgain load

### ISSUE THREAD

**Issue by BiggestBoss1** [MegaMek/mekhq#5204] opened 2024-11-17 17:36 UTC
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Medium (Gameplay Limitation): Non-core functionality is impaired, providing a suboptimal but playable experience.

### Brief Description *

Upon loading a save,possibly when a force is deployed on a scenario,the TO&E would get reset as well as all units in any of them apart from the very first starting force from the campgain start,the units will still be deployed in the briefing room but as individual units not in a force,techs maintance and repairs are still in order.

### Steps to Reproduce

Opening the TO&E panel should show no force apart from a single one.

### Operating System *

Windows 11

### Java Version *

Java Version: 17.0.11

### MekHQ Suite Version *

Free Text (type manually)

### Custom MekHQ Version

v.0.50.01

### Attach Files

[mekhq.log](https://github.com/user-attachments/files/17791704/mekhq.log)
[save TO E force issue.zip](https://github.com/user-attachments/files/17791709/save.TO.E.force.issue.zip)

![image](https://github.com/user-attachments/assets/e9f5d2ba-dea8-4fa8-ab35-73f0dc04fe0d)

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by BiggestBoss1** [comment] 2024-11-18 20:49
There is another save from march 27th but it still has a empty TO&E,the issue is when making a lance and setting units in it,when i save and then quit mekhq and load that same save again it simply removes the lance and the units from the TO&E,this issue only seems to affect the TO&E while the other tabs are still the way i set them to in regards to personel assignment or tech repairs and maintance.

This save was made before the TO&E was wiped,it had 4 mechs and a vtol in it.

**Comment by IllianiCBT** [comment] 2024-11-19 00:16
Closing as resolved

**Closed by IllianiCBT** 2024-11-19 00:16 UTC
Labels: Bug, Needs More Info

**Comment by IllianiCBT** [comment] 2024-11-19 00:18
So the issue is being caused by how you're setting up your TO&E. Basically, what seems to be happening is you've overridden the default origin node (the one named after your campaign) to be treated as a Lance, but then added forces below that, as lances are the lowest level of formation they get logged as invalid formations. However, we were incorrectly parsing for 'invalid' instead of 'invalid formation'.

If you right-click on the origin node of your current campaign and select 'remove override' your TO&E will stop being wiped. This will not work retroactively.
