### ISSUE TITLE
BTH ignored during Mass Repair

### ISSUE THREAD

**Issue by servo01** [MegaMek/mekhq#548] opened 2017-11-25 22:45 UTC
43.4 mass repair/salvage - min BTH numbers ignored, regardless of settings. 

Techs keep destroying parts by attempting repairs that need BTH > 12.

**Comment by Nightstalker17** [comment] 2017-11-26 15:48
I happen to have the same issue with 0.43.4. Tested different kinds of settings (pod-mounted equipment etc) in several combinations, all with the same result.

**Comment by scJazz2** [comment] 2017-12-03 00:55
same problem in 0.43.5?

**Comment by Nightstalker17** [comment] 2017-12-03 07:33
Excuse the stupid question... but how do I get 0.43.5? I can only find a 0.43.4 release to download

**Comment by scJazz2** [comment] 2017-12-03 19:09
Not a stupid question actually... http://bg.battletech.com/forums/index.php?topic=59401.0

**Comment by Nightstalker17** [comment] 2017-12-04 19:17
Thanx for the hint. Tested it with 0.43.5, the problem is still occuring.

**Comment by neoancient** [comment] 2018-01-14 05:01
Fixed in 4dd94b7.

**Closed by neoancient** 2018-01-14 05:01 UTC
Labels: bug
