### ISSUE TITLE
Sorting the Buy Parts Menu freezes it.

### ISSUE THREAD

**Issue by Rod995** [MegaMek/mekhq#1205] opened 2019-05-21 21:51 UTC
### Environment
`MekHQ 0.45.4`

`Windows 10 (64-bit)`

`Java version 1.8.0_191`

### Description
So I went into the menu to buy items, right?
Decided that I wanted to see the most expensive thing, so I sorted it by cost, and it just becomes unresponsive.
No, "This Application has become Unresponsive", it just stops responding to input, or at least that window does. The main campaign menu still seems responsive.

#### Steps
`Open Campaign.`
`Go to 'Purchase Parts' menu.`
`Sort by cost by clicking on the tab for cost.`
`At this time it should become unresponsive.`

### Files
`Campaign File`
[230751002.zip](https://github.com/MegaMek/mekhq/files/3204678/230751002.zip)

`Custom Units`
[2.zip](https://github.com/MegaMek/mekhq/files/3204672/2.zip)

`MekHQ Log`
[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/3204669/mekhqlog.txt)

**Comment by sixlettervariables** [comment] 2019-05-24 16:17
The sorters in PartsTableDialog.java are the cause:
https://github.com/MegaMek/mekhq/blob/5ea5a4fc55ea48773fc2533145f21afdd41248bb/MekHQ/src/mekhq/gui/dialog/PartsStoreDialog.java#L753-L782

**Comment by sixlettervariables** [comment] 2019-05-24 16:18
Along with repeated calls to `Campaign::getTargetForAcquisition`.

**Comment by sixlettervariables** [comment] 2019-05-24 18:36
The other cause: if you exit with an expensive column sorted, it'll launch with that sort enabled. I have a partial fix (sorting is faster), but the initial load will be slow if the last sorted column is expensive.

**Comment by VicenteCartas** [comment] 2019-05-24 18:42
If the initial sorting is problematic, we could also disable remembering the preferences for this table in concrete.

**Comment by sixlettervariables** [comment] 2019-06-12 01:17
Ok, I the partial fix has landed. In *most* cases it should be must faster sorting.

**Comment by sixlettervariables** [comment] 2019-06-12 01:18
Closed by #1207

**Closed by sixlettervariables** 2019-06-12 01:18 UTC
Labels: bug, performance
