### ISSUE TITLE
Right-clicking on any person in Personnel tab causes NPE error

### ISSUE THREAD

**Issue by Sleet01** [MegaMek/mekhq#4425] opened 2024-07-17 02:46 UTC
### Environment
MekHQ v0.50.0-SNAPSHOT
    Build Date: 2024-07-16T18:13:40.393936615
    Today: 2024-07-16
    Origin Project: MekHQ
    Java Vendor: Eclipse Adoptium
    Java Version: 17.0.8.1
    Platform: Linux 6.2.16-060216-generic (amd64)
    System Locale: en_US
    Total memory available to MekHQ: 4 GB
    MM Code Revision: Unknown
    MML Code Revision: Unknown
    MHQ Code Revision: Unknown

### Description
This started occurring in the last couple days (~2024/07/14 or /15):
Right-clicking on personnel in the Personnel tab no longer brings up the context menu, instead causing the generic NPE dialog to appear.

Text of the NPEs, from the latest log:
```
19:42:01,814 ERROR [mekhq.MekHQ] {AWT-EventQueue-0}
mekhq.MekHQ.lambda$main$1(MekHQ.java:280) - Uncaught Exception Detected
java.util.MissingResourceException: Can't find resource for bundle java.util.PropertyResourceBundle, key durationWeeks.text
	at java.base/java.util.ResourceBundle.getObject(ResourceBundle.java:564)
	at java.base/java.util.ResourceBundle.getString(ResourceBundle.java:521)
	at mekhq.campaign.personnel.education.Academy.getTooltip(Academy.java:941)
	at mekhq.gui.adapter.PersonnelTableMouseAdapter.buildEducationSubMenus(PersonnelTableMouseAdapter.java:2992)
	at mekhq.gui.adapter.PersonnelTableMouseAdapter.buildEducationMenusSingleton(PersonnelTableMouseAdapter.java:2827)
	at mekhq.gui.adapter.PersonnelTableMouseAdapter.createPopupMenu(PersonnelTableMouseAdapter.java:1641)
	at mekhq.gui.adapter.JPopupMenuAdapter.maybeShowPopup(JPopupMenuAdapter.java:74)
	at mekhq.gui.adapter.JPopupMenuAdapter.mousePressed(JPopupMenuAdapter.java:62)
	at java.desktop/java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:288)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6623)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3389)
	at java.desktop/java.awt.Component.processEvent(Component.java:6391)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5001)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4572)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:775)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:747)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:744)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

### Files

[Ginei Ryoudan30751205.cpnx.gz](https://github.com/user-attachments/files/16258562/Ginei.Ryoudan30751205.cpnx.gz)

Should not require any custom units, but if necessary, it would be these: 
[Customs.zip](https://github.com/user-attachments/files/16258577/Customs.zip)

**Comment by IllianiCBT** [comment] 2024-07-17 02:49
Mea culpa. I’ll have it fixed in time for tomorrow’s nightly

**Comment by IllianiCBT** [comment] 2024-07-17 23:00
This was caused by a regression, pushing a fix momentarily.

**Closed** 2024-07-17 23:13 UTC
Labels: Bug, Personnel
