### ISSUE TITLE
Individual unit ID in name carrying back to MekHQ

### ISSUE THREAD

**Issue by SuperStucco** [MegaMek/mekhq#2080] opened 2020-09-30 20:31 UTC
When the "Show each unit's unique id next to its name" client setting is toggled on in MegaMek, when the game returns to MekHQ the unit names still include the unit ID e.g. "Trebuchet TBT-5N ID:21".

This doesn't appear to have any detrimental effect in tracking, unit use, or future MegaMek sessions.  Its just a display annoyance.

**Comment by Windchild292** [comment] 2020-09-30 20:33
This is working as intended.

**Comment by NickAragua** [comment] 2020-09-30 20:34
This is actually incredibly useful when resolving complicated scenarios with a lot of units on both sides - sometimes, megamek doesn't properly assign kills (e.g. mobility/crew kills). That way, instead of trying to figure out which Saladin (Standard) got killed by which Phoenix Hawk PXH-1, you can just look up the ID numbers.

**Comment by SuperStucco** [comment] 2020-10-01 00:55
For assigning kills during the resolution process, possibly (I have some related thoughts about  that, but its a separate issue).  This is about after that - its showing up in the MekHQ TO&E, Repair bay, Hanger, and so on.  Definitely _not_ useful there.

**Comment by Windchild292** [comment] 2021-04-20 15:14
After dev discussion, this option is working as intended.

**Closed by Windchild292** 2021-04-20 15:14 UTC
