### ISSUE TITLE
[LOGISTICS] MissingFormatArgumentException when starting a new month. No convoy created.

### ISSUE THREAD

**Issue by JonhyBurner** [MegaMek/mekhq#5327] opened 2024-12-09 14:32 UTC
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Critical (Game-breaking/Crash): The game crashes or a core feature (like saving, loading, or network connection) is completely unusable.

### Brief Description *

When advancing the day at the end of the month, the game throws an error. No convoy is created.

The dailylog breaks, keeping the previous day and appending the next, and looks like this:
![image](https://github.com/user-attachments/assets/98af1a0d-babd-42c7-a131-c6fd0d367350)

The game keeps going as normal the next day, but the error appears every month.

### Operating System *

Windows 10

### Java Version *

Java Version: 17.0.13

### MekHQ Suite Version *

Free Text (type manually)

### Custom MekHQ Version

MekHQ Logistics Overhaul artifact from 2024-12-06

### Attach Files

[logs.zip](https://github.com/user-attachments/files/18062848/logs.zip)
[5th Circle Furies - month end.cpnx.gz](https://github.com/user-attachments/files/18062849/5th.Circle.Furies.-.month.end.cpnx.gz)

![image](https://github.com/user-attachments/assets/b5ddd45b-78d8-4cd4-9982-c325ee3c96af)

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by JonhyBurner** [comment] 2024-12-09 14:34
Error in the log (this is after the procurement is done):

`14:16:04,417 ERROR [mekhq.MekHQ] {AWT-EventQueue-0}
mekhq.MekHQ.lambda$main$1(MekHQ.java:293) - Uncaught java.util.MissingFormatArgumentException detected. Please open up an issue containing all logs, the game save file, and customs at https://github.com/MegaMek/megamek/issues . If Sentry is enabled, the error has also been logged.
java.util.MissingFormatArgumentException: Format specifier '%s'
	at java.base/java.util.Formatter.format(Unknown Source)
	at java.base/java.util.Formatter.format(Unknown Source)
	at java.base/java.lang.String.format(Unknown Source)
	at mekhq.campaign.mission.resupplyAndCaches.Resupply.createPlayerConvoyOptionalDialog(Resupply.java:2110)
	at mekhq.campaign.mission.resupplyAndCaches.Resupply.getResupply(Resupply.java:1711)
	at mekhq.campaign.mission.resupplyAndCaches.Resupply.getResupply(Resupply.java:1672)
	at mekhq.campaign.Campaign.processResupply(Campaign.java:4088)
	at mekhq.campaign.Campaign.processNewDayATB(Campaign.java:3970)
	at mekhq.campaign.Campaign.newDay(Campaign.java:4558)
	at mekhq.campaign.CampaignController.advanceDay(CampaignController.java:82)
	at mekhq.gui.CampaignGUI.lambda$initTopButtons$63(CampaignGUI.java:1115)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
	at java.desktop/java.awt.Component.processMouseEvent(Unknown Source)
	at java.desktop/javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.desktop/java.awt.Component.processEvent(Unknown Source)
	at java.desktop/java.awt.Container.processEvent(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)

`

**Comment by ussdefiant60** [comment] 2024-12-09 15:50
I can confirm getting an identical error message at end of month in my own game. Seems to be related to being on a contract with Independent command rights.

**Comment by OrbMonky** [comment] 2024-12-09 18:57
I'm having this occur sans error message, convoys are forming and months are ending/starting properly, but no supply ever arrives

**Comment by IllianiCBT** [comment] 2024-12-09 19:02
Unfortunately I’m out of the office till Thursday. So expect a new artifact addressing this Thursday AM Nashville time

**Comment by IllianiCBT** [comment] 2024-12-11 16:51
Closing as resolved

**Closed by IllianiCBT** 2024-12-11 16:51 UTC
