### ISSUE TITLE
Please default Ally Status to Unchecked

### ISSUE THREAD

**Issue by scJazz2** [MegaMek/mekhq#173] opened 2016-09-28 16:53 UTC
In Scenario Resolution > Ally Status window... make the boxes unchecked by default. Rather than the current checked. Saves some mouse clicks which are usually unnecessary.

**Comment by neoancient** [comment] 2016-09-28 17:02
The intended behavior is that the checks are set according to the actual status of the units in the game. This has been broken for some time, but has been fixed for the next release. In addition, the ally status is now set correctly when resolving manually, which I don't believe has ever worked.

See #33.

**Closed by neoancient** 2016-09-28 17:02 UTC
