### ISSUE TITLE
Star League Caches Generate Irregardless of Year

### ISSUE THREAD

**Issue by Kailan7401** [MegaMek/mekhq#2521] opened 2021-04-16 14:09 UTC
### Environment
StratCon alpha test build (MekHQ CI with Gradle #1168: Pull request #2144)
Windows 10
OpenJDK 11.0.10

### Description
![image](https://user-images.githubusercontent.com/32316785/115036029-18d37c80-9f08-11eb-8cf9-6b6f9479b591.png)
Special missions, Big Battles, etc appear to generate as per usual, but are not assigned a location on the AtB campaign state map. This may be intended behavior but I figured I'd point it out just in case

Small corollary: Unrelated to StratCon, but Star League Cache missions generate regardless of year, so you will sometimes see these missions regardless of if the Star League has been formed yet or not.

### Files
[Campaign Info.zip](https://github.com/MegaMek/mekhq/files/6325629/Campaign.Info.zip)
[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/6325630/mekhqlog.txt)

**Comment by NickAragua** [comment] 2021-04-16 14:18
The former is intended behavior. The latter has been the case since AtB was first implemented. Leaving this open so the latter won't get forgotten.

**Comment by Windchild292** [comment] 2021-08-21 17:24
I've got a fix for this ready, but it relies on a PR that won't be merged until after 0.49.3 https://github.com/Windchild292/mekhq/pull/116

**Closed** 2021-08-25 01:46 UTC
Labels: Bug, AtB
