### ISSUE TITLE
Campaign Breach potential bug 45.4

### ISSUE THREAD

**Issue by DwarbitBK** [MegaMek/mekhq#1165] opened 2019-03-28 16:04 UTC
### Environment
I am using MekHQ Version 45.4 on a Windows 10 laptop with Java 1.8.0_201.

### Description
I have a contract that starts on the 17th. I have on the 16th set up the minimum 3, including 1 scout Lance ready to go. When moving to the 17th, I receive 3 contract breaches automatically. The Phoenix Hawk 3M sometimes gets damaged, I initially thought it was that, but excluded it from one test and it still happened. Attached are the Images from the 16th and 17th on one test where the PXH-3M was not damaged. Also attached are the CPNX file, Factions+Hints.xml, and a zip of the custom units being used in the Campaign so far.

### Files
![10 16 3053 DeployedUnits](https://user-images.githubusercontent.com/34976715/55172881-ff501400-5137-11e9-8b46-08c1bfe903a8.JPG)
![10 17 3053 DeployedUnitsWithContractBreach](https://user-images.githubusercontent.com/34976715/55172888-037c3180-5138-11e9-975d-29d068748972.JPG)

[Dwarbithian Commandos30531016.zip](https://github.com/MegaMek/mekhq/files/3018968/Dwarbithian.Commandos30531016.zip)
[Dwarbithian Technologies.zip](https://github.com/MegaMek/mekhq/files/3018973/Dwarbithian.Technologies.zip)
[2000_KellerSchultz_planets.zip](https://github.com/MegaMek/mekhq/files/3018974/2000_KellerSchultz_planets.zip)
[factionhints.zip](https://github.com/MegaMek/mekhq/files/3018977/factionhints.zip)
[factions.zip](https://github.com/MegaMek/mekhq/files/3018978/factions.zip)

**Comment by VicenteCartas** [comment] 2019-04-01 02:02
Can't load your campaign, it's complaining that Spider SDR-5Vb is missing.

**Comment by VicenteCartas** [comment] 2019-04-01 03:38
I think the issue is that your force is deployed for the old C2-Diversion Raid on the 16th. Then the 17th arrives, and the contract checks for breaches before redeploying your units to the right contract, so when the contract is checking, your units are not yet assigned to it and there are the breaches.

I'll investigate how to change the order of operations so we first assign units to the contract and then check for breaches.

**Closed** 2019-04-04 02:30 UTC
