### ISSUE TITLE
Stop them from going where?

### ISSUE THREAD

**Issue by kipstafoo** [MegaMek/mekhq#1965] opened 2020-08-24 19:15 UTC
0.49.9

I'm doing a breakthrough (defender) mission. The enemy seems to have no clue where they are going...

Prevent at least 50% of the following enemy force(s) from reaching the NONE edge:
	Ghost Bear Dominion

![image](https://user-images.githubusercontent.com/506522/91086128-771bba00-e61c-11ea-8b5c-0b6fbe663c7b.png)

**Comment by gsparks3** [comment] 2020-08-25 00:43
Pretty sure this is related to #1880 - I've seen the "NONE" edge descriptor in addition to incorrect edge descriptors.

**Comment by Windchild292** [comment] 2020-08-25 00:55
Duplicate of #1880.

**Closed by Windchild292** 2020-08-25 00:55 UTC
