### ISSUE TITLE
[0.49.9] Personnel Market paid recruitment rolls option does nothing

### ISSUE THREAD

**Issue by kipstafoo** [MegaMek/mekhq#1940] opened 2020-08-19 13:49 UTC
Selecting the 'paid recruitment roll' in the personnel market doesn't do anything. The type of personnel didn't show up for 2 months and I had no 100k finance deduction for at all (expected to have 8 of them over 2 months).

**Comment by Windchild292** [comment] 2020-08-19 16:12
Do you have an active contract and are you playing AtB?

**Comment by Windchild292** [comment] 2020-08-19 17:45
Also, I cannot reproduce this on my test campaign and will require a campaign file to do so.

**Comment by Kendricke** [comment] 2020-08-24 22:40
Curious if this is related to https://github.com/MegaMek/mekhq/issues/1952 

I have a campaign file in that one if it helps (it's a similar issue where I stopped getting ANY personnel market updates during a contract).  I just confirmed that with that campaign, if I manually completed the Mission and began attempting paid recruitment rolls, I would get nothing. 

I would get "hangs" around Mondays each week, but no actual personnel market changes.

**Comment by Windchild292** [comment] 2020-08-24 22:50
Quite possibly the same cause.

The hang could also be #1922, which is fixed in the next release.

**Comment by Windchild292** [comment] 2020-09-07 03:00
Closing as almost certainly #1952 and thus fixed in #1992

**Closed by Windchild292** 2020-09-07 03:00 UTC
Labels: Can't reproduce, Needs More Info
