### ISSUE TITLE
 Implemented Resupply Module #4518  - Units returning from some combats are being set to factory conditions despite that being inappropriate for the mission

### ISSUE THREAD

**Issue by OrbMonky** [MegaMek/mekhq#5326] opened 2024-12-09 07:49 UTC
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Medium (Gameplay Limitation): Non-core functionality is impaired, providing a suboptimal but playable experience.

### Brief Description *

On some contracts, units are returning to base and being automatically upgraded to factory facilities, very generous, but also pretty game breaking. In this instance it is happening on a Cadre Duty in the periphery against the Oberon Confederation, but it also happened on a prior independents vs rebels 'suppress rebellion' mission (can't recall the exact title).

![image](https://github.com/user-attachments/assets/71f6c476-e183-4461-a778-53521b0d4dec)

[logs.zip](https://github.com/user-attachments/files/18058010/logs.zip)
Campaign File is in the logs zip

### Steps to Reproduce

1. Be on a mission (cadre/rebellion suppression so far)
2. Complete a scenario by usual practice of assigning forces, playing scenario, returning to base and completing the scenario normally.
3. Returning units receive factory level facilities despite having been basic facilities at start of contract/before leaving.

### Operating System *

Windows 10

### Java Version *

17

### MekHQ Suite Version *

None

### Custom MekHQ Version

 Implemented Resupply Module #4518 

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by OrbMonky** [comment] 2024-12-09 18:05
Definitely seems tied to mission parameters, here is the return status of the next mission; 
![image](https://github.com/user-attachments/assets/00993838-383b-4fe9-b673-da7f1b97d8ff)
On Von Strang's World

**Comment by IllianiCBT** [comment] 2024-12-09 18:09
Fixing this would be a great opportunity to implement Mobile Bases and the ability to specify specific units in a force as non-combat.

Leave this to me, I have some ideas.

**Comment by IllianiCBT** [comment] 2024-12-18 02:52
This is working as intended: Cadre Duty is considered a Garrison Type contract, which defaults to Maintenance Facility. A Good enough Reputation/Unit Rating improves that by 1.

I do have plans to improve this system but early attempts were a washout, so it won't see the light of day until 50.03's dev cycle.

Closing

**Closed by IllianiCBT** 2024-12-18 02:52 UTC
