### ISSUE TITLE
Implemented Resupply Module #4518 - Random unit quality appears non-functional

### ISSUE THREAD

**Issue by OrbMonky** [MegaMek/mekhq#5331] opened 2024-12-09 23:25 UTC
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Medium (Gameplay Limitation): Non-core functionality is impaired, providing a suboptimal but playable experience.

### Brief Description *

Newly salvaged and purchased units are arriving with straight C rating across the board (I have the A-F ratings inverted, so this should be D under default settings).

![image](https://github.com/user-attachments/assets/4e0a1364-0e3e-475b-a7e7-71832e7c3a4d)
![image](https://github.com/user-attachments/assets/7e8ea6db-27b0-4e72-9a74-72fa30a787d9)
![image](https://github.com/user-attachments/assets/3c002ddb-8073-4d0b-9933-4dd218f331d5)

[logs.zip](https://github.com/user-attachments/files/18069275/logs.zip)
Logs and Campaign file included, no customs

### Steps to Reproduce

1. Enable randomized new unit quality in campaign options
2. Salvage (and probably purchase or acquire from bonus rolls) a unit to be added to your roster
3. Observe part quality report

### Operating System *

Windows 10

### Java Version *

17

### MekHQ Suite Version *

None

### Custom MekHQ Version

Implemented Resupply Module #4518

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by JonhyBurner** [comment] 2024-12-09 23:40
(I'm using the latest resupply artifact and I use the default letter order for quality)

Purchased Awesome from Unit Market:
![image](https://github.com/user-attachments/assets/17708de2-8cff-422c-bcfd-ccb69badc67d)

Purchased Paramour from "Purchase Unit" menu:
![image](https://github.com/user-attachments/assets/412f0008-16be-450d-864b-594da44c4491)

Only salvaged one mech, a Lumberjack, that is indeed D quality.

So it appears to be working on my end.

**Comment by OrbMonky** [comment] 2024-12-10 12:28
Hmm, all mine were listed C except one which had C parts but somehow had a D rating (again with reversed rating order). Turning it off and on again to see if that impacts anything.

**Comment by IllianiCBT** [comment] 2024-12-12 17:06
I loaded your save, purchased a Vedette from the Unit Market and it arrived at 'E' quality. I think some confirmation bias might be at play here.

Closing as it does appear to be working as intended.

**Closed by IllianiCBT** 2024-12-12 17:06 UTC
