### ISSUE TITLE
[50.01 NIGHTLY 1647] Ship Search doesn't respect 

### ISSUE THREAD

**Issue by ussdefiant60** [MegaMek/mekhq#5096] opened 2024-10-21 03:39 UTC
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Medium (Gameplay Limitation): Non-core functionality is impaired, providing a suboptimal but playable experience.

### Brief Description *

I have a unit rating of 7 (+2), but when i open the Ship Search screen i see a modifier of 0. I suspect that one number or the other is wrong somehow.

### Operating System *

Windows 11

### Java Version *

Java 17 Adoptium

### MekHQ Suite Version *

Free Text (type manually)

### Custom MekHQ Version

50.01 NIGHTLY 1647

### Attach Files

![image](https://github.com/user-attachments/assets/e56d150f-f90a-4370-a21d-3cbe4386a376)

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by IllianiCBT** [comment] 2024-10-21 03:46
Before I can properly investigate I need a copy of your save showing this issue

**Comment by IllianiCBT** [comment] 2024-10-21 03:49
Wait, I realized what the issue is: there is a base modifier of 2, so your AtB Modifier of 2 reduces that to zero. So, it's working as intended, it's just a very old system that is in desperate need of some love.

Closing as working as intended.

**Closed by IllianiCBT** 2024-10-21 03:49 UTC
