### ISSUE TITLE
SPAs not showing for personnel

### ISSUE THREAD

**Issue by pjfarland** [MegaMek/mekhq#411] opened 2017-07-18 10:56 UTC
On each person's 'file' SPAs aren't showing up.  They are still there if you GM edit the person, they just aren't showing.  This happens whether you hire your first pilot or have many added.

**Comment by Dylan-M** [comment] 2017-07-18 11:00
Duplicate of #395. Closing.

**Closed by Dylan-M** 2017-07-18 11:00 UTC
