### ISSUE TITLE
Princess vs Princess

### ISSUE THREAD

**Issue by Dzlan** [MegaMek/mekhq#2943] opened 2021-11-07 04:03 UTC
When princess vs princess is all that is left, the game can often end up in an infinite loop. There should be a need for the player to manually state when to progress onto the next round, giving him time to review the situation and end the battle when they feel it is right to do so.

**Comment by Windchild292** [comment] 2021-11-07 12:04
Wrong tracker (this is a MegaMek issue), and a duplicate of an open MM issue. Closing

**Closed by Windchild292** 2021-11-07 12:04 UTC
