### ISSUE TITLE
Campaign Option>Tech Limits>Use ammo by type (unofficial) does not seem to work

### ISSUE THREAD

**Issue by plutonick** [MegaMek/mekhq#1665] opened 2020-04-12 15:42 UTC
Campaign Options > Tech Limits > Use ammo by type (unofficial), ie being able to load an LRM 5 with LRM20 ammo, is not working.

### Environment
47.5 has  been tested and it's not working. It's not working on 46.0 either 

### Description
![image](https://user-images.githubusercontent.com/8420602/79073110-5c8c1880-7ced-11ea-891d-461df3446e39.png)
![image](https://user-images.githubusercontent.com/8420602/79073115-61e96300-7ced-11ea-9436-f1232598f050.png)
![image](https://user-images.githubusercontent.com/8420602/79073117-66158080-7ced-11ea-84e5-a120d61943cd.png)

**Comment by Windchild292** [comment] 2020-04-12 15:45
Test campaign from #1558.
[Test30670103.cpnx.zip](https://github.com/MegaMek/mekhq/files/4466594/Test30670103.cpnx.zip)

This is the same as #1558, and I'm closing #1558 as this one has more information.

**Comment by ChaoticInsanity** [comment] 2020-05-06 02:36
I am not sure the best way to fix this but it appears that the problem is AmmoType::equals only considers ammo equal if the type and rack size match. The methods leading to the check are correctly using the 'Use ammo by type' campaign option but the different rack sizes are never considered equal so the ammo from a different rack is not acceptable. 

This failure happens when AmmoBin::getAmountAvailable calls Campaign::findSparePart where the predicate uses getMunitionType() == getMunitionType().

Maybe a new special comparison method could be created and used in the predicate to compare the ammo type without the rack size.

**Comment by ChaoticInsanity** [comment] 2020-05-06 19:10
Updated test campaign the covers missile racks and autocannons.
[Test_ACammo.cpnx.zip](https://github.com/MegaMek/mekhq/files/4588977/Test_ACammo.cpnx.zip)

**Closed** 2020-05-07 18:04 UTC
Labels: bug
