### ISSUE TITLE
Mek Lab inside MekHQ doesn't auto update unit statistics section

### ISSUE THREAD

**Issue by RamiusFox** [MegaMek/mekhq#401] opened 2017-06-07 21:02 UTC
I am using the 0.43.2-git version.  When I customize a mek in mek lab tab, I noticed the unit statistics section doesn't auto update.  I have to change tabs for it to update that section.  (see screen shot attached I just lowered the speak of a cicada from 8/12 to 7/11 but all the data in unit statistics section hasn't changed.  If I were to click equipment tab it would change.  Any equipment I add wont reflect in unit statistics until I change tabs again.   I was using version 0.3.31 before I updated to newest client and this section did auto update.  I am not sure if this is a bug or I just need to click a setting someplace. 

![image](https://user-images.githubusercontent.com/29262272/26900960-a7ca7144-4b99-11e7-8a9f-1040aa1dd17f.png)

Here is a copy of my test campaign.  No custom mechs.
[test Campaign30281224.zip](https://github.com/MegaMek/mekhq/files/1059306/test.Campaign30281224.zip)

**Comment by BLOODWOLF333** [comment] 2017-06-07 21:12
Your HQ log file would probably help a lot more.  With any HQ bug report.

**Comment by RamiusFox** [comment] 2017-06-07 21:23
Here it is.  Let me know if you need anything else. 

[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/1059354/mekhqlog.txt)

**Comment by neoancient** [comment] 2018-01-09 15:35
Duplicate of #450

**Closed by neoancient** 2018-01-09 15:35 UTC
Labels: bug, duplicate
