### ISSUE TITLE
49.20 Nightly - Monthly Vehicle Market is empty and will not generate vehicles.

### ISSUE THREAD

**Issue by Thom293** [MegaMek/mekhq#4203] opened 2024-06-10 15:49 UTC
Title.  Here is save and customs.  Load save, advance day through multiple months, vehicle market will never populate (Mechs, ASF and Conv Fighters work fine).

We believe maybe related to some recent role changes?  But not certain.

[mekhq.log](https://github.com/user-attachments/files/15775829/mekhq.log)
[Titanium Tide30700302.cpnx.gz](https://github.com/user-attachments/files/15775837/Titanium.Tide30700302.cpnx.gz)
[CustomsThom6.10.24.zip](https://github.com/user-attachments/files/15775855/CustomsThom6.10.24.zip)

**Comment by IllianiCBT** [comment] 2024-06-10 17:21
I'll be pushing a fix for this within the hour. It was caused by an unintended interaction between the AtB Unit Market and our new updated unit role definitions. The short version is that the market was filtering out anything that didn't have the `ARTILLERY_MIXED` unit role.

**Closed** 2024-06-15 00:35 UTC
Labels: Bug, AtB
