### ISSUE TITLE
[0.50.0-SNAPSHOT] Maxim (I) & potentially other large transports generate with vast amount of infantry beyond loading capacity

### ISSUE THREAD

**Issue by Tzahr** [MegaMek/mekhq#4535] opened 2024-08-01 04:39 UTC
### Environment
04:19:47,749 INFO  [mekhq.MekHQ] {main}
mekhq.MekHQ.initializeLogging(MekHQ.java:303) - Starting MekHQ v0.50.0-SNAPSHOT
    Build Date: 2024-07-27T01:16:03.359732465
    Today: 2024-08-01
    Origin Project: MekHQ
    Java Vendor: Eclipse Adoptium
    Java Version: 21.0.3
    Platform: Windows 11 10.0 (amd64)
    System Locale: en_GB
    Total memory available to MekHQ: 4 GB
    MM Code Revision: e86f08fde087d229498e46e9697a41466897653e
    MML Code Revision: bea7884b61319d3b2c803a0fa65988008638e6ef
    MHQ Code Revision: 12c84d7d4a3a993ac643cdf58ba9b621a907170c

> **EDIT:** This issue initially described multiple, different bugs. I have left everything originally reported intact, but the main error under investigation here currently is the second one described, referring to the generation of large amounts of infantry and BA. I will open new issues for the others as they occur in the new release. Everything that follows is unaltered. 

### Description
Attached is a campaign including a contract scenario that has two (2) tank bases and one (1) artillery base. Regenerating bot forces on that scenario will commonly cause: 

- Very consistent: certain forces associated with special modifiers (like artillery and tank bases) generate twice. This pretty consistently leaves this scenario to generate 2x artillery OPFOR and 3x Tank Reinforcement OPFOR on top of Primary OPFOR. 
![image](https://github.com/user-attachments/assets/51ba22d7-a2ab-4501-913e-49291607adde)

- Uncommon: causes Tank Reinforcement OPFOR to generate very large numbers of infantry and Battle Armour. This also occurs randomly on normal generation (e.g. in the wild), the most extreme case generated 400+ units of infantry and BA. 
![image](https://github.com/user-attachments/assets/948328c7-f3c4-4bdb-8ccf-980af0e4080d)

- Rarely: generates forces without any units, leaving only Primary OPFOR populated. 
![image](https://github.com/user-attachments/assets/2dc22e74-2df2-4b2e-9943-1be76ef115de)

This has occurred repeatedly. I started encountering the anomalous infantry / BA generation in the wild, causing me to frequently regenerate bot forces, which lead me to observe the first and third anomalies. 

### Files
[mekhq.log](https://github.com/user-attachments/files/16450324/mekhq.log)
[TestScenarioSave.zip](https://github.com/user-attachments/files/16450326/TestScenarioSave.zip)
[custom mechfiles.zip](https://github.com/user-attachments/files/16414872/custom.mechfiles.zip)

**Comment by Tzahr** [comment] 2024-08-01 04:48
This is a naturally generating Primary OPFOR for me on a scouting encounter: 

The vast majority of these units are infantry or BA. 
![image](https://github.com/user-attachments/assets/cd604794-c567-46ca-a1fe-e66e7d2b0f80)

**Comment by IllianiCBT** [comment] 2024-08-01 04:53
How frequent is this issue? Trying to get a sense of scope.

**Comment by Tzahr** [comment] 2024-08-01 04:58
The naturally occuring infantry horde happens quite frequently. A very rough guess would be 15-20% frequency on ground contracts. I literally observed it happening moments ago in the wild doing scouting on the same save.

**Comment by IllianiCBT** [comment] 2024-08-01 04:59
Just with Wobbies, or any faction?

**Comment by Tzahr** [comment] 2024-08-01 05:04
I have encountered it most frequently with the Wobbles, but also with other factions. I dug into the campaign records and found this one too: 

![image](https://github.com/user-attachments/assets/76d19a31-3fb8-4f9a-b9ee-f0afd456c2a2)

**Comment by Sleet01** [comment] 2024-08-01 05:27
May be an instance of https://github.com/MegaMek/mekhq/issues/2792, which was never resolved.

**Comment by Tzahr** [comment] 2024-08-01 23:11
I decided to load into the lobby with one of the lesser offenders of the infantry horde issue, and noted this:

![image](https://github.com/user-attachments/assets/783e2d51-98d4-46c7-9865-163e603e3b2a)

I wonder if it is relevant; #2792 refers to excessive Mech forces, while I am only experiencing this specifically with infantry and BA. A theory might be that it is attempting to generate a full load for the transports, but failing to satisfy this for whatever reason, causing it to potentially continuously generate additional forces to transport.

**Comment by Tzahr** [comment] 2024-08-03 01:02
Encountered the bug again, this time mission generated x2 Maxim (I).
Upon loading into the lobby, the game froze for about a minute while loading OPFOR, and then displayed errors for being unable to load a ream of BA and infantry into both Maxims seperately.

At this stage, I am 99% convinced this is a bug with the Maxim (I) specifically. 

![image](https://github.com/user-attachments/assets/81e56ba9-920c-44f5-bb34-5a140e8c0cd0)

**Comment by repligator** [comment] 2024-08-03 17:43
After smashing out some breakpoints, it looks like the issue is with `mekhq/campaign/mission/AtBDynamicScenarioFactory.java` , specifically the portion beginning with line 736. 
`// Units with infantry bays get conventional infantry or battle armor added`
After passing through this, the Primary OpFor (18 tanks and/or APC's, including several Maxim I's) became 18 APC's and/or tanks and 369 units of infantry or BA. On the same scenario, Enemy Tank Reinforcements (6 tanks and/or APC's, once again including a Maxim I), received 854 additional units of infantry and BA.

[mekhq.log](https://github.com/user-attachments/files/16482371/mekhq.log)
[so_many_blakists_1st Rimward Hussars30690117.cpnx.gz](https://github.com/user-attachments/files/16482374/so_many_blakists_1st.Rimward.Hussars30690117.cpnx.gz)

**Comment by Sleet01** [comment] 2024-08-03 21:50
> After smashing out some breakpoints, it looks like the issue is with `mekhq/campaign/mission/AtBDynamicScenarioFactory.java` , specifically the portion beginning with line 736. `// Units with infantry bays get conventional infantry or battle armor added` After passing through this, the Primary OpFor (18 tanks and/or APC's, including several Maxim I's) became 18 APC's and/or tanks and 369 units of infantry or BA. On the same scenario, Enemy Tank Reinforcements (6 tanks and/or APC's, once again including a Maxim I), received 854 additional units of infantry and BA.
> 
> [mekhq.log](https://github.com/user-attachments/files/16482371/mekhq.log) [so_many_blakists_1st Rimward Hussars30690117.cpnx.gz](https://github.com/user-attachments/files/16482374/so_many_blakists_1st.Rimward.Hussars30690117.cpnx.gz)

Whoa, good job tracking that down!

**Comment by SuperStucco** [comment] 2024-08-09 18:08
The Maxim (I) is one of the few 'large' APC type units, capable of carrying multiple platoons of most types of infantry.  When transports are assigned infantry in MekHQ it runs on a loop to generate infantry until there isn't any room; there may be some problems with actually associating those extra infantry with the carriers, so it will loop over and over generating infantry without an exit.

With the build scripts in flux and pending updated documentation, and the OIF stuff, I'm in a bit of a holding pattern as I don't want to be fighting a bunch of structural stuff that I don't understand on top of working out the code problems.  Hopefully things will be smoothed out once 50.0 goes online, if not before.  If it hasn't been looked at by then, I'll see what I can do.

**Comment by repligator** [comment] 2024-08-10 19:12
Another instance from

**Comment by Sleet01** [comment] 2024-08-10 21:25
#4601 is definitely the same issue.  Closing that as a dupe.

**Comment by Tzahr** [comment] 2024-09-04 15:20
As this report actually reports two issues: 
- The Maxim (I) transport capacity bug
- Duplication of forces on contract regeneration

I'm going to refocus this one about just the transport error, and open a new issue for the force duplication on regeneration bug.

**Closed** 2024-09-13 20:25 UTC
Labels: Bug, AtB, Needs Investigation, StratCon
