### ISSUE TITLE
MegaMekLab inside MekHQ will not print record sheets. 

### ISSUE THREAD

**Issue by WBailey79** [MegaMek/mekhq#408] opened 2017-07-07 18:13 UTC
MegaMekLab application inside both MekHQ v0.43.2 and v0.42.2 will not print record sheets for any units physically or to PDF.  I do not have this problem when using a copy of MegaMekLab outside of MekHQ.
I have attached my log file. 
[megameklablog.txt](https://github.com/MegaMek/mekhq/files/1131980/megameklablog.txt)

**Comment by Dylan-M** [comment] 2017-07-07 18:21
Please provide a _full and detailed_ bug report per our guidelines.

https://github.com/MegaMek/megamek/wiki/Making-a-Bug-Report

**Comment by WBailey79** [comment] 2017-07-07 18:38
I have updated my report, and attached what I believe is the necessary log file. 
If anything else is needed, please let me know.

**Comment by Dylan-M** [comment] 2017-07-07 18:38
If it's from inside MekHQ we need the MekHQ log as well. Thanks.

**Comment by HammerGS** [comment] 2017-07-07 18:39
This is a known issue and is the result of a packing error in the last release of MekHQ. Its been fixed here (https://github.com/MegaMek/mekhq/commit/4f2029c86fececb64404bf126a8483ff224aa5be) for the next release.

**Comment by Dylan-M** [comment] 2017-07-07 18:39
Thanks Hammer, closing as duplicate then.

**Closed by Dylan-M** 2017-07-07 18:39 UTC

**Comment by WBailey79** [comment] 2017-07-07 18:41
Thanks, Hammer and Dylan-M for the quick response and clarifying. I look forward to your next release!

**Comment by neoancient** [comment] 2017-07-08 03:33
The problem is that the packaging script placed the folder with the record sheet image files in the wrong location. You can actually fix this pretty easily without having to wait. Move the  `data/images/misc/recordsheets` folder up one level into `data/images` and you should be able to print.
