### ISSUE TITLE
Cannot refit kit non-omni mechs

### ISSUE THREAD

**Issue by nickasummers** [MegaMek/mekhq#379] opened 2017-04-10 01:22 UTC
I am playing an AtB Campaign using the new 43.1 build. When I attempt to refit (Customize>Choose Refit Kit...) a mech nothing happens. When I tried over and over with all of my mechs (all inner sphere) I managed to get one of them to pop up a refit screen just once out of many attempts and it had no variants listed. As a test, I gave myself a Timber Wolf A and attempted to refit it (Customize>Choose Configuration...) and that worked fine. It showed every variant, including versions that require more than a simple re-pod. I then went ahead and copied the save file to my old 43.0 folder (and ran the 43.0 exe to load it) and refit kits worked just fine there for the IS mechs with the same save file.

Mekhq log and save file attached.
[BugReport.zip](https://github.com/MegaMek/mekhq/files/908732/BugReport.zip)

**Comment by HammerGS** [comment] 2017-04-10 01:36
Duplicate of https://github.com/MegaMek/mekhq/issues/359.

This has been fixed and will be in the next release.

**Closed by HammerGS** 2017-04-10 01:36 UTC
Labels: duplicate
