### ISSUE TITLE
Dropship Customization Time Not Advancing

### ISSUE THREAD

**Issue by mkerensky** [MegaMek/mekhq#142] opened 2016-08-22 19:26 UTC
I could swear that this appeared in another recent bug report by someone other than me, but I haven't been able to find it. I ordered a fairly involved (92220m) customization of a dropship, and the time is not decreasing as the day advances.  I have done lesser customizations of dropships in the same campaign and had them work correctly. My log shows no errors. The source dropship was affected by a previous C3i/Naval C3 issue and went through several cancelled customizations to the same variant until that bug was resolved, allowing me to save the campaign file. 

The attached zip contains both my campaign file and the custom units folder for it. Customs.zip contains the dropship variant I'm trying to create, is it was built without MMLab. 

[Customs.zip](https://github.com/MegaMek/mekhq/files/430970/Customs.zip)

[DropShipCustomization.zip](https://github.com/MegaMek/mekhq/files/430966/DropShipCustomization.zip)

**Comment by mkerensky** [comment] 2016-08-30 15:12
I did some further testing on this, and I think the specific dropship I'm trying to customize is bugged. I can use the same refit kit on another Nekohono'O and it works, and I can also customize a different dropship to a refit kit of the same maintenance class and rough timeframe, and it works. I might also have the problem dropship set to an invalid maintenance location - it's in a field workshop trying to do a class D maintenance facility refit. If that's what is causing the problem, I'd like to request some sort of notification in the daily log.

**Comment by neoancient** [comment] 2016-10-11 15:40
Duplicate of #77. The problem was that the refit is being assigned to the commander instead of the engineer, which is a virtual crewmember that combines the skill of all the technicians in the crew. The refit only proceeds in cases when the commander has technical skill.

**Closed by neoancient** 2016-10-11 15:40 UTC
Labels: bug
