### ISSUE TITLE
[49.7] Verbose planetary aquisition creates massive daily log that breaks game save

### ISSUE THREAD

**Issue by JonhyBurner** [MegaMek/mekhq#3153] opened 2022-03-03 02:24 UTC
MegaMek v0.49.7
Release Date: 2022-02-18
Today: 2022-03-03
Origin Project: MekHQ
Java Vendor: Eclipse Adoptium
Java Version: 11.0.14
Platform: Windows 10 10.0 (amd64)
System Locale: en_GB
Total memory available to MegaMek: 2 GB

In the provided campaign, when advancing the day, the daily log is populated with an enormous amount of failed purchases. I think it's related to my highest skilled logistical admin using his daily searches and rendering the subsequent tries impossible due to parts availability.

This is how it looks:
![Screenshot 2022-03-03 021135](https://user-images.githubusercontent.com/67933202/156483668-18665f39-c5c8-4061-94b7-6d4cdcd003a5.png)

If the game is saved in that state, it fails to load. If the day is advanced again, the daily log is reset, and everything works properly again. If the verbose planetary aquisition option is disabled, it works fine as well.

Files:
[Lisbon's Ravagers NoContract 4.cpnx.gz](https://github.com/MegaMek/mekhq/files/8174387/Lisbon.s.Ravagers.NoContract.4.cpnx.gz)

Logs(with nothing related):
[legacy.log](https://github.com/MegaMek/mekhq/files/8174391/legacy.log)
[megamek.log](https://github.com/MegaMek/mekhq/files/8174392/megamek.log)
[megameklab.log](https://github.com/MegaMek/mekhq/files/8174393/megameklab.log)
[mekhq.log](https://github.com/MegaMek/mekhq/files/8174394/mekhq.log)

**Comment by Windchild292** [comment] 2022-03-04 01:57
Can you please post on of the campaign saves that fails to load @JonhyBurner so that I can test with the broken file instead of a working one.

**Comment by JonhyBurner** [comment] 2022-03-04 18:01
Here's the save file:
[Uploading Lisbon's Ravagers NoContract 4 - broken save after advancing day.cpnx.gz…]()

Just to add that the behaviour when loading this is a hard crash of the app. The window closes with OpenJDK exe still open when I check Task Manager

**Comment by Windchild292** [comment] 2022-03-04 22:43
I've never seen this before, but it looks like GitHub may have swallowed the above save @JonhyBurner

And I'm increasing this to blocker, but still need that save to investigate this properly.

**Comment by JonhyBurner** [comment] 2022-03-04 23:23
Yeah, the sintax got eaten by something when uploading, apparently. Here is another try:
[Lisbon's Ravagers NoContract 4 - broken save after advancing day.cpnx.gz](https://github.com/MegaMek/mekhq/files/8189260/Lisbon.s.Ravagers.NoContract.4.-.broken.save.after.advancing.day.cpnx.gz)

**Comment by Windchild292** [comment] 2022-03-04 23:24
Thanks 😄

**Comment by Windchild292** [comment] 2022-03-06 15:15
The save loads fine, it just takes a while to do so (maybe 30 seconds for me). This was the same behaviour as when I tried it out using the pre-advancement save.

It's thus working as intended from my testing, although it did take nearly 3GB of RAM to process the file (do note that this was done in a dev environment, which does mean it has a higher baseline RAM usage). The load staging on our end will be clearer once #3156 is merged, and I'll open a fix to change the tool tip text so it better warns about potential I/O issues.

**Comment by JonhyBurner** [comment] 2022-03-06 20:56
Alright, I can confirm that it does eventually load (although it took  a couple of minutes for me, which is why I thought the save was broken). 
And the tooltip is very appreciated, I really thought I had broken my game when I saw all those logged messages!

**Closed** 2022-03-09 15:01 UTC
Labels: Bug, GUI
