### ISSUE TITLE
[0.50 Release] Dropships missing a single crewmembers e.g. a vessel gunner no longer count as valid transport

### ISSUE THREAD

**Issue by UlyssesSockdrawer** [MegaMek/mekhq#4970] opened 2024-10-03 07:18 UTC
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Medium (Gameplay Limitation): Non-core functionality is impaired, providing a suboptimal but playable experience.

### Brief Description *

When a player has a dropship in their force, but the dropship is missing a single crewmember (in my case, a Vessel Gunner), the dropship is put into a 'Lightly damaged' status in the MekHQ hangar.

This makes the dropship ineligible to count as a unit transport and tanks the player's reputation. This can happen unnoticed or be difficult to spot if a crewmember retires or dies due to random chance.

![image](https://github.com/user-attachments/assets/9601524a-15ee-43ea-ad1d-bb32ab75f337)

The modifier for Partially Crewed Large Craft shows up correctly in the report, but based on discussions in the Discord, this shouldn't invalidate the dropship as a transport.

### Steps to Reproduce

1. Set up a campaign unit requiring transport (i.e. at least a few meks)
2. Add a dropship to the campaign, fully crew it
3. Advance to next Monday - transport reputation improves
4. Unassign a vessel gunner or other crew from the dropship
5. Advance to next Monday
6. Transport reputation drops as if no units are transported

### Operating System *

Windows 11

### Java Version *

17.0.12

### MekHQ Suite Version *

v0.50.0

### Attach Files

[NovaDragoonsDropshipCrewTest.cpnx.gz](https://github.com/user-attachments/files/17240695/NovaDragoonsDropshipCrewTest.cpnx.gz)

[customs.zip](https://github.com/user-attachments/files/17240698/customs.zip)

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by IllianiCBT** [comment] 2024-10-18 18:04
This is working as intended. As per CamOps only fully crewed DropShips count towards the units' Reputation. Closing.

**Closed by IllianiCBT** 2024-10-18 18:04 UTC
Labels: Severity: Medium
