### ISSUE TITLE
Infantry personalty description is too wide

### ISSUE THREAD

**Issue by repligator** [MegaMek/mekhq#4474] opened 2024-07-23 15:29 UTC
Developmental
Linux
Java 17

See screenshot. Note this is only the case for infantry, the other professions appear fine, although I haven't had a chance to check BA/Elementals yet.

![Screenshot_20240723_112400](https://github.com/user-attachments/assets/5f60284f-25dd-451d-94a5-1d475fd8f57a)

**Comment by IllianiCBT** [comment] 2024-07-23 19:51
This issue was caused by us not throttling the width of the unit view.

**Comment by IllianiCBT** [comment] 2024-07-23 20:02
Closing as resolved (manually closing to make it easier for us to see what issues still need actioning).

**Closed by IllianiCBT** 2024-07-23 20:02 UTC
Labels: Bug, Personnel, GUI
