### ISSUE TITLE
[RFE] Reputation incorrectly penalizing lack of jumpships

### ISSUE THREAD

**Issue by LadyAdia** [MegaMek/mekhq#5486] opened 2024-12-21 15:39 UTC
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the RFE to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] Does this conform with our Content Policy linked above?
- [X] I've searched the GitHub tracker and haven't found a similar feature request listed

### RFE Details *

This is an implementation of a missing official rule

### Brief Description *

The current reputation report adds a -5 penalty to combatant capacity if the unit has dropships but no jumpship. This does not line up with RAW. See CO pg. 33

### MekHQ Suite Version *

v0.50.02 SNAPSHOT

### Final Checklist

- [X] I've checked to make sure that this RFE has not already been filed
- [X] I am requesting implementation of only one relevant set of features in this ticket for clarity and focus

**Comment by IllianiCBT** [comment] 2024-12-21 19:01
Apparently I can't read. I'll get this fixed in a moment

**Comment by IllianiCBT** [comment] 2024-12-21 19:02
Adia, can you upload your save -- I just checked the code and I'm not seeing a -5 JumpShip penalty.

**Comment by LadyAdia** [comment] 2024-12-21 19:22
[Raven's Nest.cpnx.gz](https://github.com/user-attachments/files/18219693/Raven.s.Nest.cpnx.gz)

**Comment by IllianiCBT** [comment] 2024-12-21 20:20
So the issue isn't your lack of JumpShips, for some reason it's not putting your Light Vehicles into your spare vehicle bays. Investigating.

**Comment by IllianiCBT** [comment] 2024-12-21 20:36
Closing as resolved

**Closed by IllianiCBT** 2024-12-21 20:36 UTC
Labels: (RFE) Enhancement
