### ISSUE TITLE
Bad String in Equatorial Temperature of Planets

### ISSUE THREAD

**Issue by scJazz2** [MegaMek/mekhq#109] opened 2016-06-20 17:02 UTC
For the planets that have Canon data the string for temperature includes this extra character.

Example.
36**Â**°C (Temperate)

**Comment by Akjosch** [comment] 2016-06-20 17:48
Can you provide a screen shot *where* this is the case? Both the planetary info panel and the planet event editor look fine to me.

**Comment by scJazz2** [comment] 2016-06-20 17:52
Theme is Metal if that makes any difference.

It occurs on EVERY Canon sourced planet. Terra used for example.


![bad chars](https://cloud.githubusercontent.com/assets/16738384/16204692/1dbcf2c6-36ee-11e6-88e9-d3166a984479.jpg)

**Comment by Akjosch** [comment] 2016-06-20 17:58
That's weird, and seems like a locale-related issue (specifically, for the *packager*).

It doesn't happen in my development environment, and neither does it happen for me with my automated daily builds. It *does* happen with the 0.3.29 release. We'll have to investigate how the source files managed to be interpreted as anything but UTF-8 encoded.

**Comment by Akjosch** [comment] 2016-06-22 08:19
I added `encoding="UTF-8"` to the build files, which should (in theory) enforce that even when someone builds on Windows. Daily build worked fine; we'll see if it is fixed next release.

**Comment by BLOODWOLF333** [comment] 2016-06-23 01:50
I just opened up 0.3.29 today for the first time and seen this as well.

**Comment by pheonixstorm** [comment] 2016-06-23 04:23
Looks like it could be fixed for the next release. This will probably be closed after the next release if it doesn't pop up again

**Comment by Akjosch** [comment] 2016-06-29 21:05
I need your feedback: Do you see the problem anywhere still?

**Comment by BLOODWOLF333** [comment] 2016-06-30 01:59
Yes the EQ temp string is now fixed but, your map filter button is broken now, and are planets with no data meant to no longer show the default values of 20'c, 70% surface water, & 1.0g's on purpose in 0.3.30?

![mm0](https://cloud.githubusercontent.com/assets/16950832/16474430/6717ca5e-3e3c-11e6-9c2d-36aab8cff114.png)

**Comment by Akjosch** [comment] 2016-06-30 04:30
Values not showing when they aren't there is on purpose. Calculations and routines use the default values when required.

**Comment by Akjosch** [comment] 2016-08-29 15:19
(Confirmed working)

**Closed by Akjosch** 2016-08-29 15:19 UTC
Labels: help wanted
