### ISSUE TITLE
[0.49.19] "Sorry can't save" + broken autosaves

### ISSUE THREAD

**Issue by repligator** [MegaMek/mekhq#4046] opened 2024-05-01 23:30 UTC
### Environment
[0.49.19], Linux, Java 17.0.10

### Description
Playing a new campaign in .19. Started today, only a few hours in. I attempted to manually save and got an error message (apologies, I should screen-capped it) that said something along the lines of "Sorry, the game can't be saved, please submit a bug report". I closed and reopened mekhq. I was saddened to find that all of the auto-saves seem to be broken as well. I hadn't made a manual save yet. I was quite enjoying that campaign too. Is there any chance I can manually repair the save files>

All of the autosaves end in 
`			<c3i_link link="`
like they just got cut off somehow. I've attached the newest and oldest autosave, as well as the mekhq log.
[Autosave-1-Lyran3067-30680822.cpnx.gz](https://github.com/MegaMek/mekhq/files/15182192/Autosave-1-Lyran3067-30680822.cpnx.gz)
[Autosave-1-Lyran3067-30680818.cpnx.gz](https://github.com/MegaMek/mekhq/files/15182193/Autosave-1-Lyran3067-30680818.cpnx.gz)
[mekhq.log](https://github.com/MegaMek/mekhq/files/15182194/mekhq.log)

**Comment by kuronekochomusuke** [comment] 2024-05-01 23:38
duplicate of #4034 

A work around for this may be to regenerate bot forces to get one without any c3master, c3i, or nc3 units.   Or just remove the scenarios until you get ones that save.

**Comment by gsparks3** [comment] 2024-05-01 23:38
Think this is the same issue we found a little earlier: #4034 

It looks like there is a workaround, but only if you can clear out the offending C3i units _before_ saving or closing the program. If the units are in your own forces rather than enemy forces as for the linked issue, that's not good; every save you tried to make without just deleting the units would hit the bug.

**Comment by IllianiCBT** [comment] 2024-06-04 02:08
Looks good in 49.20 -- the duplicate issue has been closed for a while. Closing this as resolved.

**Closed by IllianiCBT** 2024-06-04 02:08 UTC
Labels: Bug, Duplicate
