### ISSUE TITLE
Damaged Jumpship during every load in a campaign

### ISSUE THREAD

**Issue by CrimsonThunderSB** [MegaMek/mekhq#1153] opened 2019-03-18 06:22 UTC
### Environment
0.45.3  WIN10
Java build 1.8.0_201-b09

### Description
Every Time I load my campaign, I notice that my Invader Jumpship has to have its thrusters replaced.  It doesn't matter how far I progress in a session, When I leave, then load back up, I always find the jumpship in the repair bay.  All you need to do is load a campaign, and just a quick gm complete task, save, close, then reload that exact save, and the jumpship is back in the repair bay.

### Files
[Stormbringing Destroyers bugged and mekhq log.zip](https://github.com/MegaMek/mekhq/files/2976600/Stormbringing.Destroyers.bugged.and.mekhq.log.zip)

**Comment by VicenteCartas** [comment] 2019-03-19 02:23
Is it the Invader PPC ship? I can't load the campaign as is, it's asking me for unit customs.

**Comment by CrimsonThunderSB** [comment] 2019-03-19 02:39
> Is it the Invader PPC ship? I can't load the campaign as is, it's asking me for unit customs.

correct, and I don't have any custom units in that campaign.

**Comment by CrimsonThunderSB** [comment] 2019-03-19 02:41
but if it helps, I will add my custom units just so you can access it, the new zip file on this should have the custom units in the folder I provided.
[Stormbringing Destroyers bugged and mekhq log.zip](https://github.com/MegaMek/mekhq/files/2981293/Stormbringing.Destroyers.bugged.and.mekhq.log.zip)

**Comment by mkerensky** [comment] 2019-03-21 12:52
I think you've managed to get some old data files that are causing your issue.

Go into your MHQ\data\mechfiles folder
Make a copy of "Jumpships.zip" and put it somewhere safe and outside the MHQ folder structure as a backup.
Replace Jumpships.zip in the mechfiles folder with the attached copy.
Delete Units.cache

Try and load your game again. 
[jumpships.zip](https://github.com/MegaMek/mekhq/files/2992075/jumpships.zip)

**Comment by CrimsonThunderSB** [comment] 2019-03-22 12:50
It worked, thank you :)

**Comment by NickAragua** [comment] 2019-03-22 13:16
Closing since the issue is resolved.

**Closed by NickAragua** 2019-03-22 13:16 UTC
