### ISSUE TITLE
MekHQ MegaMek allowed tech level option not saving and loading correctly

### ISSUE THREAD

**Issue by monbvol** [MegaMek/mekhq#140] opened 2016-08-22 02:52 UTC
[TechLevelBug.zip](https://github.com/MegaMek/mekhq/files/429273/TechLevelBug.zip)

Odd one here.  I set allowed Tech Level to Experimental launched the New Scenario in the campaign with the COM-2D Commando and verified it could load NARC specialty ammunition.  Saved campaign and re-loaded.  Allowed Tech level was set back to Standard and NARC was not available as a specialty ammunition.

So clearly something going on that is not correctly saving and loading allowed tech levels and flagging specialty ammunitions as not being available even though they should be even at the lower tech level.
![techlevelbug1](https://cloud.githubusercontent.com/assets/17420975/17842530/ba8da5a8-67d8-11e6-8281-d71db42546e5.png)
![techlevelbug2](https://cloud.githubusercontent.com/assets/17420975/17842534/c0bc1c0c-67d8-11e6-96a4-4f8406c53e91.png)

**Comment by pheonixstorm** [comment] 2016-08-22 11:26
Duplicate of #83 so its a known issue. Only workaround is to reset your tech level whenever you load your campaign.

I looked into this and MekHQ does save it correctly but I was underable to find out why it would not load it correctly from the campaign file. The code looks like it should work but doesn't.

**Comment by neoancient** [comment] 2016-09-26 05:27
Fixed in [c50d67c].

**Closed by neoancient** 2016-09-26 05:27 UTC
