### ISSUE TITLE
Base Salary for LAM Pilots always reverts to "0"

### ISSUE THREAD

**Issue by BowtieBob** [MegaMek/mekhq#2275] opened 2020-12-11 23:31 UTC
No matter how many times I have changed the base salary for LAM pilots, it always changes back to 0 as soon as I leave the campaign options dialog.

### Environment
What version of MekHQ does your issue apply to? 0.46.1
What operating system are you using?  Windows, Mac, or Linux? Windows
What java version are you using?  Version 8 Update 271

**Comment by Windchild292** [comment] 2020-12-11 23:33
Fixed in develop.

**Closed by Windchild292** 2020-12-11 23:33 UTC

**Comment by sixlettervariables** [comment] 2020-12-11 23:36
Duplicate of #2188 fixed in #2192
