### ISSUE TITLE
Bug: Heat Sink can't be repaired

### ISSUE THREAD

**Issue by Wargamer777** [MegaMek/mekhq#2376] opened 2021-01-18 01:21 UTC
### Environment
.47.16
Windows 10
Version 8 Update 271 JAVA

### Description
Heat Sinks can't be repaired on mechs.  In addition, if assigning Mech Techs to fix it, they get stuck saying another Mech Tech is already working on the repair.

In addition, the activity log display is now stuck.  When you advance the day the display doesn't update, it appends the day log to the previous day.

[BHM Day Advance Problem.cpnx.gz](https://github.com/MegaMek/mekhq/files/5827232/BHM.Day.Advance.Problem.cpnx.gz)

**Comment by sixlettervariables** [comment] 2021-01-18 02:07
Duplicate of https://github.com/MegaMek/mekhq/pull/2366

**Closed by sixlettervariables** 2021-01-18 02:07 UTC
Labels: bug

**Comment by sixlettervariables** [comment] 2021-01-18 02:09
If you remove any spare AeroHeatSinks you may have in your inventory you can get past this bug for now.

**Comment by Wargamer777** [comment] 2021-01-18 22:03
> 
> 
> If you remove any spare AeroHeatSinks you may have in your inventory you can get past this bug for now.

Didn't work.  I had 24 AeroHeatSinks salvaged in the Warehouse.  I went and sold them all.  Bug still remains.
