### ISSUE TITLE
Starting a stratcon generated mission results in immediate disconnect from Megamek.

### ISSUE THREAD

**Issue by entropyembrace** [MegaMek/mekhq#2955] opened 2021-11-19 02:31 UTC
### Environment
What version of MekHQ does your issue apply to?
0.49.5 dev snapshot
What operating system are you using?  Windows, Mac, or Linux?
windows 10
What java version are you using?  If unsure it will state your java version at the top of the mekhqlog.txt file.
Temurin 11 jdk-11.0.13+8

### Description
Describe the issue and provide screenshots ingame if able.
Starting a stratcon generated mission results in immediate disconnect from Megamek.
I have set memory for MekHQ and Megamek to -Xmx4096m, set the MekHQ delay to 2000, allowed invalid units, and regenerated bot forces; and the issue persists.
this contract is in 2787 against FWL

### Files
[megameklog.txt](https://github.com/MegaMek/mekhq/files/7567410/megameklog.txt)
[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/7567412/mekhqlog.txt)
[Steeletech Security27870121.cpnx.gz](https://github.com/MegaMek/mekhq/files/7567413/Steeletech.Security27870121.cpnx.gz)

**Comment by Windchild292** [comment] 2021-11-19 03:22
```
19:20:44,537 ERROR [mekhq.AtBGameThread] {Steeletech Security} 
run(), line 380 : Total board area must be positive
java.lang.IllegalArgumentException: Total board area must be positive
	at megamek.common.MapSettings.setBoardSize(MapSettings.java:550)
	at mekhq.AtBGameThread.run(AtBGameThread.java:118)
```

**Comment by NickAragua** [comment] 2021-11-23 03:19
As a work-around, try right clicking on the scenario, selecting "edit" and "regenerate bot forces". This is likely a failure to generate the "primary opfor".

**Comment by entropyembrace** [comment] 2021-11-23 04:27
> As a work-around, try right clicking on the scenario, selecting "edit" and "regenerate bot forces". This is likely a failure to generate the "primary opfor".

I have tried "regenerate bot forces" several times. It has never resulted in a playable mission.

**Comment by Windchild292** [comment] 2022-01-10 17:34
Caused by https://github.com/MegaMek/megamek/issues/3365, and will be fixed as part of that issue.

**Closed by Windchild292** 2022-01-10 17:34 UTC
Labels: Bug, AtB, StratCon
