### ISSUE TITLE
[12-15 Logistics Artifact Nightly] Oddities in log file behavior

### ISSUE THREAD

**Issue by LadyAdia** [MegaMek/mekhq#5384] opened 2024-12-16 02:21 UTC
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Medium (Gameplay Limitation): Non-core functionality is impaired, providing a suboptimal but playable experience.

### Brief Description *

When starting MHQ, a series of unusual system messages showed on the terminal. After closing MHQ and opening the .log file to investigate a separate issue, the .log file was empty. Upon reopening the program to obtain a screenshot of the terminal and checking the .log file again, it was at first blank, but after a short time passed, the log file became populated.

<img width="1440" alt="Screenshot 2024-12-15 at 8 02 57 PM" src="https://github.com/user-attachments/assets/afec0992-a776-4798-a42f-9cf33c2aa47f" />

### Steps to Reproduce

Run MHQ

### Operating System *

Mac

### Java Version *

17.0.12

### MekHQ Suite Version *

Free Text (type manually)

### Custom MekHQ Version

0.50.02 Nightly Logistics Artifact

### Attach Files

[MHQ Log Issue 24-12-15.zip](https://github.com/user-attachments/files/18143697/MHQ.Log.Issue.24-12-15.zip)

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by IllianiCBT** [comment] 2024-12-16 03:15
This can happen from time-to-time, usually caused by something going _very_ wrong during load - the autoLogistics error I fixed a moment ago was likely the cause.

Tentatively closing as resolved.

**Closed by IllianiCBT** 2024-12-16 03:15 UTC
