### ISSUE TITLE
[0.49.19] Unable to load HQ file from 49.18

### ISSUE THREAD

**Issue by StarColonel** [MegaMek/mekhq#4077] opened 2024-05-13 03:23 UTC
ill out the fields below with as much pertinent information as possible to help the developers solve the issue.
Search for your issue inside open and closed issues first before reporting so as not to make duplicates.
(Delete the above lines)

### Environment
0.49.19
Windows
Java Version: 17.0.6

### Description
Trying to load a HQ file created in 0.49.18 into 0.49.19 and get this on the loading screen "Campaign Loading Error. The campaign file could not be loaded. Please check the MekHQ.log file for details. 
[mekhq.log](https://github.com/MegaMek/mekhq/files/15288733/mekhq.log)

[1st_Shadow_Army30570201.cpnx.gz](https://github.com/MegaMek/mekhq/files/15289037/1st_Shadow_Army30570201.cpnx.gz)
[Deniables.zip](https://github.com/MegaMek/mekhq/files/15289038/Deniables.zip)

**Comment by HammerGS** [comment] 2024-05-13 03:51
Duplicate of https://github.com/MegaMek/mekhq/issues/4061

fixed for next release.

**Comment by BoloNike** [comment] 2024-05-13 05:32
Potentially still duplicate however i did not find any C3i or other "BAP" style items on units that do not have sensors. He had infantry with special training (Engineers) but no abilities

Attaching same campaign file. Curated customs list (pulled only what needed with MUL changed to -1) and logs.

[1st_Shadow_Army30570201.cpnx.gz](https://github.com/MegaMek/mekhq/files/15289739/1st_Shadow_Army30570201.cpnx.gz)
[Necessary.zip](https://github.com/MegaMek/mekhq/files/15289733/Necessary.zip)

The logs are almost identical except where mine shows "Unknown Source" Rather than a line.

[megamek.log](https://github.com/MegaMek/mekhq/files/15289725/megamek.log)
[megameklab.log](https://github.com/MegaMek/mekhq/files/15289726/megameklab.log)
[mekhq.log](https://github.com/MegaMek/mekhq/files/15289727/mekhq.log)

Hopefully it is still a duplicate but with not finding any of the "BAP" stuff yall mentioned figured i would send the additional data as i mentioned i would earlier

**Comment by Sleet01** [comment] 2024-05-13 06:05
I was able to load the @StarColonel 's campaign in 0.49.19.1, which includes the fix for #4061 , without any other changes.
I'm not sure _which_ unit was not loading correctly, but this indicates strongly that the issue is fixed in 0.49.19.1 and 0.49.20, and likely is caused by the unit reset / BAP-without-sensors handling error.

@BoloNike I'm relatively certain that we do not see any _loading_ bugs caused by incorrect MUL numbers, as the field itself is just a string and only consumed by sort lists and the URL generator in newer versions of MML.
However, I would expect to see issues with refits if the MUL were incorrect as I believe we compare them when deciding if a given variant is a refit option, or just the same unit type, as a given unit - and having the same MUL might cause issues during that check.

**Closed by Sleet01** 2024-05-13 06:05 UTC
Labels: Bug, Duplicate
