### ISSUE TITLE
Stratcon base attack: multiple capture objectives

### ISSUE THREAD

**Issue by Tempest-56** [MegaMek/mekhq#5220] opened 2024-11-19 03:42 UTC
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Medium (Gameplay Limitation): Non-core functionality is impaired, providing a suboptimal but playable experience.

### Brief Description *

Pulled a Data Center - Hostile - Prevent Evac scenario. The objectives include two entirely separate and conflicting objectives: 
`Leave intact at least 75% of the following force(s) and unit(s) in order to be able to take control of this facility:
	Free Worlds League Base Defenses`
and
`Destroy, cripple or force the withdrawal of 75% of the following force(s) and unit(s) to take control of the facility:
	Free Worlds League OpFor`

These are in addition to the other, more normal objectives. There probably shouldn't be two of those in the same scenario.

### Operating System *

Windows 11

### Java Version *

17

### MekHQ Suite Version *

v0.50.0

### Custom MekHQ Version

Snapshot as of 11/1

### Attach Files

[Autosave-2-Alley Cats-30170128.cpnx.gz](https://github.com/user-attachments/files/17808921/Autosave-2-Alley.Cats-30170128.cpnx.gz)

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by IllianiCBT** [comment] 2024-11-19 17:13
So, now that I've been able to look into this properly, I can confirm this is working as intended: you are required to preserve 75% of the base defenses, while routing 75% of the base defenses. That first parameter being 75% is a bug, however. I'll get that fixed in a moment.

**Comment by IllianiCBT** [comment] 2024-11-19 17:17
Closing as resolved

**Closed by IllianiCBT** 2024-11-19 17:17 UTC
Labels: StratCon
