### ISSUE TITLE
RFE: Custom Rank Titles not saving between playthroughs 

### ISSUE THREAD

**Issue by HereticGIT** [MegaMek/mekhq#1924] opened 2020-08-16 00:56 UTC
OVERVIEW/TL;DR: Whenever I go to save my campaign presets, my custom ranks are not saved; when I go to load said presets, I have to manually reenter my custom ranks. 

(Forum thread this issue originates from is https://bg.battletech.com/forums/index.php?topic=70007.0)

### Environment
Using the most stable version of MekHQ (0.46.1)
Running on Java version 8u241
Running the most recent/up-to-date version of Windows 10

### Description
I can't be the only person who has this particular problem. I meticulously enter my custom rank titles, go to save my campaign presets, and play my game. Whenever I start a new campaign *with the same presets,* my rank titles are gone and I have to spend at least 5-10 minutes reentering them and double-checking to make sure I got them all right. And I know that the next time I boot up those presets, my ranks will have to be reentered *again.*

One solution is entering my rank titles into a framework save (included) and then using that to play, but I'd rather there be a simpler fix. Perhaps a "Save Custom Ranks" button?

### Files
[megameklog.txt](https://github.com/MegaMek/mekhq/files/5079803/megameklog.txt)
[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/5079804/mekhqlog.txt)
[CPNX FILES THAT MY ERROR OCCURS IN.zip](https://github.com/MegaMek/mekhq/files/5079805/CPNX.FILES.THAT.MY.ERROR.OCCURS.IN.zip)
[HOW THE CUSTOM RANKS ARE SUPPOSED TO BE SETUP (ROUGHLY).zip](https://github.com/MegaMek/mekhq/files/5079806/HOW.THE.CUSTOM.RANKS.ARE.SUPPOSED.TO.BE.SETUP.ROUGHLY.zip)

[FRAMEWORK SAVE I AM USING AS A STOPGAP.zip](https://github.com/MegaMek/mekhq/files/5079799/FRAMEWORK.SAVE.I.AM.USING.AS.A.STOPGAP.zip)

**Comment by Windchild292** [comment] 2020-11-07 01:32
Duplicate of #1483

**Closed by Windchild292** 2020-11-07 01:32 UTC
Labels: Personnel, enhancement
