### ISSUE TITLE
Unit Rating panels do not update with personnel changes

### ISSUE THREAD

**Issue by sixlettervariables** [MegaMek/mekhq#1135] opened 2019-03-03 16:25 UTC
### Environment
What version of MekHQ does your issue apply to? 45.X
What operating system are you using? Mac
What java version are you using? Java 8

### Description
Unit rating panels do not update automatically on personnel changes.

**Comment by Windchild292** [comment] 2019-12-27 15:26
This appears to have been resolved.
Testing on 0.47.2, Windows 10.

**Comment by Windchild292** [comment] 2019-12-28 22:59
This appears to have been resolved for Campaign Operations Unit Rating, testing on latest develop (post 0.47.2), Windows 10.

**Comment by rjhancock** [comment] 2020-02-18 18:24
Using 47.4 MekHQ

Opened Last Save (Fox's Teeth)
Checked Unit Rating
Added 12 Mech Techs and assigned to Mechs.
Re-checked Unit Rating.
No Change.

**Comment by Windchild292** [comment] 2020-09-28 20:21
Just had this happen for me.... so definitely not resolved.

**Comment by Windchild292** [comment] 2023-02-04 16:52
Tech number changes do not always force a refresh, which led to #3532

**Comment by repligator** [comment] 2024-08-25 18:49
Unit rating no longer updates instantly by design. Closing as no longer applicable.

**Closed by repligator** 2024-08-25 18:49 UTC
Labels: Bug, Unit Rating, Personnel
