### ISSUE TITLE
Choose spouse doesn't allow same sex spouses 

### ISSUE THREAD

**Issue by molemanBT** [MegaMek/mekhq#5233] opened 2024-11-22 15:03 UTC
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Low (Minor/Nuisance): Minor glitches or cosmetic issues that don’t affect gameplay and occur rarely.

### Brief Description *

Right click, assign spouse - can only choose opposite sex on the latest release

### Operating System *

Windows 11

### Java Version *

Latest

### MekHQ Suite Version *

v0.50.0

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by molemanBT** [comment] 2024-11-22 19:26
I have a custom unit logo if that matters

**Comment by psikomonkie** [comment] 2024-11-23 16:55
Hey @molemanBT , I took a peek at peek at your save & I see your issue - Carolyn Hoem is not flagged as "Marriageable". If you right click her in the "Personnel" tab, go to "Flags", and check "Marriageable", she will be able to marry. 

Your company only has 2 women, and one of them is not flagged as marriageable, so it shows no eligible same-sex spouses. You only have one man as well, so he can't marry anyone of the same-sex either.

**Comment by IllianiCBT** [comment] 2024-11-23 16:57
I did wonder if that might have been playing a part.

Closing: working as intended

**Closed by IllianiCBT** 2024-11-23 16:57 UTC
Labels: Needs More Info, Personnel
