### ISSUE TITLE
Motive Damage on Vehicles not repairable

### ISSUE THREAD

**Issue by CormacAers** [MegaMek/mekhq#774] opened 2018-06-26 23:50 UTC
### Environment
mekhq version: 0.43.2-git on Windows

### Description
Motive Damage on vehicles is not repairable once it hits 4/4.
it happens with weeled, tracked and hover.
you can repair the damage in the repair bay and the vehicles is taged as undamaged, but if you try to edit the damage of the vehicle in gm mode, you can still see the 4/4 motive damage (and even if you edit the damage in gm mode, it does not change it, and if you 'damage' the armor by 1 damage, you get both motive damage and the armor as a repair task again)

reloading the game seems to fix the issue, this happens with all vehicles i've used so far. to replicate it, the damage must be done inside megamek (if you use gm mode to damage the vehicle, it shows the vehicles as crippled, but after looking into the edit damage vehicle again it shows 0/0 motive damage), what i havn't tested is it may be possible that the same problem happens with less than 4/4 damage.

**Comment by HammerGS** [comment] 2018-06-26 23:51
Can you attach the log files, cpnx file, and any customs as well.

Thanks

**Comment by NickAragua** [comment] 2018-06-27 00:12
We also do have a 44.0 stable version that just came out a couple of days ago, you may consider trying that.

**Comment by CormacAers** [comment] 2018-06-27 02:29
fresh 'installation' in a new folder, current version 0.44. 
no custom files, vehicles or rules. starting a new game, standart year 1/1/3067, official AtB options and than directly confirm. 
going into gm mode, add 2 saladin assault hover tank (ultra) as well as crew&techs for them. (as well as astechs) and add those two tanks into a force. 
after that, i created a new contract via 'ass mission' dialog and without any changes creating it. add a scenario, 
after that, i just let mekhq start megamek for me, added a bot with any unit, place my units and just retreat. in the after mission report, i edit those two tanks to have motive damage (as well as some armor damage). one tank has 2 motive damage, the other one 4. 
i repaired the damage of the vehicles with my techs in normal way, after checking with admin tool none of those two tanks had any motive damage left. after creating a new scenario and placing the vehicles again, the second one still was immobile. progressing the day after fixing the damage does not fix the bug, the admin mode does not show the motive damage on the vehicles in the hanger, but deploying them still shows one of them as immobile. 

again: saving and reloading the game fixes the bug, the tanks deployed after reloading are in fully repaired state. 
[logs.zip](https://github.com/MegaMek/mekhq/files/2139601/logs.zip)

**Comment by NickAragua** [comment] 2018-06-27 02:32
Ok, thanks for reproducing it on the current version, that should give us enough to go on. It's likely there's some flag that's not getting reset for those units in between missions.

**Comment by CormacAers** [comment] 2018-06-27 02:39
i have to thank you, you are doing most of the work^^ don't worry and take your time to fix it.
btw, just checked: if you do not repair the damage and save&reload, the damage stays on the tank, so there is no reset on it's own while saving. good luck finding the bug and for me it's night now, if any more questions arise, i won't be able to reply within the next 5-8 hours.

**Comment by CormacAers** [comment] 2018-07-11 22:00
instead of adding a new issue, i will add this here:
mekHQ version 0.44.0
was able to gain a catapult after a mission (only real damage it got was a destroyed head and i think a damaged hip/whatever). after repairing the mech it was still labled as crippled, and i was not able to deploy the unit when taking it into a mission (it was showing in the list, but after starting the 'board'game, the game wasn't even showing it in the right hand.)

after saving&reloading the game, the mech was labled as undamaged and was deployable again.
it only happened with that salvaged mech, i had multiple mechs both damaged&salvaged in this 'playthrough' with damage to all kind of systems (but i don't think any of them was killed by a headshot)

**Comment by Kalkkis** [comment] 2018-07-12 17:56
Pilot getting ko'd seems to also persist between missions.

**Comment by Zogundar** [comment] 2020-09-12 00:30
Having a similar problem, captured a couple of tanks and thought I'd repair them, was almost done when I saw that they still had 0/0 movement. Motive damage.

Ok, not sure why it's doing that since it wasn't destroyed in the first place, but ok I'll use GM mode to set it to 3 ticks and then repair the rest.

..Still at 4 motive damage. Fine, just repair it all.

4 motive damage, 0/0 movement.

Fine, just restore the unit!

4 motive damage, 0/0 movement.

FINE, I'll add a new one and delete the old one!

4 motive damage, 0/0 movement.

Can I, in fact, add any land vehicles without them automatically having permanently crippled damage?
*Adds a Flatbed Truck (Standard)*
*Adds a Saladin Assault Hover Tank (Armor)*

4 motive damage, 0/0 movement, and 4 motive damage, 0/0 movement.

Looks like that's a "no."

**Comment by Windchild292** [comment] 2020-09-12 01:04
You are describing #1376, just hire a crew and it will work

**Comment by HammerGS** [comment] 2020-09-12 17:24
I've seen this in my campaign as well. Fix the units then add the crew and still gets motive issues.

**Comment by sixlettervariables** [comment] 2020-12-05 03:21
Mostly fixed by https://github.com/MegaMek/megamek/pull/2466

**Closed** 2020-12-05 03:21 UTC
Labels: bug
