### ISSUE TITLE
[0.50.1-SNAPSHOT] SPA tooltips are messed up

### ISSUE THREAD

**Issue by WeaverThree** [MegaMek/mekhq#4995] opened 2024-10-06 01:52 UTC
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

High (Major Disruption): A major feature is broken or incorrect, but a workaround exists.

### Brief Description *

Hovering over Mek Tech SPAs produces nothing. Hovering over normal SPAs produces overly tall boxes and one of them (eagle's eyes) only shows the last word of the string.

![2024-10-05_181050](https://github.com/user-attachments/assets/83e380c1-7acd-45f1-a8a4-229de8c10039)
![2024-10-05_181226](https://github.com/user-attachments/assets/7d9b8e69-2c4e-4921-8189-54b90bb2cecb)
![2024-10-05_181244](https://github.com/user-attachments/assets/63824728-d782-4f29-9f3b-aae116949ea7)

### Operating System *

Windows 11

### Java Version *

17.0.12

### MekHQ Suite Version *

Free Text (type manually)

### Custom MekHQ Version

v0.50.01-SNAPSHOT 2024-10-04

### Attach Files

17:41:12,058 INFO  [mekhq.MekHQ] {main}
mekhq.MekHQ.initializeLogging(MekHQ.java:306) - Starting MekHQ v0.50.1-SNAPSHOT
    Build Date: 2024-10-05T03:21:32.082133455
    Today: 2024-10-05
    Origin Project: MekHQ
    Java Vendor: Eclipse Adoptium
    Java Version: 17.0.12
    Platform: Linux 6.11.2-201.fsync.fc40.x86_64 (amd64)
    System Locale: en_US
    Total memory available to MekHQ: 8 GB
    MM Code Revision: e1d2728d2a51e221c92f9f8d1855e899303a4386
    MML Code Revision: 446bd8d9c7e28bfdf49d35f312d838c44e16941a
    MHQ Code Revision: 036d7bea06aa05b4e65424baa02bf8b67d5c78f3

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by WeaverThree** [comment] 2024-10-07 02:53
Another example:

![2024-10-06_195323](https://github.com/user-attachments/assets/cc53cf97-a82b-4e9b-9990-325d1b57de6e)

**Comment by IllianiCBT** [comment] 2024-10-10 16:55
This will be caused by the name rename project. A number of xml files got reformatted, with added new lines. However, unlike a resource bundle, those new lines are preserved when the information is presented to the user.

This is likely to be a large project, as I anticipate most xml are likely affected depending on how Tex made the changes. Whether he only used AI reformatting on a couple (the big ones, for example, like education) or whether he applied it across all xml files.

**Comment by IllianiCBT** [comment] 2024-10-20 21:28
Closing as resolved

**Closed by IllianiCBT** 2024-10-20 21:28 UTC
Labels: Bug, GUI, Severity: High
