### ISSUE TITLE
TOE Forces failing to load. 

### ISSUE THREAD

**Issue by Donnerino12** [MegaMek/mekhq#5001] opened 2024-10-07 19:59 UTC
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Medium (Gameplay Limitation): Non-core functionality is impaired, providing a suboptimal but playable experience.

### Brief Description *

TOE no longer has any forces or lances that previously existed shown underneath the company root. I can add new forces and units to those forces, but all other references to the still existing lances are still present in the hangar and in personnel. Forces under these lances can be moved and used as normal on StratCon Tracks. Problem appeared after loading the save, and had no issues the night before when saving and closing the application. 

I have overwritten the save from before the problem showed up, so unfortunately I don't have any before/after comparisons to give. Uploaded here is my save.

### Steps to Reproduce

Do not know how to reproduce this issue.

### Operating System *

Windows 10

### Java Version *

17.0.12

### MekHQ Suite Version *

v0.50.0

### Attach Files

[mekhq.log](https://github.com/user-attachments/files/17283821/mekhq.log)
[Autosave-1-The 12th Cavaliers-30620309.cpnx.gz](https://github.com/user-attachments/files/17283827/Autosave-1-The.12th.Cavaliers-30620309.cpnx.gz)

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by Donnerino12** [comment] 2024-10-07 20:17
Small addendum, the meks and personnel removed and moved are from me messing around with things to try and get the TOE show up again.

**Comment by IllianiCBT** [comment] 2024-10-07 20:26
The log is completely empty. Did you take it from the MekHQ folder or the MegaMek folder?

**Comment by Donnerino12** [comment] 2024-10-07 20:36
MekHQ in the logs folder. This is what mekhq.log looks like on my end. 

![image](https://github.com/user-attachments/assets/bb6a19af-c6bc-4b96-8e24-ce366520bb65)

**Comment by IllianiCBT** [comment] 2024-10-07 20:46
Can you launch the client, loading the affected save, close the client and then send the copy of the log that can be founded here: `MekHQ/logs/mekhq.log`

**Comment by Donnerino12** [comment] 2024-10-07 20:49
[mekhq.log](https://github.com/user-attachments/files/17284367/mekhq.log)
Sorry, first time issue reporter and all. Here you go.

**Comment by IllianiCBT** [comment] 2024-10-07 20:52
You're all good :)

Unfortunately, the information we'd need to investigate hasn't been preserved. The best thing to do, is to rebuild your TO&E and keep an eye out. If it happens again we need a copy of the save just prior to it happening - i.e. one with an intact version of your TO&E. This will allow us to load the file and then see specifically what's causing the TO&E load failure.

**Comment by IllianiCBT** [comment] 2024-10-07 20:53
I've marked this as 'needs more info', but I'm going to leave the case open as there is clearly an issue, we just can't replicate with the current save.

**Comment by IllianiCBT** [comment] 2024-10-07 20:56
As someone who was a player long before they were a dev, I found making a rolling save at the end of each session resulted in the least amount of lost progress whenever something goes wrong. i.e. while playing, relying on autosaves, then at the end of the session making a hard save.

**Comment by IllianiCBT** [comment] 2024-12-18 05:05
It's been a couple of months and we've not had any more reports of this happening and without the original save it's not going to be possible to investigate the root cause.

Closing: unable to investigate (sadly)

**Closed by IllianiCBT** 2024-12-18 05:05 UTC
Labels: Bug, Needs More Info, Severity: Medium
