### ISSUE TITLE
All mech mortar smoke rounds turn into shape charged rounds

### ISSUE THREAD

**Issue by Regularitee** [MegaMek/mekhq#1151] opened 2019-03-17 05:50 UTC
Most recent experimental snapshot. What it says on the tin. In the equipment database, items that are listed as "Smoke Mortar __ Ammo", when added to a vehicle, instead display "Shaped Charge Mortar __ Ammo" in the current loadout window.

I'm not sure if it's an issue of the incorrect name displaying in the current loadout window, or if they are actual shaped charge rounds.

**Comment by neoancient** [comment] 2020-12-11 20:16
I think this might be a duplicate of a bug I fixed in MM several months ago. I don't remember the details but it seems familiar

**Closed** 2020-12-13 17:18 UTC
Labels: Needs Investigation
