### ISSUE TITLE
Feature Request [ATB]: Option to have Bot use Infantry as well

### ISSUE THREAD

**Issue by Faolind** [MegaMek/mekhq#342] opened 2017-03-12 21:16 UTC
At current, if, say, you have a mixed ATB merc force, and your scout company of motorized troops gets pulled into a fight, there is a 100% chance that they will be facing vehicles or mechs, regardless as to wether the enemy is an elite force or a backwater world's conscripted militia. Having an option to allow the bot to use Infantry in addition to the aforementioned types (With rates based on a combination of enemy unit rating, and the type of contract, i.e. Planet assault will have more infantry than a lightning raid might) would make combined arms campaigns (ever increasing as the start year moves forwards) more dynamic, believable, and interesting. While also not unfairly penalizing you for hiring 2,000 goons with rifles since they were the only units in the market last month.

**Comment by neoancient** [comment] 2017-03-12 21:55
Closing as duplicate of #152

**Closed by neoancient** 2017-03-12 21:55 UTC
Labels: duplicate
