### ISSUE TITLE
Campaigns do not Load anymore

### ISSUE THREAD

**Issue by DistillerMunich** [MegaMek/mekhq#1846] opened 2020-07-08 18:58 UTC
[Wildcards.zip](https://github.com/MegaMek/mekhq/files/4892692/Wildcards.zip)
I have been running several campaigns in paralell. Last Time  i played the personal tables  in MekHq startet to Freeze, so i shut it off. Now i can't load any savegame from neither Campaign 

### Environment
version of MekHQ 46.0 (with Megamek and Lab)
Windows 10
Java 8_u141 (tried 241 -> returned to 141)

### Description
I think the issue might be tied to the customs as no savegames load, but i can start a new Campaign, Megamek and Lab work fine. When i pick a save the program starts loading , when the progress bar says "Loading Campaign" the window vanishes.
The Task Manager Shows a Java Process, but CPU is at 0%

### Files
I have zipped the last Campaign Save, the customs Folder and the mekhqlog.txt and megameklog.txt

[Wildcards.zip](https://github.com/MegaMek/mekhq/files/4892696/Wildcards.zip)

**Comment by Windchild292** [comment] 2020-07-09 00:28
The issue is tied to personnel, namely one or more people have bad data in one of the following things: 
Skills, Edge, Special Abilities, Hits, Kills, Salary, XP, Origin Faction, Bloodname.

**Comment by Windchild292** [comment] 2020-07-09 00:42
The sheer number of changes in personnel since this point make further debugging of an old version nigh-on impossible. The campaign file in question can be loaded on the current stable and dev releases, and I would recommend an upgrade to either 0.46.1 or 0.47.7 to continue the campaign.

**Comment by Windchild292** [comment] 2020-07-13 17:14
Closing this based on my previous post. However, if your issues persist please reopen this and I'll take another look.

**Closed by Windchild292** 2020-07-13 17:14 UTC
Labels: Personnel, bug

**Comment by DistillerMunich** [comment] 2020-07-14 18:40
Hey Justin,

 

A big thank you Mate. I couldn't get 46.1 to run in the first place, upgrading was the first thing i tried when troubleshooting. I set up my Computer newly and i got it to work. I recommenced playing, and so far everything seems to work fine.

 

Thanks again for your time.

 

Best regards

Markus

 
 

Gesendet: Montag, 13. Juli 2020 um 19:14 Uhr
Von: "Justin Bowen" <notifications@github.com>
An: "MegaMek/mekhq" <mekhq@noreply.github.com>
Cc: "DistillerMunich" <markwimmer@web.de>, "Author" <author@noreply.github.com>
Betreff: Re: [MegaMek/mekhq] Campaigns do not Load anymore (#1846)


 

Closing this based on my previous post. However, if your issues persist please reopen this and I'll take another look.
