### ISSUE TITLE
"Drill Instructor" entry in documentation vs XML

### ISSUE THREAD

**Issue by Stm316** [MegaMek/mekhq#4800] opened 2024-09-06 20:32 UTC
### Environment
mekhq.MekHQ.initializeLogging(MekHQ.java:315) - Starting MekHQ v0.50.1-SNAPSHOT
    Build Date: 2024-09-02T01:23:51.819386835
    Today: 2024-09-06
    Origin Project: MekHQ
    Java Vendor: Eclipse Adoptium
    Java Version: 17.0.11
    Platform: Windows 10 10.0 (amd64)
    System Locale: en_AU
    Total memory available to MekHQ: 4 GB
    MM Code Revision: 380f7143b68a1bdd88725b4c934af9855ddfba9c
    MML Code Revision: 0581ab356323b936a71aca60af9b01fc4d9135d8
    MHQ Code Revision: 32c96c397c275d32012b1aa0c1b3d451d5f50834
Nightly 1601

### Description
I had several units set to training (from long before Auto-Awards, and standard set usually ignored), and Auto-Awards (on promotion and manual triggering) ran, issuing "Drill instructor". The standard.XML award file says range is "Drill Instructor", the document says range is "Training Officer".

**Comment by IllianiCBT** [comment] 2024-09-06 20:34
The documentation is likely wrong here and will need to be corrected.

**Comment by IllianiCBT** [comment] 2024-09-12 19:41
This issue was caused by me using an out-of-date screen grab. Please see below for the correct screen-grab. Documentation has been updated but will not be pushed until later in the 50.01 dev cycle.

Closing as resolved

![image](https://github.com/user-attachments/assets/e1d13f3b-c5f3-4142-9369-55f876f642cd)

**Closed by IllianiCBT** 2024-09-12 19:41 UTC
Labels: Awards, Documentation
