### ISSUE TITLE
Certain parts are green, but can't be repaired

### ISSUE THREAD

**Issue by repligator** [MegaMek/mekhq#4581] opened 2024-08-08 15:49 UTC
### Environment
Linux
Java 17
Master (latest PR https://github.com/MegaMek/mekhq/commit/a45a5251c44f7ab1cc47069bbc66e66f61ecd4c4)

### Description
I'm testing the new presets for the first time, so this may just be some sort of misunderstanding on my part. Some parts are green, but when I click them, no techs are available. When I click off them, they turn grey, and available techs appear.
![Screenshot_20240808_114725](https://github.com/user-attachments/assets/ba905154-464a-47ed-8a46-8a37e087e30d)
![Screenshot_20240808_114746](https://github.com/user-attachments/assets/55a6a2cf-dd3f-4d72-af76-5d4db9a6844e)

### Files
[mekhq.log](https://github.com/user-attachments/files/16550512/mekhq.log)
[strange repair issue Harold's Hunchbacks31510710.cpnx.gz](https://github.com/user-attachments/files/16550514/strange.repair.issue.Harold.s.Hunchbacks31510710.cpnx.gz)

**Comment by repligator** [comment] 2024-08-08 16:48
> What happens if you change repair location, does the issue persist?
Yep, Improvised and Factory both have the same issue. I've also tried mothballing and unmothballing it.

**Comment by IllianiCBT** [comment] 2024-08-08 20:44
I'm not in a position to check the code, but my guess is that we're matching repair site by String somewhere, which is then causing issues when mhq tries to determine the appropriate TN.

**Comment by IllianiCBT** [comment] 2024-08-08 23:50
How was this damaged sustained?

**Comment by IllianiCBT** [comment] 2024-08-09 00:05
Nevermind, I've figured it out. This is actually working as intended. Beneath each task it tells you the experience level of personnel who can attempt the task, this is due to how CamOps handles repairs. Please see page 204 (section titled 'Repair') for more information.

Thank you for the report, though. I actually didn't know it worked like this. :)

Closing as 'working as intended'

**Closed by IllianiCBT** 2024-08-09 00:05 UTC
Labels: Parts/Repair/Refit
