### ISSUE TITLE
0.50.0 Snapshot Astech Shortage

### ISSUE THREAD

**Issue by DynamicWorlds** [MegaMek/mekhq#4387] opened 2024-07-12 22:59 UTC
### Environment
0.50.0 Snapshot (2024-7-10)
Windows 10
Java Version: 17.0.11

### Description
When hitting next day I get a warning message, but bringing all astech teams to full strength doesn't fix the issue.  Persists across days.

### Files
![Temp](https://github.com/user-attachments/assets/742e961e-5899-4792-8b9b-c09805bdfbdd)
[Trond's Dragoons30250215C.cpnx.gz](https://github.com/user-attachments/files/16199876/Trond.s.Dragoons30250215C.cpnx.gz)
[customs.zip](https://github.com/user-attachments/files/16199878/customs.zip)
[megamek.log](https://github.com/user-attachments/files/16199879/megamek.log)
[mekhq.log](https://github.com/user-attachments/files/16199881/mekhq.log)

**Comment by IllianiCBT** [comment] 2024-07-22 10:18
I'm surprised to say that this isn't actually a bug.

Basically you have insufficient AsTech hours, and need more dudes, however you cannot hire more dudes because all of your Tech teams are at full strength. Your options are either to get more techs, or reduce the amount of additional maintenance time you're using. Doing either of those will resolve the issue.

Closing as working as intended.

**Closed by IllianiCBT** 2024-07-22 10:18 UTC
