### ISSUE TITLE
[49.19 Nightly] NPE when assigning scout lance to already scouted hex

### ISSUE THREAD

**Issue by Thom293** [MegaMek/mekhq#3884] opened 2024-03-16 07:39 UTC
Title.  I assigned them to an already scouted lance because it would reveal 2 other unscouted ones.  Got an NPE.

Dismissed it, and the green icon for my lance appeared on the map.  It generated a scenaro in briefing room, but it does not have a map icon.

![image](https://github.com/MegaMek/mekhq/assets/23645569/e875fc01-9e90-4276-a737-4cd8ba1f989a)

![image](https://github.com/MegaMek/mekhq/assets/23645569/afcc86c1-83c8-4618-8987-bbb2ae9966b9)

[Crazed Profanity30690808.cpnx.gz](https://github.com/MegaMek/mekhq/files/14622800/Crazed.Profanity30690808.cpnx.gz)
[mekhq.log](https://github.com/MegaMek/mekhq/files/14622801/mekhq.log)
[Customs.zip](https://github.com/MegaMek/mekhq/files/14622802/Customs.zip)

**Comment by Sleet01** [comment] 2024-04-14 17:33
Closing as duplicate of #3767

**Closed** 2024-04-15 17:17 UTC
Labels: Bug
