### ISSUE TITLE
3.27 : Megamek options -> Tech level is stuck on Standard

### ISSUE THREAD

**Issue by Question2** [MegaMek/mekhq#84] opened 2016-05-23 16:22 UTC
After loading the campaign save and going to file->megamek options and changing the tech level, the tech level always resets to standard tech level after reloading the campaign save.

[#battletech.zip](https://github.com/MegaMek/mekhq/files/277824/battletech.zip)

**Comment by HammerGS** [comment] 2016-05-23 17:48
Duplicate of https://github.com/MegaMek/mekhq/issues/83

**Closed by HammerGS** 2016-05-23 17:48 UTC
Labels: duplicate
