### ISSUE TITLE
Load Last Save not working in MekHQ-0.47.14

### ISSUE THREAD

**Issue by txsoldier94** [MegaMek/mekhq#2253] opened 2020-12-02 05:31 UTC
I have noticed with this new MHQ that I cannot load the last Save. I get the message that the campaign file could not be loaded. Screenshot and log attached. I do not have any issues loading the campaign with the Load a Campaign button, only the loading last save.

### Environment
MekHQ-0.47.14
Win10
Java version 1.8.0_271

![load error](https://user-images.githubusercontent.com/13945328/100832297-2ee71180-342d-11eb-9483-8564ff42a409.jpg)
[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/5627168/mekhqlog.txt)

[Dvorak's Rangers30330920.cpnx.gz](https://github.com/MegaMek/mekhq/files/5627169/Dvorak.s.Rangers30330920.cpnx.gz)
[Dvorak's Rangers30330921.cpnx.gz](https://github.com/MegaMek/mekhq/files/5627170/Dvorak.s.Rangers30330921.cpnx.gz)

**Comment by HammerGS** [comment] 2020-12-02 05:34
We also need the MegaMek log.txt file.

**Comment by txsoldier94** [comment] 2020-12-02 05:36
[megameklog.txt](https://github.com/MegaMek/mekhq/files/5627189/megameklog.txt)

Here you are, thanks!

**Comment by sixlettervariables** [comment] 2020-12-02 14:48
Load Last does not open CPNX.GZ files under 0.47.14. What is your last CPNX file in that directory?

The logs do not have any errors as far as I can see.

**Comment by txsoldier94** [comment] 2020-12-02 14:58
I will have to look when I get home, but I believe they were all .cpnx.gz files
 
 

    On Wednesday, December 2, 2020, 08:48:41 AM CST, Christopher Watford <notifications@github.com> wrote:  
 
 


Load Last does not open CPNX.GZ files under 0.47.14. What is your last CPNX file in that directory?

The logs do not have any errors as far as I can see.

**Comment by sixlettervariables** [comment] 2020-12-02 21:57
So there turns out to be a bug in megameklog.txt, which I didn't open. My apologies! The issue is fixed in some upcoming work https://github.com/MegaMek/mekhq/pull/2229/commits/a4479525c40d9edb81b5371c653e6f94c3821d7e

This is sort of a chicken-and-the-egg problem when we load parts from your Campaign file.

**Comment by txsoldier94** [comment] 2020-12-03 04:43
Ah, thank you for looking into this!  Y'all do great work!

 
 

    On Wednesday, December 2, 2020, 03:57:43 PM CST, Christopher Watford <notifications@github.com> wrote:  
 
 


So there turns out to be a bug in megameklog.txt, which I didn't open. My apologies! The issue is fixed in some upcoming work a447952

This is sort of a chicken-and-the-egg problem when we load parts from your Campaign file.

**Closed** 2020-12-13 17:18 UTC
Labels: bug
