### ISSUE TITLE
Request: set default name and/or flag of Trying to Marry/Conceive on new personnel?

### ISSUE THREAD

**Issue by binaryspica** [MegaMek/mekhq#2357] opened 2021-01-09 18:41 UTC
### Environment
Ver 0.47.16

### Description
For now, the new personnel automatically have random name, as well as 'Trying to Marry' flag by default. If the personnel is female, she also has 'Trying to Conceive' by default as well. But isn't it better to have an option to set when it is on? Such as, able to set default flag of new personnel's name/Marry/Conceive to off by
* Specific Role
* Gender
* Bulk Hire personnel(such as Marketplace-**Bulk Hire Personnel**, **Hire minimum complement** on unit, and Astech/Medic Pool - **Hire Astechs/Medics**)
* Hired personnel by Marketplace - Hire or Personnel Market.
* Random event(such as on Against the Bot event to add the personnel)
* Prisoner
* Prisoners created by additional crew requirement(that is not the unit commander).

If the name is set to off, then the new personnel with such category will have the 'unnamed' as MegaMek, else it is not so bad to set the default name for such red shirts. But name part seems not that important right now.

The really important point is Trying to Marry/Conceive for the company with many personnel makes almost impossible to manually set them all or choose the spouse. You cannot select them all and simply turn it off for all the personnel, for you cannot change these options unless all the personnel have the same flag option, so you need to spend too much time to actually do it all by manually.

Also, what about the option to not put the default portrait on the personnel hired by Bulk Hire personnel, that is take precedence over Campaign Options - Name and Portrait Generation? If you hire each person manually, it is nothing wrong to generate a new portrait. But some of you don't want to generate each simple crews or astech/medic that is not used for the most times. If you want to weight on them enough to give a new portrait, you may hire them manually first or set the random portrait afterwards as well. But since you simply choose bulk hire, I don't think that you will consider them important enough to give a portrait.

**Comment by Windchild292** [comment] 2021-07-18 23:59
Trying to Marry and Trying to Conceive are both override flags for personnel modules, and thus will not be made customizable in the setup described.

Further, MekHQ assumes personnel are individually named by design, and thus that part is against the core design of MekHQ and will not be implemented.

Closing this as it:
1) Goes against the design of the override flags
2) Goes against the design of names in MekHQ
3) Includes multiple issues within a single issue

**Closed by Windchild292** 2021-07-18 23:59 UTC
Labels: Enhancement, Personnel
