### ISSUE TITLE
Single lance force with Scout role generating multiple 'must complete' scenarios on the same day

### ISSUE THREAD

**Issue by SuperStucco** [MegaMek/mekhq#3702] opened 2023-06-22 17:21 UTC
In the attached 49.12 campaign there is a single lance in play.  In order to meet scenario requirements it is given the Scout role on the Briefing tab.

When deployed on the StratCon map it generated a scenario.  The adjacent StratCon map hexes which were revealed also generated/revealed a mission objective facility with a scenario, on the same day.  Even with a deployment delay of 0 days, only the scenario in the original StratCon hex can be completed.  This is not the first time this has happened in this campaign or mission - a previous deployment resulted in a direct scenario and a mission objective scenario in an adjacent hex.

I'm getting around this by GM-pushing the date for the adjacent scenario by one day (or however long the deployment delay is).  But I would like to see some de-conflicting of scenario dates in cases like this e.g. if only a single force is in the TO&E, automatically push revealed scenarios by the deployment delay so they have the opportunity to be completed.

[Houston's Cowboys30060611.cpnx.gz](https://github.com/MegaMek/mekhq/files/11837467/Houston.s.Cowboys30060611.cpnx.gz)
Some custom infantry is present:
[Infantry Pack - Conventional.zip](https://github.com/MegaMek/mekhq/files/11837471/Infantry.Pack.-.Conventional.zip)

**Comment by JonhyBurner** [comment] 2023-06-22 18:53
I'm almost positive that delaying facility objectives doesn't incurr any penalties beyond losing VP/SP. And that missing the deployment date updates it.

It is, of course, a matter of opinion regarding balance, but having an extra reserve lance is good strategy, so I would see this as working as intended. Sometimes the battlefield doesn't behave like we want.

**Comment by Thom293** [comment] 2023-06-23 00:52
Yeah I just considered this normal behavior.  This is what your other lances are for...? I know I have had 3 scenarios on one day before.  Just gotta play whack-a-mole.

**Comment by SuperStucco** [comment] 2023-06-23 19:41
Kinda-sorta?  This time 'round I'm working with a very bare-bones startup.  While there's been some opportunity to expand past the starting lance the +3 era modifier on maintenance and repairs makes upkeep difficult, so expansion is going to be VERY slow. Also working on sustainability with both random death and retirement enabled, which has been a severe struggle with larger formations (to the point I normally play with retirement turned off, and handling it manually).  I can see there being playability issues with only one or two Mechs, that's a little TOO small.  But a single lance should be reasonably playable, especially in certain eras like the early 3000's which did not regularly see massive formations running around.

But beyond that, there's situations like this that pops up:

![Multiple deployment](https://github.com/MegaMek/mekhq/assets/70451747/c44aefd5-5a0d-484f-a265-a91c00484138)

The deployment location scenario is randomly generated, but the Scout role revealed the mission objective scenario in the adjacent StratCon hex.  All fine and good, but the deployment-generated scenario is set for the 28th of the month while the mission objective scenario was generated for the 24th which is the current day.  I can un-deploy the lance from the TO&E but it won't redeploy on the StratCon tab, I have to manually deploy it from the TO&E tab.  Or I can push the mission scenario date back by the deployment delay.  Here's the kicker: there's a 2 day deployment delay and 4 days difference between the two.  The lance could simply go to the one actually required first, then to the later one it was originally deployed to.

Not a big fan of regularly generating no-win situations in this way i.e. the only way to find the mission objective scenario is to go scouting around, but in doing so it makes it impossible for the scenario to be played, let alone completed.

**Comment by Thom293** [comment] 2023-06-24 17:28
Ahh.  Yeah.  I think its balanced around a company start. Maybe an RFE for a single lance start intensity?  Or just skip it.

**Comment by IllianiCBT** [comment] 2024-12-19 18:25
This should be fixed in 50.02. Closing as resolved

**Closed by IllianiCBT** 2024-12-19 18:25 UTC
Labels: (RFE) Enhancement, StratCon
