### ISSUE TITLE
MekHQ.sh launcher script doesn't use Unix line endings

### ISSUE THREAD

**Issue by Algebro7** [MegaMek/mekhq#4867] opened 2024-09-20 13:56 UTC
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Low (Minor/Nuisance): Minor glitches or cosmetic issues that don’t affect gameplay and occur rarely.

### Brief Description *

The `MekHQ.sh` launcher script packaged with the 0.50 release had Windows-style line endings, which does not work on Linux. 

### Steps to Reproduce

The following error happens after extracting the archive and trying to run the program:

```
 $ ./MekHQ.sh
bash: ./MekHQ.sh: cannot execute: required file not found
```

After converting the file to Unix-style line endings with the `dos2unix` tool, the program launches as expected:

```
$ dos2unix MekHQ.sh                                                                                                                                                                            2 
dos2unix: converting file MekHQ.sh to Unix format...
```

Note that you also have to make it executable with `chmod +x`, which isn't a big deal, but it would be nice if it was executable out of the box.

### Operating System *

Linux

### Java Version *

17

### MekHQ Suite Version *

v0.50.0

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by rjhancock** [comment] 2024-09-20 14:59
The scripts themselves are already marked executable and are written with LF line endings within the various repositories. If they are being changed at any point, it would be during the build script phase.

However, during testing, they did work from the extracted packages by myself and others from the QA and development teams.

**Comment by Algebro7** [comment] 2024-09-20 15:24
The scripts in `bin` are in fact executable and written with the correct line endings. The ones in the root directory (`MekHQ.sh`, for example) are not.

**Comment by rjhancock** [comment] 2024-09-20 15:26
As I said, the ones in the repository ARE set correctly so this is happening during the build scripts portion.

Which is odd as testing at the time did show they were working. It is entirely possible the issue may be something unrelated to both and the way the releases are packaged for release outside of Actions.

**Comment by rjhancock** [comment] 2024-09-21 10:17
Closing as duplicate of #4772.

**Closed by rjhancock** 2024-09-21 10:17 UTC
