### ISSUE TITLE
userdata folder use is unclear

### ISSUE THREAD

**Issue by mjbroekman** [MegaMek/mekhq#3176] opened 2022-03-19 12:47 UTC
### Environment
MekHQ 0.49.7
OS: All

### Description
The userdata folder in 0.49.7 contains a readme with the version 0.49.2 which states:
```This is a list of all supported files in the userdata directory. Any file not listed here has not been checked to ensure it works properly, and thus the userdata folder is not supported for them. Directories are especially likely to not work if you place them here.```

However, #1477 seems to imply that custom mech files should be able to go in there. (After testing it, It appears that custom mech files _are_ loaded from there.)

Are all of the directories mentioned in #1477 supported? If so, can the readme be updated to reflect it.

Can the default save location for new mech designs be updated to use the userdata folder rather than `mekhq-<version>/data/mechfile/customs/<campaign>`?

**Comment by Windchild292** [comment] 2022-03-19 14:58
#1477 was closed as it duplicates https://github.com/MegaMek/megamek/issues/1050. The README is correct for supported folders outside of campaign presets, which are also supported.

Closing as a duplicate of https://github.com/MegaMek/megamek/issues/1050

**Closed by Windchild292** 2022-03-19 14:58 UTC
