### ISSUE TITLE
GEnerated scenario with thin atmosphere and fog

### ISSUE THREAD

**Issue by Tecmes** [MegaMek/mekhq#2455] opened 2021-03-07 21:04 UTC
According to TO57 (Light Fog section and others). this is not possible. 
I know this might be an AtB issue, not MekHQ, but I'm not sure.

**Comment by Tecmes** [comment] 2021-03-07 21:40
(this is the same, asyou may guess, with other incompatible conditions, such as snowfall+thin)

**Comment by BullseyeSmith** [comment] 2021-03-10 15:46
This reminds me of a Base Attack (Defender) battle I once had.  The weather said clear.  I had to keep all the civilians and allied vees & turrets alive.  Got all ready and launched the scenario.  First round everything (except mechs) dies.  I went back and looked again.  Weather: Clear. Wind: F4 Hurricane.  I just, I couldn't, I still can't.  GM deleted the scenario and pretended it never happened.

**Comment by Windchild292** [comment] 2021-05-04 19:53
Working as intended, AtB rules allow this.

**Comment by HammerGS** [comment] 2021-05-04 20:26
I disagree, with closing this. AtB rules especially for things like weather and planet conditions shouldn't be superseded by AtB.

**Comment by NickAragua** [comment] 2021-05-04 20:36
The specific combinations of "thin atmosphere" and some wind conditions is actually prohibited, so we should review that logic when we re-visit the weather tables for StratCon.

**Closed** 2023-04-19 03:39 UTC
Labels: Enhancement, StratCon
