### ISSUE TITLE
CamOps Rep is very good for a not-so-good unit

### ISSUE THREAD

**Issue by repligator** [MegaMek/mekhq#4645] opened 2024-08-15 22:21 UTC
### Environment
Java 17
Linux
Master (Latest PR https://github.com/MegaMek/mekhq/commit/fbb0a02e62541aa66b146055a847e38bad50f86e)

### Description
Fairly new save with a unit that is not doing very well. 1 mission completed (failed), and most of the way through failing the second one. I don't think I've ever had a unit with more than 5 reputation before (and that includes ones that fought successfully from the Clan Invasion to the Dark Ages). But somehow this one has 13?

![Screenshot_20240815_181804](https://github.com/user-attachments/assets/7e56b13b-ed5f-436b-9706-46214b399241)

### Files
[Yakuza3830391101.cpnx.gz](https://github.com/user-attachments/files/16630812/Yakuza3830391101.cpnx.gz)

**Comment by IllianiCBT** [comment] 2024-08-15 22:40
Based on those numbers, that looks like it’s working as intended and is following RAW. However, if you’ve had a failed Mission *and* it’s been at least one Monday since then that should be reflected in the score, so I’ll need to investigate that

**Comment by IllianiCBT** [comment] 2024-08-15 23:16
Closing as resolved

**Closed by IllianiCBT** 2024-08-15 23:16 UTC
Labels: Bug
