### ISSUE TITLE
MHQ Unable to Resolve Space Battle with Fighter Squadrons

### ISSUE THREAD

**Issue by mkerensky** [MegaMek/mekhq#170] opened 2016-09-26 13:47 UTC
MHQ doesn't seem to be able to handle importing and converting units from a battle where fighter squadrons were used.   

The attached zip contains the campaign file, final autosave from MM, MHQ log that throws an NPE and custom units for the campaign file. I've had this happen twice using different sets of units and the same versions of the programs. 
[Squadron Import Files.zip](https://github.com/MegaMek/mekhq/files/493219/Squadron.Import.Files.zip)

**Comment by pheonixstorm** [comment] 2016-09-27 00:43
I think I reported this in the sf.net bug tracker a few years ago.

**Comment by mkerensky** [comment] 2016-09-27 12:18
I would guess that part of it has to do with squadron damage assignment. Each fighter seems to take most of its damage to one hit location, which greatly exceeds the available armor there in many cases.

**Comment by Dylan-M** [comment] 2016-09-27 12:28
This is definitely reported on SF tracker somewhere, it's also been a known issue for a long time. It's simply a matter of resources. Squadrons aren't used very often among my play group, so I don't have a huge desire to do the code. I feel my time (resources) are better spent elsewhere.

**Comment by Akjosch** [comment] 2016-09-27 16:35
The problem is that `FighterSquadron` relies on the `Game` instance being actually fully configured to return the actual `Aero` instances "inside" it, instead of storing them as object instances itself. When asking for anything which boils down to one of those (like the engine type ...), having a semi-initialised `Game` instance (as in what MHQ provides) just causes NPEs.

The main conceptual problem here is that asking a fighter squadron for its engine type (what MHQ does and what eventually causes the error) is about as meaningless as asking a 'Mech lance for *its* engine type. The correct answer is "multiple of them, one for each individual unit inside the squadron" (fighters inside a squadron need not be of the same type, see SO p. 27).

So, the fix needs to happen on two sides: On MM's side, `FighterSquadron` needs to stop implementing methods it has no business implementing, in particular `getEngine()`. On MHQ's side, fighter squadrons need to stop being treated like a single unit.

The first one is easy ...

**Comment by Akjosch** [comment] 2016-09-27 17:00
Update: The specific problem (asking a fighter squadron for its engine) was easy enough, but now it crashes when asking for its *weight*. It means the class needs a redesign, to not use a `Game` instance but hold its constituent units directly.

**Comment by Akjosch** [comment] 2016-09-27 20:46
Hmm. Tried to load the campaign file on my other computer and ...

![](http://i.imgur.com/rQ0c8lx.png)

... looks like I'm missing something.

**Comment by mkerensky** [comment] 2016-09-27 20:57
[Customs.zip](https://github.com/MegaMek/mekhq/files/496622/Customs.zip)

You are missing the attached file. Sorry about that.

**Comment by Akjosch** [comment] 2016-09-30 12:47
Should be fixed in the next release (or automated build).

**Closed by Akjosch** 2016-09-30 12:47 UTC
