### ISSUE TITLE
[0.45.0 : Bug] Parts Acquisition No Longer Show In Transit

### ISSUE THREAD

**Issue by SirMegaV** [MegaMek/mekhq#883] opened 2018-08-20 10:53 UTC
### Environment

0.45.0

### Description

Using Parts Acquisition in Repair Bay:

1. After a successful body parts order, it updates on "OmniPod" instead of "in transit". See image.

1. After a successful weapon parts order, it doesn't update anything. See image.

Savegame attached.

### Files

![image](https://user-images.githubusercontent.com/17064665/44336349-ca952380-a4a9-11e8-8710-1bd1b230e9fa.png)

![image](https://user-images.githubusercontent.com/17064665/44336490-32e40500-a4aa-11e8-9c70-2077a2eaee6b.png)

[PartsAcquisitionNoLongerShowInTransit.zip](https://github.com/MegaMek/mekhq/files/2302079/PartsAcquisitionNoLongerShowInTransit.zip)

**Comment by sixlettervariables** [comment] 2018-08-20 12:05
Dupe of #855

**Closed by sixlettervariables** 2018-08-20 12:05 UTC
