### ISSUE TITLE
[49.7] NPEs on Intersteller Map with Custom systems and factions even on new campaign

### ISSUE THREAD

**Issue by PhoenyxCullen** [MegaMek/mekhq#3463] opened 2022-09-23 06:40 UTC
### Enviroment
MEKHQ v.0.49.7

$ java -version
openjdk version "11.0.16.1" 2022-08-12
OpenJDK Runtime Environment (build 11.0.16.1+1)
OpenJDK 64-Bit Server VM (build 11.0.16.1+1, mixed mode)
$ lsb_release -a
LSB Version:	n/a
Distributor ID:	ManjaroLinux
Description:	Manjaro Linux
Release:	22.0.0
Codename:	Sikaris

### Description
I have added to the following files in data/universe section of code: systems, system_events, factions, faction_hints. Files will be attached to this report. This is happening on both my and friend's computer. While I'm on Linux, he is on Windows 10. This is in MekHQ 0.49.7. We have the same version of java (11.0.16.1 OpenJDK). 

### Files
[49.7InterstellerMapNPEIssue.zip](https://github.com/MegaMek/mekhq/files/9631170/49.7InterstellerMapNPEIssue.zip)
[mekhq.log](https://github.com/MegaMek/mekhq/files/9631187/mekhq.log)

**Comment by PhoenyxCullen** [comment] 2022-09-23 06:43
The campaign isn't posted in here as it still happens even in a new campaign.

**Comment by PhoenyxCullen** [comment] 2022-09-23 06:44
Don't know if I made a coding/xml error.

**Comment by Windchild292** [comment] 2022-09-30 03:18
```
23:19:02,423 ERROR [mekhq.MekHQ] {AWT-EventQueue-0}
mekhq.MekHQ.lambda$main$0(MekHQ.java:269) - Uncaught Exception Detected
java.lang.NullPointerException
	at mekhq.gui.InterstellarMapPanel$6.paintComponent(InterstellarMapPanel.java:660)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1074)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:907)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1083)
	at java.desktop/javax.swing.JLayeredPane.paint(JLayeredPane.java:590)
	at java.desktop/javax.swing.JComponent.paintChildren(JComponent.java:907)
	at java.desktop/javax.swing.JComponent.paint(JComponent.java:1083)
	at java.desktop/javax.swing.JComponent.paintToOffscreen(JComponent.java:5255)
```

**Comment by Windchild292** [comment] 2022-09-30 03:47
```
for (Faction faction : factions) {
    if (capitals.get(faction).equals(system.getId())) {
```

Data issue with your custom data, either to do with a faction not existing or (more likely) specifying a faction that doesn't exist. I'm closing this as a user issue, and have opened #3468, #3470, and #3471 to properly validate that data upon load to prevent this issue in future.

**Comment by PhoenyxCullen** [comment] 2022-09-30 03:48
I'm asking for help on this. Faction is in there. Down at the bottom. CHD and DWA are two new factions, on the same planet.

**Closed by Windchild292** 2022-09-30 03:47 UTC
Labels: Bug, Planets

**Comment by PhoenyxCullen** [comment] 2022-09-30 03:49
How do I fix my data?

**Comment by PhoenyxCullen** [comment] 2022-09-30 04:07
<faction>
        <shortname>CHD</shortname>
        <fullname>Cullenholme Dynasty</fullname>
        <startingPlanet>Dwarbithia</startingPlanet>
        <colorRGB>2,55,71</colorRGB>
        <tags>is,minor,merc,playable</tags>
        <start>2779</start>
    </faction>
    <faction>
        <shortname>DWA</shortname>
        <fullname>Dwarbithia Alliance</fullname>
        <startingPlanet>Dwarbithia</startingPlanet>
        <colorRGB>34,89,3</colorRGB>
        <tags>is,minor,merc,playable</tags>
        <start>2779</start>
    </faction>

**Comment by PhoenyxCullen** [comment] 2022-09-30 04:08
<system>
    <id>Dwarbithian</id>
    <event>
      <date>3033-03-15</date>
      <nadirCharge source="noncanon">false</nadirCharge>
      <zenithCharge source="noncanon">false</zenithCharge>
    </event>
    <planet>
      <sysPos>3</sysPos>
      <event>
        <date>3033-03-15</date>
        <faction source="noncanon">PIR</faction>
        <hpg source="noncanon">X</hpg>
        <population source="noncanon">500000</population>
        <socioIndustrial source="noncanon">F-F-A-F-F</socioIndustrial>
      </event>
      <event>
        <date>3049-08-12</date>
        <faction source="noncanon">DWA,CHD</faction>
        <hpg source="noncanon">X</hpg>
        <population source="noncanon">9600000</population>
        <socioIndustrial source="noncanon">C-C-A-C-C</socioIndustrial>
      </event>
    </planet>
  </system>

**Comment by PhoenyxCullen** [comment] 2022-09-30 04:09
<system>
    <id>Dwarbithian</id>
    <event>
      <date>3033-03-15</date>
      <nadirCharge source="noncanon">false</nadirCharge>
      <zenithCharge source="noncanon">false</zenithCharge>
    </event>
    <planet>
      <sysPos>3</sysPos>
      <event>
        <date>3033-03-15</date>
        <faction source="noncanon">PIR</faction>
        <hpg source="noncanon">X</hpg>
        <population source="noncanon">500000</population>
        <socioIndustrial source="noncanon">F-F-A-F-F</socioIndustrial>
      </event>
      <event>
        <date>3049-08-12</date>
        <faction source="noncanon">DWA,CHD</faction>
        <hpg source="noncanon">X</hpg>
        <population source="noncanon">9600000</population>
        <socioIndustrial source="noncanon">C-C-A-C-C</socioIndustrial>
      </event>
    </planet>
  </system>

**Comment by HammerGS** [comment] 2022-09-30 14:51
> How do I fix my data?

At this time, we just don't have the dev resources to trouble shoot an error that is caused by player editing of data. Windchild has provided as much guidance as we can at this time. 

> ```
> for (Faction faction : factions) {
>     if (capitals.get(faction).equals(system.getId())) {
> ```
> 
> Data issue with your custom data, either to do with a faction not existing or (more likely) specifying a faction that doesn't exist. I'm closing this as a user issue, and have opened #3468, #3470, and #3471 to properly validate that data upon load to prevent this issue in future.


I would recommend going back to the base data, then adding things in very small sections to test.

**Comment by PhoenyxCullen** [comment] 2022-09-30 16:23
Troubleshooting a PC having power issues, eh? Ok. :)
