### ISSUE TITLE
[0.43.4] NPE On Loading Campaign

### ISSUE THREAD

**Issue by Flibjib** [MegaMek/mekhq#512] opened 2017-10-29 03:13 UTC
Not sure what's causing this but I've made a few changes:

Enabled Clan Wolverine as a playable faction
Removed the Reaved tags from the Clan Wolverine Bloodnames
Changed the ownership of a few planets

I have a few customs, but nothing too crazy. Dropped an LRM from a Maxim and swapped it for a little more infantry space, shortly before this started being an issue.

[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/1424761/mekhqlog.txt)
[Minnesota Tribe28320105.cpnx.zip](https://github.com/MegaMek/mekhq/files/1424762/Minnesota.Tribe28320105.cpnx.zip)

**Comment by HammerGS** [comment] 2017-10-29 03:19
java.lang.NullPointerException
	at mekhq.campaign.universe.RandomFactionGenerator.addBorderEnemy(RandomFactionGenerator.java:531)
	at mekhq.campaign.universe.RandomFactionGenerator.updateBorders(RandomFactionGenerator.java:502)
	at mekhq.campaign.universe.RandomFactionGenerator.updateTables(RandomFactionGenerator.java:454)
	at mekhq.campaign.Campaign.restore(Campaign.java:3030)
	at mekhq.gui.dialog.DataLoadingDialog$Task.doInBackground(DataLoadingDialog.java:194)
	at mekhq.gui.dialog.DataLoadingDialog$Task.doInBackground(DataLoadingDialog.java:116)

**Comment by neoancient** [comment] 2017-10-29 19:32
Duplicate of #490

**Closed by neoancient** 2017-10-29 19:32 UTC
Labels: bug, duplicate
