### ISSUE TITLE
Mass Repair/Salvage Window doesn't respect Monitor Size

### ISSUE THREAD

**Issue by scJazz2** [MegaMek/mekhq#521] opened 2017-11-13 16:24 UTC
The Window should appear with a maximum height of whatever display it is being shown on.

0.43.5 Beta Nov11

![massrepair window](https://user-images.githubusercontent.com/16738384/32736305-1c3d49aa-c865-11e7-98d1-fcd226a5cb9b.jpg)

**Comment by sixlettervariables** [comment] 2020-10-02 18:29
@Windchild292 while you're working on MRMS could you take a look at perhaps a scrollbar for the options area?

**Comment by Windchild292** [comment] 2020-10-02 18:30
Already in my plan.

**Comment by Windchild292** [comment] 2020-10-09 15:27
The baseline on this is not a bug but rather considered a standard in Java. However, I will be adding a scrollbar.

**Comment by Windchild292** [comment] 2020-10-09 15:30
The dialog already has a scrollbar and works fine on tiny screens, closing as this is just a standard for Java.

**Closed by Windchild292** 2020-10-09 15:30 UTC
Labels: Mass Repair/Mass Salvage, bug
