### ISSUE TITLE
[Feature Request] More Supported Folders in "userdata" Folder

### ISSUE THREAD

**Issue by SirMegaV** [MegaMek/mekhq#854] opened 2018-08-07 02:34 UTC
Currently the following folders cannot be used in the "userdata" folder.

1. data/boards
2. data/images/force
3. data/images/portraits
4. data/rat

**Comment by Windchild292** [comment] 2020-03-15 22:16
This will be implemented as part of implementing #1477, and is covered there. This can therefore be closed.

**Comment by Windchild292** [comment] 2020-08-21 02:49
Duplicate of #1477

**Closed by Windchild292** 2020-08-21 02:49 UTC
Labels: Hydra, enhancement
