### ISSUE TITLE
BA Repairs take incorrect equipment

### ISSUE THREAD

**Issue by Saberuneko** [MegaMek/mekhq#1720] opened 2020-05-02 16:22 UTC
### Environment
What version of MekHQ does your issue apply to? 0.47.5
What operating system are you using?  Windows, Mac, or Linux? Windows 10
What java version are you using? 1.8.0_251

### Description
Whenever I try to replace a destroyed battle armor, all BA related equipment in the warehouse is applied into it and consumed. Resulting in units with 200 armor points, etc. See attached screenshot

### Files
Please see attachments, no customized units or files, vanilla MekHQ

![ScreenShot00732](https://user-images.githubusercontent.com/4760050/80869613-c1f67800-8ca1-11ea-901b-9c763ae821b2.png)

[Skull Hunter Hetairoi30500307.zip](https://github.com/MegaMek/mekhq/files/4568184/Skull.Hunter.Hetairoi30500307.zip)

**Comment by Saberuneko** [comment] 2020-05-04 00:11
Tested with 0.47.6, seems like certain items stopped being "absorbed" into the unit such as Armor. Still, some others still do.

For example, trying to replace one of the missing battle armor units still absorbs all BAs in the Warehouse.

**Comment by sixlettervariables** [comment] 2020-12-11 20:00
I'm not able to reproduce this on the dev snapshot, but still trying.

**Comment by sixlettervariables** [comment] 2020-12-11 20:26
If I could get a CPNX in the correct state, with steps to reproduce from the exact state that would be great. I've tried all manner of things with the given CPNX and could not get it to mess up the parts.

**Comment by Windchild292** [comment] 2021-09-29 19:42
Closing as unable to recreate and no further information provided in nearly a year.

**Closed by Windchild292** 2021-09-29 19:42 UTC
Labels: Bug, Needs More Info, Needs Investigation
