### ISSUE TITLE
[0.49.20] Bug: BA c-bill cost calculation errors/mismatches

### ISSUE THREAD

**Issue by Gribbly1** [MegaMek/mekhq#4473] opened 2024-07-23 12:35 UTC
Bundled Megamek with MekHQ 0.49.20
Windows 10, Java Version: 11.0.13

Tech Manual p281 BATTLE ARMOR STRUCTURAL COSTS AND AVAILABILITY, p285 for final unit cost.

BA financial values are inconsistent across the purchase unit menu, procurement info pane, Hangar and financials tab.

[BAtest.cpnx.gz](https://github.com/user-attachments/files/16348710/BAtest.cpnx.gz)

Note: parts value set to 1 for clarity.

![longinus](https://github.com/user-attachments/assets/d21720bd-046d-4830-8d25-24b965816d08)

![long2](https://github.com/user-attachments/assets/0bb7dd5d-7686-4452-99da-f61496f378c4)

![long3](https://github.com/user-attachments/assets/6c4807f1-e77d-4bc4-b2ef-254f9e87f965)

![long4](https://github.com/user-attachments/assets/b1372058-d784-4dd3-b00d-1466edf1d582)

**MML dry calc for comparison:**

![image](https://github.com/user-attachments/assets/5c7b6094-114f-4181-9aa2-dae68d650d0c)

**Comment by repligator** [comment] 2024-07-23 14:12
Math time:

Cost With Ammo=2548320
Dry Cost=2440320
Mystery Cost=1948320

2548320-1948320=600000

600000= the cost to train 1 Longinus Battle Armor Pilot multiplied by 4

MHQ is charging you 600,000 C-Bills less because you are only buying the suits, you have to supply your own pilots.

**Comment by Gribbly1** [comment] 2024-07-23 15:33
Math time:
1,948,320 does not equal 6,195,280

**Comment by repligator** [comment] 2024-07-23 16:54
> Math time: 1,948,320 does not equal 6,195,280

Apologies if I sounded glib earlier, that was not my intention.
After further investigation, it appears MHQ is using the `INF_JUMP` `priceMultiplier` (2.6) on these BA's. 
2382800(the base cost of the parts according to `partsValue`)x2.6=6195280

This can be confirmed by setting breakpoints on lines 963 and 964 of `megamek/common/Infantry.java`

**Comment by Gribbly1** [comment] 2024-07-23 17:34
No worries.

Is there a way to see exactly what partsValue is made up from? It doesn't seem to correspond to the dry cost or purchase cost.

Also the ammo cost should be negligible for one shot SRM2's, not the full 27k*4 for 45 shots per suit.

**Comment by repligator** [comment] 2024-07-23 17:52
> Is there a way to see exactly what partsValue is made up from? It doesn't seem to correspond to the dry cost or purchase cost.

These are the 29 parts that are being used for the calculation.
![Screenshot_20240723_134422](https://github.com/user-attachments/assets/9b8e05fc-bec8-4db2-87fd-c45da8f42491)

The only way I know of to generate this list (in human readable format) is to run MHQ through an IDE (for example IDEA) and set a breakpoint.

**Comment by repligator** [comment] 2024-07-24 18:11
See also #1795

**Comment by IllianiCBT** [comment] 2024-08-08 00:09
Closing as resolved

**Closed by IllianiCBT** 2024-08-08 00:09 UTC
Labels: Bug
