### ISSUE TITLE
Failure to properly load mul file after mission

### ISSUE THREAD

**Issue by bczretribution** [MegaMek/mekhq#569] opened 2017-12-21 07:22 UTC
After completing a mission in Megamek when handed back to Mekhq, Mekhq askes about battlefield control, then the after battle report screen fails to open.  Trying to resolve manually and load the independently save mul from the mission has similar results.  resolving manually and loading any other mul including the salvage mul works fine.  The issue seems to be with the writing of the full report mul, both automated and manual from Megamek.
[megameklog.txt](https://github.com/MegaMek/mekhq/files/1578269/megameklog.txt)
[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/1578270/mekhqlog.txt)

https://drive.google.com/file/d/1v5X0XpP6u5rcNRGoYd3LSOuJ0cmhNc6s/view?usp=sharing
https://drive.google.com/file/d/1z0zGlMQQK3x33lZ7b5UHRXCbPCmOjv8h/view?usp=sharing
https://drive.google.com/file/d/1N0BharBudGh5cKE00kYXvG_iM_ysdfyY/view?usp=sharing

**Comment by molemanBT** [comment] 2017-12-21 11:25
Having same issue

**Comment by bczretribution** [comment] 2017-12-21 17:51
new information.
Similar to issue #566 but if I try to resolve manually and do not load a mul, but instead manually set damage and survival for my units I can progress through the after-action fine. However, once I reach the final page and click finish, nothing happens, the window does not close and the battle does not resolve, I can just keep clicking finish to no noticeable effect.

**Comment by HammerGS** [comment] 2017-12-21 17:58
Duplicate of https://github.com/MegaMek/mekhq/issues/566

**Closed by HammerGS** 2017-12-21 17:58 UTC
Labels: duplicate
