### ISSUE TITLE
[49.1 #390] Own units status not reported to MekHQ

### ISSUE THREAD

**Issue by Tecmes** [MegaMek/mekhq#2598] opened 2021-05-10 00:34 UTC
At the end of a scenario, the status of the OpFor and kills etc. was correctly returned, but all my units were reported as Undamaged despite some serious damage). However, once back from the deployement, they had the correct damage on them when landing on the repair bay...
(So sorry the title is not quite correct, but I can't quite change it)

 Here are some errors that appeared in the mhq log (the MM log seemed fine).

[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/6448710/mekhqlog.txt)

**Comment by Tecmes** [comment] 2021-05-10 00:47
Now that's crazy fast!

**Comment by Windchild292** [comment] 2021-05-10 01:14
Fixes for both NPEs are now open, neither are the cause of this.

**Comment by Tecmes** [comment] 2021-05-10 13:14
Then I guess this issue can be closed. If it reappears I'll try and post a  more detailed feedback material.

**Comment by Windchild292** [comment] 2021-05-25 23:57
Closing as further testing couldn't recreate. If you can do so, please post with more detailed feedback.

**Closed by Windchild292** 2021-05-25 23:57 UTC
Labels: StratCon, bug
