### ISSUE TITLE
Export Whole Personnel vs Single Personnel Asset Mismatch (Aggression, Ambition, Greed, Social, Intelligence)

### ISSUE THREAD

**Issue by johnboyjjb** [MegaMek/mekhq#4994] opened 2024-10-05 20:50 UTC
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the RFE to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] Does this conform with our Content Policy linked above?
- [X] I've searched the GitHub tracker and haven't found a similar feature request listed

### RFE Details *

This is an improvement to an existing feature

### Brief Description *

A single exported personnel file doesn't include the Aggression, Ambition, Greed, Social, or Intelligence attributes. When Loyalty was added it showed up in both reports but these attributes do not.

### MekHQ Suite Version *

0.50.0

### Final Checklist

- [X] I've checked to make sure that this RFE has not already been filed
- [X] I am requesting implementation of only one relevant set of features in this ticket for clarity and focus

**Comment by IllianiCBT** [comment] 2024-10-20 00:02
It's late and my brain is clearly lagging, but I'm struggling to know what you mean by 'single exported personnel file' -- is anyone able to point me in the right direction?

**Comment by johnboyjjb** [comment] 2024-10-20 03:16
![image](https://github.com/user-attachments/assets/c5b59bb9-3031-48a1-a51c-4e85667ed50f)
[SingleExportedPersonnel.prsx.csv](https://github.com/user-attachments/files/17448307/SingleExportedPersonnel.prsx.csv)

The prsx file isn't a csv but I cannot upload a PRSX file without compressing it or changing the format so I changed the extension.

**Comment by IllianiCBT** [comment] 2024-10-20 03:19
I’ll be honest, didn’t know that option existed, so the inclusion of Loyalty is entirely by accident.

I’ll see about getting the personality traits added tomorrow.

**Comment by johnboyjjb** [comment] 2024-10-20 14:01
![Screenshot 2024-10-19 201435](https://github.com/user-attachments/assets/d53929c2-dbf1-4f8e-aba9-0da24ce5eff9)

**Comment by IllianiCBT** [comment] 2024-10-20 21:39
I've confirmed personality traits _are_ exported using that option, however they won't be included if the character does not have a trait of that type. That's because this option uses the same exporter method as normal saving, so we exclude default values to keep save files at a reasonable length.

Closing as working as intended.

**Closed by IllianiCBT** 2024-10-20 21:39 UTC
Labels: (RFE) Enhancement, Personnel
