### ISSUE TITLE
Repair tab and other multiple return glitches

### ISSUE THREAD

**Issue by bczretribution** [MegaMek/mekhq#1018] opened 2018-12-28 02:20 UTC
It would seem that many of the issues that had been resolved by 44.0 stable have reemerged, I am wondering if someone merged an update with an out of date source, overwriting the fixes.  

The first being that techs that are assigned 480m maintenance still show up as having available work time, which allows the auto to assign them to tasks (see issue #895 ).  

Techs that do have time free when assigned to multi-day tasks sometimes do not continue working after the first day.  In such cases, you can sometimes manually tell that tech to continue work on that task but only that tech as the task is still considered assigned to them.  (issue ??)

After refits, some mechs will have repair tab jobs to refill ammo bins that when completed consume ammo but do not go away (see issue #648 )

The auto assign repair button will sometimes leave repair tasks unassigned even though they meet all criteria (issue ??).

Sometimes after a part is repaired successfully the unit is not updated i.e. after a leg is replaced the mech still does not have a leg but also does not have the option to replace the leg anymore (issue??)

mechs that lost pilots in prior missions won't deploy in new missions (issue #655 )

mechs destroyed by ammo detonation do not show pilots as possible prisoners (issue #531 )

when advancing day, astech pool minutes go to 0 sometimes (issue ??)

My hope is that most of these might be able to be solved by looking back at the merges that fixed the issues before and repasting some code back in.  However, in the likely event that it won't be that easy, I will update this ticket with saves as I have them.  I will also continue to search github to find links to the rest of the issues.

**Comment by bczretribution** [comment] 2018-12-28 03:39
everything I mentioned is stuff I have run into in 45.2, the linked issue #s are all pre 44.0

**Comment by molemanBT** [comment] 2019-01-04 06:47
I've had most of these in a new 44.2 campaign

**Comment by molemanBT** [comment] 2019-01-04 06:49
Specifically 1st, second, 4th and last

**Comment by molemanBT** [comment] 2019-01-05 22:54
Oops, yes sorr

**Comment by sixlettervariables** [comment] 2019-01-06 18:55
Issue 1 is not really a bug, more observed behavior. You are not charged time for units which do not require maintenance. This can cause somebody with 480 minutes of maintenance to have "left over" time, and still show up in the list. They truly would be eligible to do work *today*, but maybe not if left to work overnight. Perhaps a visual indicator could help with that.

Issue 2 I believe I ameliorated in a recent PR #1016.

Issue 4 I believe I fixed in PR #1039.

I'll look into the Astech pool minutes issue.

**Comment by bczretribution** [comment] 2019-01-07 01:12
Under what conditions do units not require maintenance? if assigned 480 min of maintenance I thought that that was a daily occurrence.  

I've tracked individual techs who have unit assignments "8 units (480 minutes)" maintaining a 135 min left status every day for weeks, and have even had them do short jobs (20-30 min) and the next day they are back at 135.

thank you for your patches for these, and sorry I haven't posted any more info or saves, haven't had much time to play, hoping that will be better this week.

**Comment by sixlettervariables** [comment] 2019-01-07 16:23
I'd love to see a save file where they have 8 units and 480 minutes and have extra time. I'm unable to reproduce that locally.

**Comment by bczretribution** [comment] 2019-01-08 01:38
got to play some today and thats the first issue ive been able to cap, so as requested here it is.

in the following three images you can see that mr. takahashi has 480 min maintenance assigned, that he is listed as having 135 minutes in the repair tab, and in fact, if I try to do a refit he can be found in that list as having 135/0 minutes (you can use the refit list to find that there are several other techs with the same issue).  
The save file will be uploaded bellow, but the following two actions should be repeatable from this point in the save; 1. assigning him a repair that is <135 min and advancing the day he will refill to 135 min, 2.  assigning him a repair >135 min he will make 135 min worth of progress but when advancing days no further progress will be made (as expected).

![personnel](https://user-images.githubusercontent.com/34722287/50804357-8ae5a180-12bb-11e9-9764-a664791d38d0.jpg)
![refit](https://user-images.githubusercontent.com/34722287/50804358-8ae5a180-12bb-11e9-8a41-24b26d1c5ce8.jpg)
![repair bay](https://user-images.githubusercontent.com/34722287/50804359-8ae5a180-12bb-11e9-8346-bad0bed3bf90.jpg)

[glitch.zip](https://github.com/MegaMek/mekhq/files/2734886/glitch.zip)

**Comment by sixlettervariables** [comment] 2019-01-08 13:59
Interesting. Mr. Takahashi is listed as maintaining 8 units but only actually maintains 5 (if you jump into the hangar). Some removed units must not have been removed from his tech list.

**Comment by bczretribution** [comment] 2019-01-09 04:48
managed to get a save game for item 7- units ammo detonated dont have pilots in the capture list.  the attached zip contains the campaign just before mission start, a MMK save just after the first ammo dets, jpgs of the ammo dets and capture screen, and the mission end mul.  you will see there was a crusader, firestarter and a few other mechs that blew up, ejected safely but their pilots disappeared come post battle.

[glitch (3).zip](https://github.com/MegaMek/mekhq/files/2739399/glitch.3.zip)

**Comment by sixlettervariables** [comment] 2019-01-09 13:54
To fix this issue you'll need to manually edit your CPNX. Search for `<person>` and then find the `<name>` tag which matches the tech. Inside you'll see a `<techUnitIds>` tag with `<id>...</id>` tags corresponding to the units they maintain. You'll need to remove the following ID's per person (just delete the entire line):

Cynthia Rhyne:
- `<id>a31f4191-7640-478a-b7d1-0f303aa4186a</id>`
- `<id>13baf686-279d-4d59-88d5-84c1928a6294</id>`
- `<id>b70cdec0-9c23-4908-9a20-2530276ce221</id>`
- `<id>06f47e67-9f7a-4001-93eb-505908753484</id>`

Corneles Ramírez:
- `<id>16b20e81-e4d4-4798-a3ac-887b431cd02f</id>`

Kiyotaka Takahashi:
- `<id>cc9a88a6-1e46-42ca-b174-2cf8ca1719cc</id>`
- `<id>3c1d779a-d0da-48d6-a279-2160e8c405df</id>`
- `<id>b4af4dd6-8b45-4f70-afd9-b278b4bcc810</id>`

Katrene George:
- `<id>ed5e0290-7c93-4746-ac06-c292b590d774</id>`

**Comment by bczretribution** [comment] 2019-01-14 23:41
had the astech pool goes to 0 minutes when advancing day glitch

[glitch.zip](https://github.com/MegaMek/mekhq/files/2757489/glitch.zip)

**Comment by sixlettervariables** [comment] 2019-01-17 16:35
#1041 fixes the issues on campaign load for unit-tech mismatches.

**Comment by sixlettervariables** [comment] 2019-01-18 21:37
@bczretribution hrm, I can't recreate it, but certainly from the CPNX I see that the astech pool minutes are 0.
```
		<astechPoolMinutes>0</astechPoolMinutes>
		<astechPoolOvertime>149850</astechPoolOvertime>
```

**Comment by bczretribution** [comment] 2019-01-19 14:52
yea the only time I was ever able to recreate it was when I had just taken a save the day before it happened.  It seems that, if you can get a save the day before, it is consistent in happening on the afflicted day, but I've never been able to figure out what the trigger is.  Somewhere here on github is an upload of that save but that was from a much older version.

At some point as I keep playing I'll be lucky enough to again get a save the day before and will submit it for you

**Comment by sixlettervariables** [comment] 2019-06-25 15:48
I'm going to close this for now as #1041 fixed the primary issue. If you encounter the 0 astech minutes again open a new issue. Thanks!

**Closed by sixlettervariables** 2019-06-25 15:48 UTC
