### ISSUE TITLE
12/13 logistics 0.50.02 snapshot - receiving 'contract breach' nag for not deploying, no missions list as required deployments, liason command. Also showing 'ghost mission', not visible on stratcon panes

### ISSUE THREAD

**Issue by OrbMonky** [MegaMek/mekhq#5376] opened 2024-12-15 03:18 UTC
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Medium (Gameplay Limitation): Non-core functionality is impaired, providing a suboptimal but playable experience.

### Brief Description *

Attempting to bypass some overwhelming deployments, like you do on a no salvage contract, but there is no indicator of any requirement to deploy on them and when attempting to deploy, I am receiving the 'will cause a minor breach' nag.

Further, it lists three active scenarios, but only 2 active scenarios are present to deploy to in Stratcon pane.
Track 3 and its listed scenario;
![image](https://github.com/user-attachments/assets/c112c709-95c4-49b2-aad9-823da751e67d)
![image](https://github.com/user-attachments/assets/8f0249f6-c9dd-4724-b862-51c438b736d9)

Track 4 and its listed scenarios, the one Gamma Lance is deployed to has been completed, they are returning from deployment
![image](https://github.com/user-attachments/assets/50bd2c56-438b-448a-b358-3434d23bd6f3)
![image](https://github.com/user-attachments/assets/487cb5db-0447-45c3-93aa-6824f06665eb)
![image](https://github.com/user-attachments/assets/c07d56bb-3222-46da-bece-bb205f178811)

Track 5 and its visible objective - the industrial facility does not have a scenario listed currently
![image](https://github.com/user-attachments/assets/414f5fe2-e41d-4046-9618-d2aedaadfd03)

[logs.zip](https://github.com/user-attachments/files/18138743/logs.zip)
Campaign, prior day autosave, customs, log files included

### Operating System *

Windows 10

### Java Version *

17

### MekHQ Suite Version *

None

### Custom MekHQ Version

12/13 Logistics Overhaul '0.50.02-SNAPSHOT'

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by OrbMonky** [comment] 2024-12-15 03:30
correction - the ghost mission is not a thing, I had missed that gamma lance was deployed to one of the three missions, but the other issue is occurring

**Comment by IllianiCBT** [comment] 2024-12-15 03:37
Thank god…

That other issue is much easier to resolve. I’ll get it fixed tomorrow.

**Comment by IllianiCBT** [comment] 2024-12-16 22:00
Can you do me a favor, check your MekHQ nag settings and confirm you haven't got this nag disabled (ticked):

<img width="292" alt="image" src="https://github.com/user-attachments/assets/03642a48-92b6-4fcc-9624-d0875e69f55d" />

**Comment by OrbMonky** [comment] 2024-12-16 22:15
![image](https://github.com/user-attachments/assets/24b55387-c38c-4ff4-b6d5-9f732c477776)
here's what I see

**Comment by IllianiCBT** [comment] 2024-12-16 22:31
And you don't get the unresolved Stratton contacts nag when advancing day?

**Comment by OrbMonky** [comment] 2024-12-16 22:37
![image](https://github.com/user-attachments/assets/9f5074d7-7c41-40cc-842f-1745d167d2bd)
This is what I get when advancing on a mission day

**Comment by IllianiCBT** [comment] 2024-12-16 22:47
And what do you get if you don't have anyone deployed to the scenario?

**Comment by OrbMonky** [comment] 2024-12-16 22:55
![image](https://github.com/user-attachments/assets/116a8812-e158-4fe0-b171-63b2d36a433c)

**Comment by IllianiCBT** [comment] 2024-12-16 22:56
Ok, awesome. Everything is working as intended and the 'contract breach' mention has been addressed in an earlier PR.

Closing as resolved :)

**Closed by IllianiCBT** 2024-12-16 22:56 UTC
