### ISSUE TITLE
0.49.3 - Dropship Mechbay Door (x 1) on one dropship always shows as destroyed when save file is loaded

### ISSUE THREAD

**Issue by UlyssesSockdrawer** [MegaMek/mekhq#2878] opened 2021-09-16 21:34 UTC
### Environment
MHQ Version 0.49.3, MHQ combined download
OS: Win10
JR: Open JDK11

### Description
Campaign file and customs attached.

Each time the campaign save is loaded, one dropship (Union 2) has a single mechbay door load as destroyed. I have been fixing this by GM'ing in parts and GM completing the repair.

It is always the same dropship and always the same mechbay door.

Nothing is shown in the logs.

### Files
[Rickie's Roughriders30501219.cpnx.gz](https://github.com/MegaMek/mekhq/files/7181091/Rickie.s.Roughriders30501219.cpnx.gz)
[customs.zip](https://github.com/MegaMek/mekhq/files/7181093/customs.zip)

**Comment by HoneySkull** [comment] 2021-09-17 03:22
I was able to reproduce this issue on a blank campaign file with 1 Union class dropship in 0.49.3.

1.  Create a new campaign (in 3050 //not sure if that matters)
2.  GM add a new Union (2708) dropship.
3.  In the Hangar GM Edit damage and click a damage on the bay door.
4.  Go into the repair bay left click on the damaged bay door and scrap the part.
5.  Save the campaign file.

Now when you go back into the campaign file.  You can GM add part and repair the part and save the campaign... but when you reload the campaign the drop ship still thinks the bay part is scrapped.

I'm going to take a look at the code as I was in there recently to see if I can find what is going on.

**Comment by HoneySkull** [comment] 2021-09-17 03:26
A work-around for this until it is fixed may be to GM-remove the dropship from your campaign and then GM add a new one back and save.   (I would Unassigned the crew first, and then reassign them on the new dropship.)

**Comment by HoneySkull** [comment] 2021-09-17 03:30
@Windchild292  - I suspect this may get resolved with #2877 (Part I/O using MegaMekXMLUtil)  Maybe scrapped parts are not de-serializing correctly?

**Comment by HoneySkull** [comment] 2021-09-18 03:06
It appears that when a bay door on the union is scrapped and then repaired, the repaired door is added to the unit's part list, but the parent child relationship is not maintained.  (The Bay only referenced on child bay door, and an orphan bay door is added to the units `Part` list but has a null/0 parent id which doesn't get stored to save file.  

I'm guessing then when the unit is loaded from the file, it appears to be missing the bay door because the child / parent relationship is not restored on the repair.  

i.e. Each time you repair and save the file, an additional orphaned bay door is added to the dropship part dope.

### Missing Bay Door ###
![missingBayDoor](https://user-images.githubusercontent.com/83041327/133870223-bf209dcc-56b4-4cb8-8e43-5a9757b61b48.png)


### Orphan Bay Doors ###
After fixing and saving three times after having a scrapped bay door, three orphan doors appear in the dropship's part list.  //Notice: There is no parent tag as the parent ID on that part object was 0 in memory before being saved.  The issue isn't with the de-serialization, but with linking parent/child relationship on the repair.

![orphanBayDoors](https://user-images.githubusercontent.com/83041327/133870249-c6abad86-40aa-4a63-95e0-79243505c338.png)

### Simple Sample File ###
File is a sample from 0.49.3 but I was able to reproduce in 0.48.0 as well.

[Broken Dropship30500106.cpnx.gz](https://github.com/MegaMek/mekhq/files/7189093/Broken.Dropship30500106.cpnx.gz)

**Closed** 2021-09-20 03:11 UTC
