### ISSUE TITLE
MHQ ATB scenario won't launch

### ISSUE THREAD

**Issue by Calvinfs852** [MegaMek/mekhq#1149] opened 2019-03-16 20:32 UTC
### Environment
MekHQ 45.3 dev
Win 10
Java 1.8.0_201

In MekHQ, a randomly generated scenario will not launch. This is a new computer and the first time I have tried to use MHQ on this machine.
[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/2974462/mekhqlog.txt)

[Tinkers30000601.txt](https://github.com/MegaMek/mekhq/files/2974463/Tinkers30000601.txt)
[Boulder BLD-1M.txt](https://github.com/MegaMek/mekhq/files/2974465/Boulder.BLD-1M.txt)
[Boulder BLD-1R.txt](https://github.com/MegaMek/mekhq/files/2974466/Boulder.BLD-1R.txt)
[Boulder Mek.txt](https://github.com/MegaMek/mekhq/files/2974467/Boulder.Mek.txt)
[Club Infantry.txt](https://github.com/MegaMek/mekhq/files/2974468/Club.Infantry.txt)

**Comment by NickAragua** [comment] 2019-03-16 20:36
Surprisingly enough, this isn't a duplicate of the special mission bug.  

Uploading the files as .txt works, however, it'd be easier for you going forward to just add them to a zip file.

**Comment by NickAragua** [comment] 2019-03-16 20:53
As a workaround, you can undeploy the Demolisher. Since it's immobilized, it's highly unlikely to be able to make it to the battle anyway.

**Closed** 2019-03-18 01:33 UTC
Labels: bug
