### ISSUE TITLE
:Blush: Ummm I broke the campaign save again.

### ISSUE THREAD

**Issue by KiloWhiskey1** [MegaMek/mekhq#1658] opened 2020-04-11 02:52 UTC
### Environment
What version of MekHQ does your issue apply to? 47.5
What operating system are you using?  Windows, Mac, or Linux? Windows
What java version are you using?  If unsure it will state your java version at the top of the mekhqlog.txt file. 1.8.0_231

### Description
File will not save in campaign. 13 saves preformed before it broke with
 a null pointer exception.

I had been plying with MML in MHQ but did not save any creations.

java.lang.NullPointerException

[customs.zip](https://github.com/MegaMek/mekhq/files/4463939/customs.zip)
[megameklog.txt](https://github.com/MegaMek/mekhq/files/4463940/megameklog.txt)
[RedRum30400804.zip](https://github.com/MegaMek/mekhq/files/4463941/RedRum30400804.zip)

Let me know if I need to stop breaking your guys hard work for a bit.

**Comment by HammerGS** [comment] 2020-04-11 03:19
From Log
`java.lang.NullPointerException
	at mekhq.campaign.ExtraData.isEmpty(ExtraData.java:182)
	at mekhq.campaign.personnel.Person.writeToXml(Person.java:2124)
	at mekhq.campaign.Campaign.writeMapToXml(Campaign.java:4846)
	at mekhq.campaign.Campaign.writeToXml(Campaign.java:4645)
	at mekhq.gui.CampaignGUI.saveCampaign(CampaignGUI.java:1418)
	at mekhq.gui.CampaignGUI.menuSaveXmlActionPerformed(CampaignGUI.java:1384)`

**Comment by Windchild292** [comment] 2020-04-11 03:25
This is the same procreation issues as before, I just don't trust myself not to make a mistake after a night of drinking with my housemate. I'll fix this in the morning, and am very sorry about the inconvenience.

**Comment by KiloWhiskey1** [comment] 2020-04-11 09:12
Dude. Take the long view, don't apologize for the inconvenience. Its a volunteer project so don't burn yourself out.

I just hope that the bug report helps you guys, I can wait to get back to my campaign.

**Comment by Kailan7401** [comment] 2020-04-11 09:24
[RedRum30400804.zip](https://github.com/MegaMek/mekhq/files/4464329/RedRum30400804.zip)

Hi Kilo, does this fix work? I have no idea what I'm doing but Windchild told me a bit ago that if you follow these instructions you can get the games to save again, and I've had luck using that method.

> In future, you can fix it by copying the save file, then opening it in notepad++ or a similar program and searching for any instances of `<map/>`
> If you remove the lines
> `<extraData>`
> `<map/>`
> `</extraData>`
> (but not the trailing personnel bit)
> it will work again

**Comment by KiloWhiskey1** [comment] 2020-04-11 09:31
Working on it now,

I am removing everything that looks like
<extraData>
    <map>
        <list type="java.lang.Integer">
            <entry key="procreation:children" value="0"/>
        </list>
    </map>
</extraData>

**Comment by KiloWhiskey1** [comment] 2020-04-11 09:34
Bah cut and past dosn't show

<extraData>
        <map>
                  <list type="java.lang.Integer">
                        <entry key="procreation:children" value="0"/>
                  </list>
         </map>
</extraData>

**Comment by Kailan7401** [comment] 2020-04-11 09:35
Try loading the save file I attached, see if that works. I've had luck following those instructions but unfortunately the issue keeps reappearing a few days later. We'll just have to wait patiently for a fix, but this should (hopefully) at least get you a working save again!

**Comment by KiloWhiskey1** [comment] 2020-04-11 09:39
Sorry missed the file trying now.

**Comment by KiloWhiskey1** [comment] 2020-04-11 09:43
Seemed to work. Thanks for letting me know how to fix it. I don't want to bother you guys with something I can fix on my own.

Rather have you skull sweating something cool for the community rather then fixing personal stuff

**Comment by HammerGS** [comment] 2020-04-11 13:03
This is still a big and still needs to be fixed.

**Comment by Windchild292** [comment] 2020-04-11 14:16
I'm Canadian, and apologizing is just my natural state of things @KiloWhiskey1 (that's one stereotype I am glad to embrace and say it tends to be true).

And thanks @Kailan7401 for helping with the fix.

**Comment by Windchild292** [comment] 2020-04-11 14:16
I just used this campaign to verify the two related bug fixes, and they are working. However, I am going to keep this open with the following statement.

This is caused by an issue with procreation, but disabling procreation if it is on will only make this far worse. The issue should only occur when loading from a save file with broken data, although it will appear to work properly until you attempt to save, whereby it is unable to save. That means that if you can save immediately after loading, you will be able to save.

In future, you can fix it by copying the save file, then opening it in notepad++ or a similar program and searching for any instances of <map/>. If you remove the lines
```
<extraData>
<map/>
</extraData>
```
(but not the trailing personnel bit), it will work again

**Comment by Windchild292** [comment] 2020-05-07 11:56
Closing this as it is resolved in 0.47.6

**Closed by Windchild292** 2020-05-07 11:56 UTC
Labels: Campaign Fixes Needed, bug
