### ISSUE TITLE
MRMS does not always use BTH settings

### ISSUE THREAD

**Issue by HammerGS** [MegaMek/mekhq#577] opened 2017-12-25 22:45 UTC
From the forum post here.

http://bg.battletech.com/forums/index.php?topic=59867.msg1374521#msg1374521

> I noticed the Mass-Repair-BTH-Bug has not been fixed so far. Is there anyone else having the same problem? My techs keep destroying my mechs /Tanks/ASF/DS because MekHQ seems to select just random techs to repair parts, not considering any settings in the mass-repair-setup. I had green techs trying to rush a xl-reactor-repair in the field while elites refilled ammo in maintenance facility-stored mechs... Is there a specific campaign-option causing the problem or is this generally broken? Any ideas? I am playing a campaign on regiment-level with a friend, and it gets a bit tedious repairing whole battalions after each battle without the mass repair

**Comment by HammerGS** [comment] 2017-12-25 22:47
I've left a note for them to get us campaign files and customs.

**Comment by Legendslayer84** [comment] 2017-12-27 08:45
Attached a campaign file. All min and max bth are set to 4 for this purpose. on the first mass repair, only armor parts will be fixed - all with a target roll of 4 - which is correct so far. advance one day, and  click mass repair again and the techs will try to repair parts where they need to roll 7 or higher.
This is one of my test-campaigns, so far i have not figured out a way to get around this bug. 

[Legends Legion30350708.zip](https://github.com/MegaMek/mekhq/files/1588659/Legends.Legion30350708.zip)

**Closed** 2018-01-14 04:58 UTC
Labels: bug

**Comment by neoancient** [comment] 2018-01-14 05:01
This is actually a duplicate of #548.
