### ISSUE TITLE
Save Corruption - Unknown Source (MekHQ)

### ISSUE THREAD

**Issue by BubbleLord** [MegaMek/mekhq#911] opened 2018-09-01 19:08 UTC
[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/2342677/mekhqlog.txt)
I'd wanted to supply my savefile as well, but GitHub prevents it from being added. I noticed someone else experienced a similar issue on the Reddit and wanted to throw another here. Hoping there's a fix or edit that can be made to the save file that will allow one to recover it. I changed the save over to a txt file, however, so hopefully it can provide context/make it feasible to see if there is a fix or way to isolate the issue.
[Tornaius' Aviators30250227 - Copy.txt](https://github.com/MegaMek/mekhq/files/2342678/Tornaius.Aviators30250227.-.Copy.txt)

Link from Reddit - https://www.reddit.com/r/battletech/comments/9bv3e6/mekhq_corrupt_save/

**Comment by HammerGS** [comment] 2018-09-01 19:15
You need to zip the files to add them.

**Comment by sixlettervariables** [comment] 2018-09-01 19:26
You're on 0.45.0 correct? If so, https://github.com/MegaMek/mekhq/pull/861 fixed it.

**Comment by sixlettervariables** [comment] 2018-09-01 19:26
Duplicate of #860.

**Closed by sixlettervariables** 2018-09-01 19:26 UTC

**Comment by BubbleLord** [comment] 2018-09-01 19:28
Yes I am on 0.45; I even made a fresh slab of the download under the idea maybe I'd corrupted my copy. It did not work in that one nor in my primary directory/version for 0.45.

**Comment by BubbleLord** [comment] 2018-09-01 19:34
So I looked at the other issue (#860) and don't understand why it was marked as a duplicate; I'd not used Mass Repair. Is it due to the fact that there are potentially units that should have been removed from the hangar post-salvage? I'd like to try and save this file, so finding a way to fix it would be nice.

**Comment by sixlettervariables** [comment] 2018-09-01 19:43
Yes, that's the issue on load. Interesting to note your cause was not mass repair. I'm not able to take a look at it today, but I can try loading and resaving the CPNX on the newer code tomorrow.

**Comment by BubbleLord** [comment] 2018-09-01 19:46
I'd appreciate it. I guess in the meantime I'll start a new campaign. If it helps, I had multiple instances during my play-through where I finished salvaging something and had to manually remove/sell it. If that's the cause, then it's not exclusive to mass repair; I don't use Mass Repair and experience things being left in my roster frequently without being cleaned out by the system.

To note though; it has worked a few times. But it often doesn't and requires me to manually sell them. This definitely seems exclusive/new to the .45 build.

**Comment by sixlettervariables** [comment] 2018-09-02 01:55
```
Javelin JVN-10N has been removed from the unit roster.

Griffin GRF-1N #3 has been removed from the unit roster.
```
[Tornaius' Aviators30250227-restored.zip](https://github.com/MegaMek/mekhq/files/2342910/Tornaius.Aviators30250227-restored.zip)

**Comment by sixlettervariables** [comment] 2018-09-02 16:44
Do you recall if any of these salvages ended up taking multiple days?

**Comment by BubbleLord** [comment] 2018-09-02 17:41
I think the Javelin did; not entirely sure on the 3rd Griffin. I might have just started salvaging it and hadn't finished when the save was made.
