### ISSUE TITLE
Random portraits pulling default image as choice when it shouldn't

### ISSUE THREAD

**Issue by pheonixstorm** [MegaMek/mekhq#572] opened 2017-12-23 14:25 UTC
Using the hire menu I have been getting the default image showing up when using the GM regenerate and random portrait options. Portraits are in use for MechWarriors
![defaultimage](https://user-images.githubusercontent.com/1787879/34320240-1c24779a-e7c3-11e7-89ec-e20eebe14622.png)

**Comment by neoancient** [comment] 2018-01-13 18:00
I can't reproduce this. Did the default.gif file somehow get copies into the data/images/portraits/Male or data/images/portraits/Female trees?

**Comment by pheonixstorm** [comment] 2018-01-14 00:50
No, but it also doesn't happen often. I will try to get a new build made and see if I can find a way to reproduce, or at least reproduce it slightly more often. Low priority bug anyways so it can wait until after the stable.

**Comment by monbvol** [comment] 2018-02-04 21:23
I'm getting a similar error on 43.7 RC1.  On one of my campaigns it refuses to assign portraits to female personnel(every role I've tried at any rate, wouldn't be surprised if I missed a role or two though).  It only happens on the one campaign I've created since switching to 43.7 RC1.

Windows 10 64 bit
Java 1.8
MekHQ 43.7 RC1

[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/1693320/mekhqlog.txt)

I'll just zip up all my transfers folder that has all my custom designs, portraits(which has some organizational changes from other people's so you'll probably want to delete the default portrait folder), and campaigns.  The one you'll want that has the issue(for me at least) is Trail of Tears.  None of the others seem to have had any issues.

Mediafire link since it is too big to attach directly: http://www.mediafire.com/file/7ke69v7uc1gd78u/MekHQtransfers.zip

**Comment by scJazz2** [comment] 2018-02-04 22:06
Just checking but... there must be a MALE and FEMALE folder. So if that is not a part of /data/images/portraits/

You should check that out.

**Comment by monbvol** [comment] 2018-02-04 22:11
That is one of the organizational changes I made to the example campaign
portraits(splitting them into Male/Female directories).

**Comment by monbvol** [comment] 2018-02-14 04:56
Well with 43.8 RC-2 the campaign that was giving me this issue is not anymore.

So I'm not sure if you guys fixed it without mentioning it or if something else was going on.  Either way I'm now able to get portraits and randomize portraits in said troublesome campaign.

**Comment by monbvol** [comment] 2018-02-14 06:02
Update 4:

While I do get the odd repeat it is rare enough that I am satisfied that the randomize portrait on new hire male unit members is working correctly.

I also checked the two female images that seem to be the only ones to come up for new hire female unit members and while they are both JPGs instead of PNGs there are other JPGs in the same directory with roughly the same dimensions.

But on a random tangent I manually selected another portrait for a female unit member that already had one and the new portrait entered the randomize portrait rotation(bringing the total to three it'll pull).

Repeating the process doesn't actually seem to add any more and only seems to change what the third portrait is but that could just as easily be that the choice pool is still so small that it keeps choosing the same three pictures, maybe four(think I saw it pull a fourth one once but not sure now).

Nothing seems to be showing in the log.

Checking other campaigns it seems they will assign new hire portraits correctly but randomizing existing ones does not work.  Which isn't a big deal and something I can certainly live with.

**Comment by Flibjib** [comment] 2018-03-22 20:42
I just wanted to say that I'm running into the same issues with female personnel portraits, have tested on both 43.9 RC3 and 43.8 RC2. Male personnel work fine.

**Comment by monbvol** [comment] 2018-03-25 06:30
The weird part for me is it only does it in that particular campaign.  I
have no trouble in any of my other campaigns.  I would suggest seeing if
that is the case for you as well, that it only happens in a particular
campaign.

**Comment by sixlettervariables** [comment] 2018-07-08 21:21
I had to restart MekHQ (0.44.0) a few times before I noticed it working on my campaign.

**Comment by BLOODWOLF333** [comment] 2018-07-15 01:43
I can duplicate this.  In the warehouse and repair bay HQ is using the default portrait for my vessel techs but, in the personnel tab it displays their portrait correctly.

![image](https://user-images.githubusercontent.com/16950832/42729705-679681c2-87a6-11e8-8369-884d051151a8.png)

![image](https://user-images.githubusercontent.com/16950832/42729712-88fb9460-87a6-11e8-847e-0b67d7c93ee6.png)

Maybe because their primary role is admin?

![image](https://user-images.githubusercontent.com/16950832/42729715-996df2ac-87a6-11e8-8121-bbe30042fb52.png)

**Comment by Windchild292** [comment] 2020-03-14 22:39
Randomize Portraits now works for personnel with portraits, and I've not been able to recreate the main part of this despite trying hard to. However, I can confirm that the warehouse and repair tab both  still require the fix. Assign this to me, I'll fix it

**Closed** 2020-11-07 00:16 UTC
Labels: Personnel, bug
