### ISSUE TITLE
Convoy escort mission generated ONE military mech as convoy.

### ISSUE THREAD

**Issue by BTSS88** [MegaMek/mekhq#5241] opened 2024-11-24 08:44 UTC
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Medium (Gameplay Limitation): Non-core functionality is impaired, providing a suboptimal but playable experience.

### Brief Description *

Convoy escort mission generated ONE military mech as convoy.

### Steps to Reproduce

Load save; it's the first mission of the week. 

### Operating System *

Windows 11

### Java Version *

17

### MekHQ Suite Version *

Free Text (type manually)

### Custom MekHQ Version

50.01

### Attach Files

[Musket's Emergency Contractors30620415.cpnx.gz](https://github.com/user-attachments/files/17892559/Musket.s.Emergency.Contractors30620415.cpnx.gz)
[logs.zip](https://github.co
[customs.zip](https://github.com/user-attachments/files/17892563/customs.zip)
m/user-attachments/files/17892562/logs.zip)

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by IllianiCBT** [comment] 2024-11-24 16:05
Your logs don’t appear to have uploaded and are essential for investigating this issue.

However, it is possible for military units to appear in a convoy. You can logic it as being a military convoy. Essentially what happened is we were unable to generate a unit of the requested type and weight, so unit substitution kicked in to avoid having an empty force.

Once I have the log I can confirm whether that’s correct.

**Comment by BTSS88** [comment] 2024-11-25 01:39
[logs.zip](https://github.com/user-attachments/files/17896060/logs.zip)

Here's the log. Hmm, I don't know why some files don't get uploaded. This is the 2nd time it has happened.

**Comment by IllianiCBT** [comment] 2024-11-25 01:41
This is a *guess* but I expect when you’re dragging the files into GitHub you’re dragging them onto the text from the existing files, which causes GitHub to place the file at that point in the text, breaking whatever file was there first

**Comment by BTSS88** [comment] 2024-11-25 02:31
Thanks. I realized that when I was posting another error. Will take more
care in the future.

**Comment by IllianiCBT** [comment] 2024-11-25 06:40
This appears to be working as intended. Currently, the civilian tables are very small so we frequently run into issues where units fail to generate because no units exist of the type we're asking for. In those events we start lowering our strictness, first by removing roles (Civilian, in this case), then weight, then the final fallback is to default to Mek (for ground scenarios).

That's what happened here, however any other units were then culled out by the old culling method. That has been completely reworked in https://github.com/MegaMek/mekhq/pull/5247.

Closing: working as intended.

**Closed by IllianiCBT** 2024-11-25 06:40 UTC
Labels: Force Generation
