### ISSUE TITLE
Can't load campaign file

### ISSUE THREAD

**Issue by Rince-Wind** [MegaMek/mekhq#1225] opened 2019-07-04 10:42 UTC
### Environment
Version 0.45.4
Windows 7
Java 8, Update 131

### Description
I can't load the campaign file and can't figure out what is wrong from the logs so I could change the file. File is from current version and I am still ingame. Forwarding a couple of days did not help, neither did saving again.

### Files

[Artemis' Hunters30741228.zip](https://github.com/MegaMek/mekhq/files/3358920/Artemis.Hunters30741228.zip)

[mekhqlog.txt]
(https://github.com/MegaMek/mekhq/files/3358917/mekhqlog.txt)

**Comment by sixlettervariables** [comment] 2019-07-04 17:07
Looks like a refit bug.
```
java.lang.ClassCastException: mekhq.campaign.parts.equipment.EquipmentPart cannot be cast to mekhq.campaign.parts.Armor
	at mekhq.campaign.io.CampaignXmlParser.parse(CampaignXmlParser.java:590)
	at mekhq.campaign.CampaignFactory.createCampaign(CampaignFactory.java:88)
	at mekhq.gui.dialog.DataLoadingDialog$Task.doInBackground(DataLoadingDialog.java:210)
	at mekhq.gui.dialog.DataLoadingDialog$Task.doInBackground(DataLoadingDialog.java:129)
	at javax.swing.SwingWorker$1.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at javax.swing.SwingWorker.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
```

**Comment by sixlettervariables** [comment] 2019-07-04 17:18
Duplicate of https://github.com/MegaMek/mekhq/issues/1193 which may be fixed in the next release. I'm out of town right now but can attempt to fix your CPNX when I get back.

**Comment by Rince-Wind** [comment] 2019-07-04 17:19
I just gm-finished the refit and I can load it again, thanks for pointing to it.

**Closed** 2019-07-04 17:20 UTC
