### ISSUE TITLE
[0.50.0-SNAPSHOT] Education - Warrior House Ma-Tsu Kai homeworld incorrect

### ISSUE THREAD

**Issue by Tzahr** [MegaMek/mekhq#4518] opened 2024-07-29 16:31 UTC
### Environment
16:22:59,754 INFO  [mekhq.MekHQ] {main}
mekhq.MekHQ.initializeLogging(MekHQ.java:303) - Starting MekHQ v0.50.0-SNAPSHOT
    Build Date: 2024-07-27T01:16:03.359732465
    Today: 2024-07-29
    Origin Project: MekHQ
    Java Vendor: Eclipse Adoptium
    Java Version: 21.0.3
    Platform: Windows 11 10.0 (amd64)
    System Locale: en_GB
    Total memory available to MekHQ: 4 GB
    MM Code Revision: e86f08fde087d229498e46e9697a41466897653e
    MML Code Revision: bea7884b61319d3b2c803a0fa65988008638e6ef
    MHQ Code Revision: 12c84d7d4a3a993ac643cdf58ba9b621a907170c

### Description
Warrior House Ma-Tsu Kai lists New Aragon as their planet in the Prestigious Academies list, instead of Bithinia, (and from 3063 onward Wazan). This currently causes Warrior House Ma-Tsu Kai to becomes accessible to citizens of the Federated Sun/Commonwealth while New Aragon is held by them 3008 - 3069.

**Comment by N7Danny** [comment] 2024-07-29 16:33
![image](https://github.com/user-attachments/assets/8ee26ae5-64f3-4503-92f8-7997c814df73)

It also appears to incorrectly note in the flavour text as well, referencing the forces to be Combine.

**Comment by IllianiCBT** [comment] 2024-07-29 19:55
How frustrating. There appears to have been a regression at some point, because the description *was* fixed. @N7Danny can I verify what version that screenshot was taken on?

**Comment by IllianiCBT** [comment] 2024-07-29 19:55
Actually, I can tell it wasn't on 50.0 as it doesn't offer Unit Education as an option. So I _think_ that's been fixed now

**Comment by Tzahr** [comment] 2024-07-29 20:38
I can confirm it still says Combine in the reported build.

**Comment by IllianiCBT** [comment] 2024-07-29 20:40
How bothersome. I'll take a look, as that very likely means there are other regressions in the xml. Thanks for flagging this guys :)

**Comment by IllianiCBT** [comment] 2024-07-31 15:30
Closing as resolved.

**Closed by IllianiCBT** 2024-07-31 15:30 UTC
Labels: Bug, Data, Personnel
