### ISSUE TITLE
KIA personnel that have been set to 0 hits in the battle resolution screen are still moved to the KIA roster

### ISSUE THREAD

**Issue by Question2** [MegaMek/mekhq#464] opened 2017-09-20 19:00 UTC
Personnel killed in a scenario and then set to 0 hits (or anything other than "dead") are still incorrectly moved to the KIA roster after the post battle resolution screen. They should only be moved to KIA if they are at 6 hits/dead.

[#battletech.zip](https://github.com/MegaMek/mekhq/files/1318905/battletech.zip)

If you load the autosave file for the first base attack scenario and let the BA get killed, you will end up with some dead BA pilots in the battle resolution screen afterwards. Setting them to 0 hits will still result in them being moved to the KIA roster at 0 hits.

**Comment by pheonixstorm** [comment] 2017-09-20 19:01
I noticed this earlier in my own game. Will take a look at it later and see if I can find the cause unless a dev beats me to it.

**Comment by Qwertronix** [comment] 2017-11-16 20:31
Noticed this as well, and it might be related to another report (which I can't seem to find at the moment) of units "disappearing" on their deployment phase in MM if they had previously come up as KIA and been put back to active status in this way. 

Also probably the same issue as #324.

**Comment by Dylan-M** [comment] 2018-02-11 21:56
Closing as duplicate.

Duplicates #324

**Closed by Dylan-M** 2018-02-11 21:56 UTC
Labels: bug
