### ISSUE TITLE
Overview -> Unit Rating does not take into account small craft Infantry Bays

### ISSUE THREAD

**Issue by Morkath** [MegaMek/mekhq#1100] opened 2019-02-21 17:00 UTC
### Environment
0.44.0
Windows

### Description
When using small craft to hold your infantry platoons, while docked in your dropship, the Overview -> Unit Rating, does not take into account these bays and gives the unit a penalty.

Overview -> Transport Breakdown
Infantry Bays (Occupied):                   6 (   6)
Small Craft Bays (Occupied):                2 (   2)

Overview -> Unit Rating
Small Craft Bays:            2 needed /   2 available
Infantry Bays:               7 needed /   0 available

The unit rating also seems to think I need one more bay, than I actually have platoons for some reason.

### Files
Attached the campaign and custom unit files.

[Morkath's Marauders_FullCustom_Company.zip](https://github.com/MegaMek/mekhq/files/2890291/Morkath.s.Marauders_FullCustom_Company.zip)
[CustomUnits.zip](https://github.com/MegaMek/mekhq/files/2890288/CustomUnits.zip)

**Comment by Windchild292** [comment] 2019-12-27 15:38
Can confirm this is still happening in vanilla 0.47.2

**Comment by Windchild292** [comment] 2019-12-31 20:19
This issue is that we only handle bays located in JumpShips and DropShips, and even then only specific types of bays for each.
JumpShips have code to handle ASF or Small Craft Bays, while Dropships can do MechBays, BA Bays, Infantry Bays, Light Vehicle Bays, Heavy Vehicle Bays, ASF Bays, or Small Craft Bays.
You can assign this to me, as I will be taking it on as my next issue. It is also an improvement, not a bug.

**Comment by Windchild292** [comment] 2020-01-07 17:06
Not an actual bug (FMM(r), p. 154 and Campaign Operations, p. 35 both state explicitly that transport capacity is based on dropships, jumpships, and warships.),, but did lead to some internal improvements. This can be closed.

**Comment by Morkath** [comment] 2020-01-07 17:27
> 
> 
> Not an actual bug (FMM(r), p. 154 and Campaign Operations, p. 35 both state explicitly that transport capacity is based on dropships, jumpships, and warships.),, but did lead to some internal improvements. This can be closed.

Yeah, that wouldn't actually disqualify this.  It is still being determined by the dropship/jumpship/warship.  The small craft is being carried inside the larger crafts bay.

I don't have campaign ops to check, but FMM doesn't say to ignore any small craft or other vehicles that the larger craft are carrying, that are capable of transporting units.

**Comment by Windchild292** [comment] 2020-01-07 17:43
I agree with you, but @neoancient does not.

FM:M(r) only talks about counting dropships, while Campaign Ops states Warships, Dropships, and Jumpships only. I think they never considered that other things can take bays, but.. RAW they don't count Small Craft Bays.

I'm considering making a custom version that will handle our viewpoint, but that will be later.

**Comment by neoancient** [comment] 2020-01-07 18:05
My position is not based on what I think the rules ought to be, or what I think should be possible. It is based on what the rules actually state.

FMM(r), p. 154:
>>>A force’s DropShip capacity is simply the percentage of component sub-forces that the command’s DropShips can carry, rounded off to the nearest 10 percent.

Campaign Operations, p. 35:
>>>To determine a Force’s Transportation Rating, first determine if the Force’s own transports (DropShips, JumpShips, and WarShips) are sufficient to convey the Force, including its noncombatants (technicians, administrators, specialist infantry, etc.).

There is no ambiguity in either rulebook about which unit types should be counted as transports for the purposes of rating/reputation. If you think the formula should be revisited to consider other unit types, post a rules question on the BT forums.

**Comment by Morkath** [comment] 2020-01-07 18:06
RAW do they specifically exclude small craft bays?  

The vehicle in that bay is using the exact same equipment that the dropship would use to house those units.  

Also, no one is trying to attach a small craft to a jump ship docking port and having it count as transport capacity, we are utilizing a bay in the dropship.  You are trying to arbitrarily count what equipment on a dropship is and is not valid.

**Closed by neoancient** 2020-01-07 18:05 UTC
Labels: bug

**Comment by Morkath** [comment] 2020-01-07 18:07
> 
> 
> My position is not based on what I think the rules ought to be, or what I think should be possible. It is based on what the rules actually state.
> 
> FMM(r), p. 154:
> 
> > > > A force’s DropShip capacity is simply the percentage of component sub-forces that the command’s DropShips can carry, rounded off to the nearest 10 percent.
> 
> Campaign Operations, p. 35:
> 
> > > > To determine a Force’s Transportation Rating, first determine if the Force’s own transports (DropShips, JumpShips, and WarShips) are sufficient to convey the Force, including its noncombatants (technicians, administrators, specialist infantry, etc.).
> 
> There is no ambiguity in either rulebook about which unit types should be counted as transports for the purposes of rating/reputation. If you think the formula should be revisited to consider other unit types, post a rules question on the BT forums.

Nothing in either of those quotes says to discount small craft bay on the larger vessel.

No one is trying to use just a small craft to transport units.

**Comment by neoancient** [comment] 2020-01-07 18:22
I'm not trying to blow you off when I say to ask a rules clarification question on the forums. If you think that's what it should mean, go through the channels.
