### ISSUE TITLE
Possible misplaced opfor, oops all arty (almost), in dropship raid defense

### ISSUE THREAD

**Issue by OrbMonky** [MegaMek/mekhq#5535] opened 2024-12-27 08:18 UTC
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Medium (Gameplay Limitation): Non-core functionality is impaired, providing a suboptimal but playable experience.

### Brief Description *

![image](https://github.com/user-attachments/assets/cec561d3-af81-4c60-be36-479bbbb61520)

Not sure how to reproduce this issue as the missions are more or less random, but this opfor appears to be a bit 'unusual'. Posting to have it checked.
[logs.zip](https://github.com/user-attachments/files/18258822/logs.zip)

### Operating System *

Windows 10

### Java Version *

17

### MekHQ Suite Version *

None

### Custom MekHQ Version

12/16 Logistics Artifact / 0.50.02 SNAPSHOT

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by IllianiCBT** [comment] 2024-12-27 08:21
I’ll want to double check the template to make sure everything is set up correctly. So not closing this now. But the OpFor turning up with a force generally built around killing Dropships at range would be working as intended.

**Comment by IllianiCBT** [comment] 2024-12-27 18:51
Closing as resolved

**Closed by IllianiCBT** 2024-12-27 18:51 UTC
