### ISSUE TITLE
Feature Request - TOE "Build Force" menu option

### ISSUE THREAD

**Issue by trent1098s** [MegaMek/mekhq#352] opened 2017-03-18 18:41 UTC
Another request, which hopefully can make use of already existing functions to automate the task.

Add GM context menu option on TOE screen "GM > Build Force"

<a href="http://imgur.com/B2KTreO"><img src="http://i.imgur.com/B2KTreO.png" title="source: imgur.com" /></a>

Which opens Create Random Army screen from Megamek:

<a href="http://imgur.com/oqEK15I"><img src="http://i.imgur.com/oqEK15I.png" title="source: imgur.com" /></a>

Default to RAT Generator tab, fill in game year, default faction to the one selected in the Campaign file for MekHQ:

<a href="http://imgur.com/ErpfqFN"><img src="http://i.imgur.com/ErpfqFN.png" title="source: imgur.com" /></a>

Then when you hit OK after building the RAT of your choosing and selecting forces, in MekHQ the units would be imported (as per import MUL file) and assigned to the currently selected force in TOE.

Would allow very rapid population of company / Binary / Trinary / Level II level units (12-20 mechs/vehicles) which could then be dragged & dropped to their respective Lance / Star / Level I as the player sees fit.

**Comment by neoancient** [comment] 2017-03-18 21:35
It actually looks more like this:
![screenshot from 2017-03-18 16-28-41](https://cloud.githubusercontent.com/assets/16927464/24076157/fa569f78-0bf7-11e7-9563-da86c0b690c1.png)
As I said in #348 I've got a force generator nearly completed. This is in a branch of the MM repository. When used from within MHQ it will set ranks and force icons as well. I started it as an OpFor generator, but I've been planning on using it in a new campaign wizard and providing access to it for reinforcing the TO&E with additional forces. I wrote the RAT Generator specifically to be a backend to this, but added it to MM as a useful feature in its own right.

**Comment by trent1098s** [comment] 2017-03-18 22:48
OK that's pretty awesome, and would be a massive time saver for our campaign.

**Comment by trent1098s** [comment] 2017-03-18 23:55
For custom / nonstandard regiments would be handy to have # of companies etc. I mean you could put a min and max in the config file for stuff (e.g. FWL infantry regiments could have variable # of battalions and companies). 

For customizing units though, if you select Regiment, have dropdowns for min-max # of battalions and companies; etc. 

Also a % of rated strength would be nifty and probably not too terribly difficult to implement. Some units are chronically understrength of rated capacity. A dropdown with multiples of 15%. Default 100, but allowing you to generate a regiment that's only at 75% strength; with units missing from various forces to show the lack of manpower. (I say it's easy to implement as I assume when bringing in units to populate from the rat generator, you could simply do a random(100) and if it is under the set value, it's added, otherwise it is skipped)

If you need any help with data entry, let me know what format the XML files are in (or send me a sample) and I can help get mercenary companies and house units entered. I have pretty much every one of the field manuals / handbooks / etc.

**Comment by Faolind** [comment] 2017-03-20 01:08
I know this is just me and maybe one other person in the universe, but having the Marian Legion setup (My favorite TOE style, it's just perfect for me) as a preset, or, as mentioned by Trent, as an editable system, would be greatly appreciated. The one issue with that specifically is that the Marian Legions had different numbers of Cohort in different eras, numbering from I think 2 to 10.

**Comment by neoancient** [comment] 2017-03-20 02:32
As I said above, any faction in any era.
![screenshot from 2017-03-19 20-48-39](https://cloud.githubusercontent.com/assets/16927464/24086920/b599c5ec-0ce5-11e7-8ab8-298efb1ff427.png)
Actually, that's not quite true. I haven't made a configuration file for The Society, but that's not terribly complicated.

If you want to help with research, I could use some help putting together some data on frequencies of certain lance types: what proportion should be recon, fire support, striker, etc. I have some of that worked in, but Campaign Operations has a much larger list and detailed criteria. Integrating that is the only thing that remains before I merge this into the master branch.

**Comment by Windchild292** [comment] 2020-09-05 01:22
Duplicate of #348

**Closed by Windchild292** 2020-09-05 01:22 UTC
Labels: enhancement
