### ISSUE TITLE
[12-15 Logistics Artifact] MHQ crash when advancing to new month

### ISSUE THREAD

**Issue by LadyAdia** [MegaMek/mekhq#5388] opened 2024-12-16 04:20 UTC
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Critical (Game-breaking/Crash): The game crashes or a core feature (like saving, loading, or network connection) is completely unusable.

### Brief Description *

When advanving to new month, immediately after the resupply dialogs, MHQ froze. Checking the terminal showed an NPE triggered and Sentry wad able to capture it, but it does not show on the log.

<img width="1440" alt="Screenshot 2024-12-15 at 10 16 00 PM" src="https://github.com/user-attachments/assets/eec0223f-c95c-4640-9ddf-8666c22c28de" />

I copy-pasted the message into a text file contained within the compressed files, along with the log and the required files.

### Steps to Reproduce

Advance day

### Operating System *

Mac

### Java Version *

17.0.12

### MekHQ Suite Version *

Free Text (type manually)

### Custom MekHQ Version

0.50.02 Nightly Logistics Artifact

### Attach Files

[MHQ New Month Error 24-12-15.zip](https://github.com/user-attachments/files/18144435/MHQ.New.Month.Error.24-12-15.zip)

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by IllianiCBT** [comment] 2024-12-16 04:22
It not being in the log is going to make this a pain to track down. Does it occur every month?

**Comment by LadyAdia** [comment] 2024-12-16 04:24
I did a test where I completed the contract early and advanced the day, and other than the scenario popup I already mentioned in Discord, I was able to advance to the next month

**Comment by LadyAdia** [comment] 2024-12-16 04:32
Further testing. When I refuse to send my convoy for the resupply, the month advanced correctly.

**Comment by IllianiCBT** [comment] 2024-12-16 21:14
Looks like this is being caused by a pesky infinite loop following the creation of the emergency convoy defense scenario. I'll see what I can do to track it down.

**Comment by IllianiCBT** [comment] 2024-12-16 21:35
Closing as resolved. I'll be pushing a new artifact later today so keep an eye on Discord :)

**Closed by IllianiCBT** 2024-12-16 21:35 UTC
