### ISSUE TITLE
sav corrupted, class cast exception [44.0]

### ISSUE THREAD

**Issue by bczretribution** [MegaMek/mekhq#975] opened 2018-11-09 04:06 UTC
### Environment
mekhq 44.0
 win 8.1

### Description
tried to reload my save from a few hours ago and received an unable to load message.  checked the log and found the following:

`java.lang.ClassCastException: mekhq.campaign.parts.equipment.EquipmentPart cannot be cast to mekhq.campaign.parts.Armor
	at mekhq.campaign.Campaign.createCampaignFromXMLFileInputStream(Campaign.java:4146)
	at mekhq.gui.dialog.DataLoadingDialog$Task.doInBackground(DataLoadingDialog.java:193)
	at mekhq.gui.dialog.DataLoadingDialog$Task.doInBackground(DataLoadingDialog.java:117)
	at javax.swing.SwingWorker$1.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at javax.swing.SwingWorker.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)`

hoping the file is salvageable.
### Files
[glitch.zip](https://github.com/MegaMek/mekhq/files/2564559/glitch.zip)
includes log file

**Comment by neoancient** [comment] 2018-11-09 19:45
One of the Stuka refits has the id of one of the PPCs in the place where the replacement armor should be. After a bit of poking around I found the correct id and was able to repair the campaign file (attached). I haven't found the cause yet.
[The Calvalry3.cpnx.zip](https://github.com/MegaMek/mekhq/files/2567304/The.Calvalry3.cpnx.zip)

**Comment by RexPearce** [comment] 2020-09-27 19:02
I loaded this campaign file with the latest dev and no exceptions occurred. However, the error log contained the warning: "unscrambleEquipmentNumbers : Could not unscramble equipment..." for around 20 of the units, which means there's a bunch of parts attached to units where they shouldn't be.

There have been several bugs fixed to the refit code in the last 2 years that could have caused this, so I recommend closing this.

**Closed** 2020-09-27 19:03 UTC
Labels: bug, refit
