### ISSUE TITLE
Odd behavior in simulated relationships

### ISSUE THREAD

**Issue by SirChaos1** [MegaMek/mekhq#5239] opened 2024-11-23 16:27 UTC
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Medium (Gameplay Limitation): Non-core functionality is impaired, providing a suboptimal but playable experience.

### Brief Description *

I´ve noticed some behavior in simulated reationships that is presumably not working as designed:

1) Female characters may have a pair of children with their birth date several weeks to a month apart. I assume that those are pairs of twins, but that the simulated relationship mechanics determine the birth date separately for each twin, instead of using the same for both as real life and the in-campaign procreation system do.

2) The "no longer trying to conceive" dice roll does not appear to firing during simulated relationships. At least, I cannot recall seeing a single female character who had at least one kid during the simulated relationship phase whose "trying to conceive" flag was set to "no", indicating that the dice roll after birth of her youngest child came up as "1". Older female characters who started out as trying to conceive tend to have a lot of children during the simulated relationship phase as a result (I see quite a few newly generated age 50+ female characters with 8-10 children in my campaign).

3) When a male character gets married during the simulated relationship phase and a female dependant spouse is generated, is that spouse also going through conception rolls from the time of marriage to the start of the campaign, the way non-dependant female characters are? Because, while have seen a lot of male characters starting out married or divorced, I cannot recall any of those married to (or divorced from) a woman to have children.

4) Children born during the simulated relationship phase, even if they are adults at campaign start, have Early Childhood education level.

### Steps to Reproduce

The issues should be straightforward to reproduce by generating a considerable number of personnel with "simulate relationship history" turned on and studying the result; maybe set a high minimum age in the Bulk Hire Personnel dialogue to make sure there´s plenty of time for simulated relationships to happen.

### Operating System *

Windows 10

### Java Version *

Java 17

### MekHQ Suite Version *

None

### Custom MekHQ Version

0.50.01

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by psikomonkie** [comment] 2024-11-23 21:24
@SirChaos1 - I've submitted a PR with fixes for 1, 3, and 4. 

I think 2 (The "no longer trying to conceive" dice roll does not appear to firing during simulated relationships.) is working as intended. Based on what I see in the campaign options, "No longer trying to conceive" is only rolled once, when a character is created. It is not re-rolled at any point.

**Comment by IllianiCBT** [comment] 2024-11-23 21:49
Actually, there should be a chance to opt out of future conception rolled whenever a character has a child. It’s entirely possible that was missed out of the simulation. Same with marriages (after a divorce there should be a die rolled to see whether they opt out of future marriage)

**Comment by psikomonkie** [comment] 2024-11-23 22:21
I see! Both divorce & background divorce have the reroll, but only the regular birth has the reroll. I've added it to birthHistoric, which is only used in the simulated relationships. Thanks!

**Comment by IllianiCBT** [comment] 2024-11-24 22:01
Closing as resolved

**Closed by IllianiCBT** 2024-11-24 22:01 UTC
Labels: Personnel
