### ISSUE TITLE
No message to say that no employees are eligible for turnover

### ISSUE THREAD

**Issue by molemanBT** [MegaMek/mekhq#5235] opened 2024-11-22 19:35 UTC
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Medium (Gameplay Limitation): Non-core functionality is impaired, providing a suboptimal but playable experience.

### Brief Description *

Advancing to a new month, get a warning about the turnover mechanic, click EMPLOYEE TURNOVER on the left side, and there is no nag to say you have noone eligible for turnover, it just advances day. Happens with a brand new save where I had 2 full lances constructed with the company generator too.

Linked thing, I get the pre turnover mechanic nag 4x for some reason.

[The Harbingers30340530.cpnx.gz](https://github.com/user-attachments/files/17875381/The.Harbingers30340530.cpnx.gz)

### Operating System *

Windows 11

### Java Version *

17

### MekHQ Suite Version *

Free Text (type manually)

### Custom MekHQ Version

0.50.01 (although the log, and the help > about ribbon at the top say 0.50.1)

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by molemanBT** [comment] 2024-11-22 19:47
Ok wait, once I made a commander, it started happening

**Comment by molemanBT** [comment] 2024-11-22 19:47
Still getting multiple nags though

**Comment by IllianiCBT** [comment] 2024-11-22 23:45
Can you list the exact steps you took to get this working again? Because the reason it's not working is, for some reason, Turnover checks aren't occurring on this save.

Just to confirm, have you manually edited your save? I'm assuming no, but want to be certain.

**Comment by molemanBT** [comment] 2024-11-24 19:37
Not a manually edited save, no (I don't know how to do that).

Personnel tab, left click, flags, and gave one of the mechwarriors the commander flag. Prior to that there was no commander because I manually added the mechwarriors, and didn't use the company generator

**Comment by IllianiCBT** [comment] 2024-11-24 19:44
Interesting, because assigning a commander in the provided save doesn't fix the issue.

**Comment by IllianiCBT** [comment] 2024-11-24 21:58
Closing as resolved

**Closed by IllianiCBT** 2024-11-24 21:58 UTC

**Comment by IllianiCBT** [comment] 2024-11-24 22:00
The issue is caused by a 'recently promoted' modifier that another contributor added during the development of 50.01. If your characters have never been promoted it fails, causing the entire module to breakdown.

The work around is to promote your characters at least once.
