### ISSUE TITLE
MekHQ-0.50.0-SNAPSHOT: Overabundance of Natural Aptitude: Piloting in personnel generation.

### ISSUE THREAD

**Issue by UlyssesSockdrawer** [MegaMek/mekhq#4707] opened 2024-08-25 19:34 UTC
### Environment
Version: MekHQ-0.50.0-SNAPSHOT
OS: Win11
Java: 17

### Description
During a testing run of the snapshot today, I noticed an overabundance of Natural Aptitude: Piloting in personnel generation. Over the course of creating a unit and playing one contract, I had 7 personnel generate with the trait.

Screenshots shared in the thread in the QA channel on Discord.

### Files
[The Ramshackle Renegades30620207.cpnx.gz](https://github.com/user-attachments/files/16741687/The.Ramshackle.Renegades30620207.cpnx.gz)

Save file attached.

@IllianiCBT

**Comment by repligator** [comment] 2024-08-25 19:50
The two "natural" SPA's are currently the only ones without prerequisites, hence they appear more often.

**Comment by IllianiCBT** [comment] 2024-08-25 20:04
Yeah, I thought I mitigated for that, but evidently not. I certainly intended to mitigate for it. I’ll check the books and implement or invent some prerequisites.

**Comment by UlyssesSockdrawer** [comment] 2024-08-25 21:03
I don't know if it should have pre-requisites - but it should also be rare. IIRC it's that sort of 'protagonist' trait that people like Kai Allard-Liao gets in the books.

Maybe putting it down to a 1% chance to trigger or something?

**Comment by IllianiCBT** [comment] 2024-08-25 21:04
So the problem is, that requires us to explicitly call out those SPAs we want to be rare, when we can’t actually guarantee the user even has these SPAs available in their campaign

**Comment by UlyssesSockdrawer** [comment] 2024-08-25 21:10
Darn. No way to put a rarity factor into the SPA itself?

**Comment by IllianiCBT** [comment] 2024-08-26 15:33
Closing as resolved

**Closed by IllianiCBT** 2024-08-26 15:33 UTC
Labels: SPA

**Comment by IllianiCBT** [comment] 2024-08-26 15:34
> Darn. No way to put a rarity factor into the SPA itself?

That might be an option in future
