### ISSUE TITLE
Cannot resolve Scenario in Current Mission

### ISSUE THREAD

**Issue by MattDroz** [MegaMek/mekhq#566] opened 2017-12-20 20:24 UTC
Everything launched fine. I played through the scenario, it saved the .mul file fine. When I click on Done, it brings me back to MekHQ and asks if I controlled the battlefield at the end. I answer yes (truthfully), and then nothing happens.

I then tried to resolve it manually with the same .mul, and still nothing happens. If I answer that I did NOT control the battlefield, then it lets me continue with the resolution.

[Test.zip](https://github.com/MegaMek/mekhq/files/1576920/Test.zip)

**Comment by HammerGS** [comment] 2017-12-20 20:27
Duplicate of https://github.com/MegaMek/mekhq/issues/560 and https://github.com/MegaMek/mekhq/issues/559

Fixed but need to find time to do a new release.

**Closed by HammerGS** 2017-12-20 20:27 UTC
Labels: bug, duplicate
