### ISSUE TITLE
50.01 Atmo Aerospace missions still spamming light units.

### ISSUE THREAD

**Issue by poiu18894012** [MegaMek/mekhq#5231] opened 2024-11-21 15:44 UTC
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

High (Major Disruption): A major feature is broken or incorrect, but a workaround exists.

### Brief Description *

Atmo Aerospace battles against enemies still spawn an absurd amount of light/medium units for given BV.
![image](https://github.com/user-attachments/assets/4c0a943a-28ec-4051-a6f2-f38468d66c74)
![image](https://github.com/user-attachments/assets/3d3f9ffd-d254-443c-932e-88a6b38f01ba)

### Operating System *

Windows 11

### Java Version *

17.0.12

### MekHQ Suite Version *

Free Text (type manually)

### Custom MekHQ Version

50.01

### Attach Files

[Interstellar Defense Force27750527.cpnx.gz](https://github.com/user-attachments/files/17848379/Interstellar.Defense.Force27750527.cpnx.gz)
[mekhq - Copy.zip](https://github.com/user-attachments/files/17848390/mekhq.-.Copy.zip)

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by IllianiCBT** [comment] 2024-11-25 00:57
What version were these scenarios spawned in? Because in checking the log I'm running into a _really_ odd thing. The force multiplier is set to x2.0, however the scenario has the multiplier set to x1.0 and spawning a second scenario of the right type confirms it's working as intended.

**Comment by poiu18894012** [comment] 2024-11-25 02:21
This save was from a fresh run in the 50.01 dev release from the website.

**Comment by IllianiCBT** [comment] 2024-11-25 05:50
Closing as resolved

**Closed by IllianiCBT** 2024-11-25 05:50 UTC
Labels: Force Generation
