### ISSUE TITLE
White Space issues on Briefing Screen

### ISSUE THREAD

**Issue by repligator** [MegaMek/mekhq#4958] opened 2024-10-01 13:39 UTC
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Low (Minor/Nuisance): Minor glitches or cosmetic issues that don’t affect gameplay and occur rarely.

### Brief Description *

See attached screenshot. I've tried editing the strings without any success, so it looks like the issue is with the formatting. Also, note that this bug is _not_ caused by https://github.com/MegaMek/mekhq/pull/4928 , as it predates it. 

![Screenshot_20241001_093427](https://github.com/user-attachments/assets/0cec7559-762a-41a1-bc3c-b9249c05435a)

### Operating System *

Windows 11

### Java Version *

17

### MekHQ Suite Version *

v0.50.0

### Custom MekHQ Version

https://github.com/MegaMek/mekhq/pull/4928

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by IllianiCBT** [comment] 2024-10-01 13:58
This will be caused by some xml weirdness resulting from the Mech->Mek changes. I _think_ I caught all of them, when working on #4928 so closing this as resolved. Once that PR is merged, though, please keep an eye out for any you think I missed. We can re-open this report if necessary. :)

**Comment by repligator** [comment] 2024-10-01 14:09
The screenshot is actually from when I was testing #4928 early today.

**Comment by IllianiCBT** [comment] 2024-10-01 14:11
![image](https://github.com/user-attachments/assets/ece1d7c5-51e5-4a7c-9e51-68900dcdc3cb)

Re-opening

**Comment by IllianiCBT** [comment] 2024-10-15 17:29
Closing as resolved…

…again

**Closed by IllianiCBT** 2024-10-15 17:29 UTC
Labels: Bug, Severity: Low
