### ISSUE TITLE
Cannot load saved missions

### ISSUE THREAD

**Issue by DynamicWorlds** [MegaMek/mekhq#4372] opened 2024-07-11 16:16 UTC
Fill out the fields below with as much pertinent information as possible to help the developers solve the issue.
Search for your issue inside open and closed issues first before reporting so as not to make duplicates.
(Delete the above lines)

### Environment
Nightly 2-024-7-10    0.50.0
Windows 10
Java 17

### Description
Cannot load saved scenarios in either MekHq or megamek.  Throws error message when attempting to load in megamek but not for mekhq.

side note: log files for megameklab and mekhq are empty.

### Files
[Trond's Dragoons30250215B.cpnx.gz](https://github.com/user-attachments/files/16180429/Trond.s.Dragoons30250215B.cpnx.gz)
[customs.zip](https://github.com/user-attachments/files/16180432/customs.zip)
[megamek.log](https://github.com/user-attachments/files/16180492/megamek.log)
[mekhq.log](https://github.com/user-attachments/files/16180493/mekhq.log)
![Temp2](https://github.com/MegaMek/mekhq/assets/155043132/f80f268f-101b-470b-ab5b-715316288b10)
![Temp](https://github.com/MegaMek/mekhq/assets/155043132/eb3004ad-aca3-494c-8490-4e8a016e4d34)

**Comment by HammerGS** [comment] 2024-07-11 16:26
Are you trying to load a **saved game** not a MekHQ campaign from a previous version?

**Comment by DynamicWorlds** [comment] 2024-07-11 17:24
No.  The file I'm trying to load was created in and by the snapshot.

**Comment by IllianiCBT** [comment] 2024-07-22 10:21
This appears to be a duplicate of #5756. I'm going to go ahead and close this issue, as there is an active investigation in the sister case.

**Closed by IllianiCBT** 2024-07-22 10:21 UTC
