### ISSUE TITLE
MekHQ freezes

### ISSUE THREAD

**Issue by Insert25c** [MegaMek/mekhq#940] opened 2018-09-23 20:39 UTC
Fill out the fields below with as much pertinent information as possible to help the developers solve the issue.
Search for your issue inside open and closed issues first before reporting so as not to make duplicates.
(Delete the above lines)

### Environment
MekHQ 0.44.0
Windows 10
Java 8 update 181

### Description
Game freezes when trying to access drop down menus (right click and menu drop downs like choosing which category of personnel to look at)
Lately the easiest way to force it to freeze is to try and right click on and Aero Pilot
Discussed in forums here: https://megamek.org/bb/thread-2565-post-18197.html#pid18197

### Files
zip folder with most recent save, mekhqlog, and megameklog
[Magnificent Bastard30200404.zip](https://github.com/MegaMek/mekhq/files/2409122/Magnificent.Bastard30200404.zip)

**Comment by HammerGS** [comment] 2018-09-24 23:32
See here and see if this rank fix resolves anything.
https://github.com/MegaMek/mekhq/issues/946#issuecomment-424157574

**Comment by giorgiga** [comment] 2018-09-24 23:49
Great intuition @HammerGS: it is indeed the same problem as #946! (well, basically)

This time instead of an empty rank description, the issue is the E0 naval rank is "--NAVAL", which means "same as naval" and causes an infinite loop.

<img width="1052" alt="campaign_options" src="https://user-images.githubusercontent.com/471835/45985084-d2c21f00-c064-11e8-9085-51b6293e9a31.png">

**Comment by HammerGS** [comment] 2018-09-25 00:11
Cool, so next step a bug fix.....tosses into on the pile..... for people smarter than I :)

**Comment by HammerGS** [comment] 2018-09-25 00:13
Duplicate of #946

**Closed by HammerGS** 2018-09-25 00:13 UTC
Labels: duplicate

**Comment by Insert25c** [comment] 2018-09-25 12:18
Thanks for the help.
