### ISSUE TITLE
[49.7] Mass Training, Unable to Mass Train Astech & Medtech Skills

### ISSUE THREAD

**Issue by IllianiCBT** [MegaMek/mekhq#3229] opened 2022-04-17 20:27 UTC
### Environment
Version - 0.49.7
OS - Mac, Monterey 12.3.1
Java - Homebrew, 11.0.12

### Description
When using 'Mass Personnel Training' certain Astech & Medtech skills cannot be trained. This means that should a user wish to provide these skills to personnel they will need to do so via manually editing the individual personnel member, as the skills also do not appear in the normal 'Spend XP' dropdown menu. If there are multiple personnel to receive these skills, this must be done individually.

Reproduction:
Select 'Mass Personnel Training', select either 'Astech' or 'Medtech' skills. Zero personnel will be shown as available to receive training.

**Comment by pheonixstorm** [comment] 2022-06-02 20:47
I was able to mass train **new** Astechs while setting up a new campaign in 0.49.8. Have not tried for Medtech.

These two skills are not skills that upgrade unlike regular techs or doctors. You only pay for the initial skill. Neither will show up in the spend xp -> current skills menu, only in the spend xp -> new skills menu. 

@Windchild292 unless someone wants to make this an upgradable skill this is working as intended.

**Comment by Windchild292** [comment] 2022-06-03 20:01
Mass hire works, mass training does not @pheonixstorm. You should be able to train anyone to add Astech or Medtech, but cannot. Upgrading is not part of either skill.

**Comment by pheonixstorm** [comment] 2022-06-03 20:40
@Windchild292 mass training for astechs and medtechs **does** work. I tested this in both 0.49.7 and 0.49.8
As for upgrading, it was mentioned in the original comment  "as the skills also do not appear in the normal 'Spend XP' dropdown menu"

![astech](https://user-images.githubusercontent.com/1787879/171948223-a8004782-d277-4787-9a80-e15b2a40f705.png)
![medtech](https://user-images.githubusercontent.com/1787879/171948251-96eb0eaf-8f2e-4bc3-84ef-cfa46a818a6d.png)

**Comment by Windchild292** [comment] 2022-06-06 11:47
Interesting, as running on latest develop I was unable to mass train those skills.

**Comment by pheonixstorm** [comment] 2022-06-06 12:10
Odd, I'm running win 10 and Adoptium jdk-11.0.14.101-hotspot. Or at least that is what I got from the install folder.

I started up an Age of War game that is heavy on infantry so first thing I did was add the 12xp needed for astech to all soldiers then did the mass training (nearly 200 soldiers).

If I can get my older computer running again I can try it on there.

**Comment by IllianiCBT** [comment] 2022-06-08 19:46
<img width="971" alt="image" src="https://user-images.githubusercontent.com/103902653/172703282-6de17040-62f6-4fc5-b5d1-2ca450f6094c.png">

<img width="965" alt="image" src="https://user-images.githubusercontent.com/103902653/172703581-4bb3d2a9-e968-43ba-9aae-141e56d8b18d.png">


[Autosave-1-Ape Mob-30251220.cpnx.gz](https://github.com/MegaMek/mekhq/files/8864610/Autosave-1-Ape.Mob-30251220.cpnx.gz)

Current campaign, 49.7 Mac, I'm unable to replicate the experiences of other users.

**Comment by pheonixstorm** [comment] 2022-06-08 20:31
You need to include any custom units. Tried to open the file and it can't find Kintaro Grim Dog. You should see a customs folder in /data/mechfiles  Just zip the customs folder and attach.

For target skill, can you change the -1 to zero? Also, in campaign options/experience how is the astech skill setup? You will need to scroll down a bit until you see Astech in the table. It should default to 12. If I change it manually to -1 I get the same result as the image you posted. With the default of 12 I am able to correctly train infantry with the Astech skill. For images below, top image is how it should look. Bottom image won't work
![should work](https://user-images.githubusercontent.com/1787879/172711299-f59dfe40-3d16-46ad-8d5b-23cc51f00ba7.png)
![doesnt work](https://user-images.githubusercontent.com/1787879/172711331-58727e42-c36b-4047-b23c-aa1496966734.png)

**Comment by IllianiCBT** [comment] 2022-06-08 20:37
[customs.zip](https://github.com/MegaMek/mekhq/files/8864871/customs.zip)
<img width="520" alt="image" src="https://user-images.githubusercontent.com/103902653/172711955-f9f46772-9922-4e9e-9457-06bb7d6a0b68.png">

Looks like skill cost settings is the culprit. Good catch.

The following campaign presets have -1 cost rank 0 skills:

- AtB - Official Options
- AtB - Starter Guide v4.0

**Comment by pheonixstorm** [comment] 2022-06-08 20:44
That explains why I had no problem, I rarely use atb.

**Comment by Windchild292** [comment] 2022-06-08 21:36
The AtB preset issues are resolved in 2e7a68a41a577dbcb35ed579d054a6c7126ab493

I'll open a PR shortly to disable the spend XP button when the skill target is -1, as that's a separate bug.

**Comment by Windchild292** [comment] 2022-08-15 02:05
Resolved in latest.

**Closed by Windchild292** 2022-08-15 02:05 UTC
Labels: Bug, Personnel, GUI
