### ISSUE TITLE
RFE:  Open All/Close All function within TO&E

### ISSUE THREAD

**Issue by Kendricke** [MegaMek/mekhq#1867] opened 2020-07-15 05:34 UTC
As a player who runs large unit campaigns, I would like an option to fully expand or close all units listed within the TO&E tab, because I dislike having to constantly double click each unit icon individually. 

Ideally, I would like this option to further allow me to fully expand/close specific parts of a unit org depending on where I use the option, which itself could show as a right-click menu option.

**Comment by purpledragon2** [comment] 2020-07-15 21:05
I would also like to have this functionality.

**Comment by Windchild292** [comment] 2020-07-18 18:30
Duplicate of #302

**Closed by Windchild292** 2020-07-18 18:30 UTC
Labels: enhancement
