### ISSUE TITLE
RFE: HQ Random SPA Improvements

### ISSUE THREAD

**Issue by RaozSpaz** [MegaMek/mekhq#3832] opened 2024-02-06 16:35 UTC
### Environment
49.17
Windows
Java 11

### Description
Someone was asking about it in the discord, but some options related to the random assignment of SPAs would be great. The first one is related directly to the discussion. The others are just other things I thought of.

1] An option to enable or disable the random assignment of SPAs whenever a personnel ranks up. 

2] An option to tone down the application of naturally generated SPAs [the ones that can only be acquired during random assignments] to prevent OpFors from having 8 Natural Gunners.

3] An option to limit the SPAs that can be acquired randomly during rank up [mostly to prevent Small Pilot and the like from appearing on someone if they chose to set it that way]

Out of all of these number 1 is honestly the highest priority. I could live without the other two if number one was a thing. 

### Files
RFE.

**Comment by Thom293** [comment] 2024-02-10 01:10
FYI you can set "SPA Intensity" in game options on the ATB tab.  I think each increment is a 0% chance at 0, and 25% chance at 1, etc...

Also, if you go to the SPA tab in game options, you can disable SPAs completely by removing them, or set them to -1 and they can only generate on "birth".

**Comment by RaozSpaz** [comment] 2024-02-11 03:28
I have my Special Abilities set to this and my Veterans will still get random abilities on rank up. Which is weird with the number set to 0. What it all means probably needs to be made a bit more clear. 
![image](https://github.com/MegaMek/mekhq/assets/132851640/046ba32a-3564-48dd-a68e-31012515f4fc)


Yeah. I have the -1 for the skills I dont want to be able to buy but generate. Though good lord do they have a tendency to appear on enemies.

**Comment by Thom293** [comment] 2024-02-11 04:20
Ahh. yeah the first setting is for frequency on enemies.  the second setting, I would assume when a MM force is created, the pilots can roll those "on birth only" SPAs because that is essentially when they are born.  But yes.  I can understand the desire now.  Sorry I misunderstood.

On the small pilot example - if you have it set to -1 I dont think it should roll on rank-up.  Id guess that would be a bug.

**Comment by RaozSpaz** [comment] 2024-02-11 05:32
Yeah. Small Pilot [or -1 SPAs in general] spawning on rank up is definitely a bug. Since the -1 is supposed to make it only for when they spawn. I didnt even think about that XD

**Comment by RaozSpaz** [comment] 2024-08-11 12:26
@IllianiCBT As requested

**Comment by IllianiCBT** [comment] 2024-08-11 17:42
> 1] An option to enable or disable the random assignment of SPAs whenever a personnel ranks up.

This definitely needs to be added. I'll look into it.

> 2] An option to tone down the application of naturally generated SPAs [the ones that can only be acquired during random assignments] to prevent OpFors from having 8 Natural Gunners.

This will be a little tougher to resolve, but definitely something that can be looked into. I think the biggest issue will be determining at what point during the character creation process are these personnel being handed their SPAs. Note to self: the SPA intensity campaign options should show where in the code we're doing this.

3] An option to limit the SPAs that can be acquired randomly during rank up [mostly to prevent Small Pilot and the like from appearing on someone if they chose to set it that way]

This will require a bit of a think. Would you be able to define what you mean by 'if they chose to set it that way'?

**Comment by Thom293** [comment] 2024-08-11 18:19
The issue is the SPA assignment code is in 3 different places and is inconsistent between them. Some consolidation would help, probably.  For example I'm not sure if the prerequisites even work on OpFor pilots.  

And just in case you don't know changing OpFor SPA frequency on StratCon tab is possible.  Each notch is 25%  chance.

**Comment by RaozSpaz** [comment] 2024-08-11 20:38
> The issue is the SPA assignment code is in 3 different places and is inconsistent between them. Some consolidation would help, probably. For example I'm not sure if the prerequisites even work on OpFor pilots.
> 
> And just in case you don't know changing OpFor SPA frequency on StratCon tab is possible. Each notch is 25% chance. I suppose if you want finer control could change notches to 5% steps.

Yeah. Me and you have already gone over that before. I already have it tuned to a comfortable %. The problem isnt the frequency at which they get SPAs, but the frequency at which they get NAG and NAP. Almost every battle at least 2 to 3 pilots have one or the other. And ive had some battles where upwards of 14 pilots can have it at once.

**Comment by Thom293** [comment] 2024-08-12 01:37
Yeah that many is busted. Could I trouble your for a save of your campaign settings?  I do t ever get that much repition.  I wonder what the difference in our settings is and maybe I can grok it out. 

I mean it needs to be fixed anyway but maybe I can help you in the short term.

**Comment by IllianiCBT** [comment] 2024-11-19 22:04
#5225 renders this no longer relevant. Closing.

**Closed by IllianiCBT** 2024-11-19 22:04 UTC
Labels: (RFE) Enhancement, AtB, Personnel, SPA
