### ISSUE TITLE
Fail to save campaign. 0.47.1

### ISSUE THREAD

**Issue by georgiaboy1966** [MegaMek/mekhq#1340] opened 2019-11-13 21:13 UTC
### Environment
What version of MekHQ does your issue apply to?
0.47.1

What operating system are you using? 
 Windows 7 Professional 64-bit SP1
Computer type: Desktop
Installation Date: 2/9/2014 12:31:25 PM

What java version are you using?  If unsure it will state your java version at the top of the mekhqlog.txt file.
Java Runtime Environment
	Path	C:\Program Files\Java\jre1.8.0_231\bin\java.exe
	Version	8.0
	Update	231
	Build	11

### Description
Describe the issue and provide screenshots ingame if able.

Attempt to Save Campaign, and program failed to save. gave error message. 
Is repetable.
Screenshop_2 attached

![Screenshot_2](https://user-images.githubusercontent.com/53351092/68804150-1d1eaa80-062f-11ea-85f5-fc873adb445c.jpg)

Latest Autosave
[Autosave-0-Federated Suns CYOA -29960626.cpnx.gz](https://github.com/MegaMek/mekhq/files/3843483/Autosave-0-Federated.Suns.CYOA.-29960626.cpnx.gz)

Customized files:
[Custom.zip](https://github.com/MegaMek/mekhq/files/3843510/Custom.zip)

Mekhqlog.txt:
[mekhqlog.txt](https://github.com/MegaMek/mekhq/files/3843512/mekhqlog.txt)

**Comment by sixlettervariables** [comment] 2019-11-14 00:24
Do you have a previous autosave? That one is bad. It is dying writing out your personnel it seems.

**Comment by georgiaboy1966** [comment] 2019-11-14 17:50
Here are two saves of same game

[Autosave-0-Federated Suns CYOA -29960627.cpnx.gz](https://github.com/MegaMek/mekhq/files/3847861/Autosave-0-Federated.Suns.CYOA.-29960627.cpnx.gz)
[Autosave-0-Federated Suns CYOA -29960628.cpnx.gz](https://github.com/MegaMek/mekhq/files/3847862/Autosave-0-Federated.Suns.CYOA.-29960628.cpnx.gz)

**Comment by NickAragua** [comment] 2019-11-15 00:44
The given campaign files are beyond any hope of recovery, as they are incomplete.

Is there anything from earlier?

**Comment by sixlettervariables** [comment] 2020-01-19 21:50
The campaigns themselves are unrecoverable and it is not apparent what the issue is. Closing this out until there is more info.

**Closed by sixlettervariables** 2020-01-19 21:50 UTC
Labels: Needs More Info
