### ISSUE TITLE
Not Saving. Usual fixes not working

### ISSUE THREAD

**Issue by NERRRRRRRRRRRRRRRRRRRRRRRRD** [MegaMek/mekhq#1689] opened 2020-04-24 00:33 UTC
Using MegaMek 47.5, on Windows with Java version 1.8 (I believe but am not entirely certain
This campaign does not save and I have looked through it in Notepad++ but I am likely missing something due to inexperience with the code. 
.cpnx and customs attached below.
I apologize for the inconvenience this probably presents.
[SoTFCampaign Info and Custom Units.zip](https://github.com/MegaMek/mekhq/files/4526000/SoTFCampaign.Info.and.Custom.Units.zip)

**Comment by Windchild292** [comment] 2020-04-24 00:51
My apologies for the issue, attached is the fixed campaign file with procreation turned off, as that is the cause of the issue. It shouldn't happen again, and I'm sorry about the inconvenience.

[The Scions of the Forge30470122-Fixed.zip](https://github.com/MegaMek/mekhq/files/4526043/The.Scions.of.the.Forge30470122-Fixed.zip)

**Comment by Windchild292** [comment] 2020-05-07 11:57
Closing this as it is resolved in 0.47.6

**Closed by Windchild292** 2020-05-07 11:57 UTC
Labels: Campaign Fixes Needed, Personnel, bug
