### ISSUE TITLE
[49.17] Aerospace forces are not generated in a Defend the Dropship scenario

### ISSUE THREAD

**Issue by Leafback** [MegaMek/mekhq#3861] opened 2024-02-29 01:16 UTC
### Environment

MekHQ: v49.17
OS: Linux Mint 21.3 x86_64 
Kernel: 5.15.0-94-generic 
DE: Cinnamon 6.0.4 
CPU: AMD Ryzen 7 5800X (16) @ 3.800G 
GPU: NVIDIA GeForce RTX 3080 Ti 
openjdk version "11.0.21" 2023-10-17

### Description

ATB isn't generating any aero for a scenario, specifically the objective dropship and friendly air support. I don't know when this was triggered to repeat any steps.

![image](https://github.com/MegaMek/mekhq/assets/105673647/06fe2860-a8fa-4a25-ba3e-565a3a2319e9)
![image](https://github.com/MegaMek/mekhq/assets/105673647/3e746958-cb23-4895-8c75-25dcb7ebb613)
![image](https://github.com/MegaMek/mekhq/assets/105673647/a54f8f03-0ebc-432d-801c-f63e370c699f)

What I have tried so far is to regenerate OPFOR. I have also tried different orders of regenerating OPFOR and adding/removing modifiers.

The support nor dropships are never generated. My own dropship was never deployed from the TO&E.

I'm including three saves. The autosave is slightly before arrival to the planet. "again" is when both scenarios were created upon arrival to the planet. "second" is after the resolution of the non-bugged one.

FWIW, this is my first time using 49.17 on my Linux system.

### Files

[Team Venom30441103second.cpnx.gz](https://github.com/MegaMek/mekhq/files/14441542/Team.Venom30441103second.cpnx.gz)
[Team Venom30441103again.cpnx.gz](https://github.com/MegaMek/mekhq/files/14441543/Team.Venom30441103again.cpnx.gz)
[Autosave-2-Team Venom-30441027.cpnx.gz](https://github.com/MegaMek/mekhq/files/14441544/Autosave-2-Team.Venom-30441027.cpnx.gz)
[megamek.log](https://github.com/MegaMek/mekhq/files/14441549/megamek.log)
[mekhq.log](https://github.com/MegaMek/mekhq/files/14441550/mekhq.log)

And a thank you all for volunteering to keep a great program awesome!

**Comment by Leafback** [comment] 2024-02-29 01:17
Oh. And I just noticed a separate issue? A Hot Jungle with Light Snowfall?

**Comment by kuronekochomusuke** [comment] 2024-02-29 01:23
that one I am working on. where temp is not restricting snow

**Comment by Sleet01** [comment] 2024-05-19 07:45
@Leafback Apologies for taking so long to get back to you with an update.

This appears to be a problem with the old traditional RATManager unit generation system, and your campaign settings (possibly exacerbated by playing during the Federated Commonwealth era):
- The allied air support and DropShip sections of the scenario _are_ being read in correctly from the template, and the scenario attempts to populate them, but...
- The defined RATs don't contain any matches for your current level of support quality, the FC faction, the year, and the defined unit types (ASF/CF, and DropShip)

The good news is that the RAT Generator method _does_ properly populate the forces:
<img width="283" alt="image" src="https://github.com/MegaMek/mekhq/assets/22018319/95af0890-5441-446f-a203-6ce814fa845d">

All you have to do to enable this method is open "Campaign Options", navigate to the Random Assignment Tables tab, and click the top option.

You also have the option of adding more era-appropriate traditional RATs (this game only has two, and one of them is a 3067+ RAT), like this:
<img width="470" alt="image" src="https://github.com/MegaMek/mekhq/assets/22018319/5010bc54-1b49-4eda-8280-1ef69eafaebb">

Either way, I'm going to close this as "won't fix" as it appears to be caused by the specific config in this save, and not a bug.

**Closed by Sleet01** 2024-05-19 07:45 UTC
