### ISSUE TITLE
12/18 Logistics Artifact / 0.50.02 SNAPSHOT - Excess cargo being allotted and left behind, in excess of requested and carryable tonnage. Fewer than expected items seem to make it into the warehouse.

### ISSUE THREAD

**Issue by OrbMonky** [MegaMek/mekhq#5453] opened 2024-12-20 00:27 UTC
### Prerequisites and Pre-Issue Checklist

- [X] I'm reporting the issue to the correct repository:
- [MegaMek](https://github.com/MegaMek/megamek/issues)
- [MegaMekLab](https://github.com/MegaMek/megameklab/issues)
- [MekHQ](https://github.com/MegaMek/mekhq/issues)

- [X] I've tested the issue against at least the latest MILESTONE version
- [X] I've asked on the MegaMek Discord about the error
- [X] I've reviewed the BattleTech rules and MekHQ documentation, and I've confirmed that something isn't working as intended.
- [X] I've searched the Github tracker and haven't found the issue listed

### Severity *

Medium (Gameplay Limitation): Non-core functionality is impaired, providing a suboptimal but playable experience.

### Brief Description *

I have four of these in the first convoy, the Hustler custom refit of the Vedette;
![image](https://github.com/user-attachments/assets/609b5d1c-3e5b-4c0b-8174-5492ef270369)
I have five of these in the second convoy, the standard Flatbed Truck (Armor);
![image](https://github.com/user-attachments/assets/a6ed5ad5-3769-49c8-9b57-970016d19a9e)
I have two of these in the third convoy, the Kite custom refit of the Maxim;
![image](https://github.com/user-attachments/assets/f155c4b7-9505-4ef9-a51c-df86e49b651f)
They all use traditional cargo bay w/door setups which should be valid cargo space, the space appears correctly recognized when dispatching the cargo (it requests 50 tons but has 60 tons available, which matches the math of all the Convoy units added up).

I only get two prompts post-acceptance of the cargo, and I get a lot of items dumped in the mekhq daily logs as 'left behind' due to not enough space. I think it is either not correctly utilizing one of the convoys or maybe not utilizing *any* of them. The total weight of the 'abandoned items' list is well in excess of 40 tons.

Here is my pre-convoy armor stock.
![image](https://github.com/user-attachments/assets/0603621f-4305-4495-a89e-ed51ae63238b)
If I choose armor as my request here is what I get offered;
![image](https://github.com/user-attachments/assets/617e5c55-359d-48d6-94fe-42c3881fde68)
Here is what I actually receive, well short of the expected mount;
![image](https://github.com/user-attachments/assets/4621664e-6895-4258-bda7-85709a11463a)

and I have pages of this totalling over a hundred tons.
![image](https://github.com/user-attachments/assets/f15987d4-1357-4e36-82f4-c37e76828b85)

> - Armor (Standard)  - Armor (Standard)  - Armor (Standard)  - Armor (Standard)  - Armor (Standard)  - Armor (Standard)  - Armor (Standard)  - Armor (Standard)  - Armor (Standard)  - Armor (Standard)  - Armor (Standard)  - Armor (Standard)  - Armor (Standard)  - Armor (Standard)  - Armor (Standard)  - Armor (Standard)  - Armor (Standard)  - Armor (Standard)  - Armor (Standard)  - Armor (Standard)  - Armor (Standard)  - Armor (Standard)  - Armor (Standard)  - Armor (Standard)  - Armor (Standard)  - Armor (Standard)  - Armor (Standard)  - Armor (Standard)  - Armor (Standard)  - Armor (Standard)  - Armor (Standard)  - Armor (Standard)  - Armor (Standard)  - Armor (Standard)  - Armor (Standard)  - Armor (Standard)  - Armor (Standard)  - Armor (Standard)  - Armor (Standard)  - Armor (Standard)  - Armor (Standard)  - Armor (Standard)  - Armor (Standard)  - Armor (Standard)  - Armor (Standard)  - Armor (Standard)  - Armor (Standard)  - Armor (Standard)  - Armor (Standard)  - Armor (Standard)  - Armor (Standard)  - Armor (Standard)  - Armor (Standard)  - Armor (Standard)  - Armor (Standard)  - Armor (Standard)  - Armor (Standard)  - Armor (Standard)  - Armor (Standard)  - Armor (Standard)  - Armor (Standard)  - Armor (Standard)  - Armor (Standard)  - Armor (Standard)  - Armor (Standard)  - Armor (Standard)  - Armor (Standard)  - Armor (Standard)  - Armor (Standard)  - Armor (Standard)  - Armor (Standard)  - Armor (Standard)  - Armor (Standard)  - Armor (Standard)  - Armor (Standard)  - Armor (Standard)  - Armor (Standard)  - Armor (Standard)  - Armor (Standard)  - Armor (Standard)  - Armor (Standard)  - Armor (Standard)  - Armor (Standard)  - Armor (Standard)  - Armor (Standard)  - Armor (Standard)  - Armor (Standard)  - Armor (Industrial )  - Armor (Industrial )  - Armor (Industrial )  - Armor (Industrial )  - Armor (Standard)  - Armor (Standard)  - Armor (Standard)  - Armor (Standard)  - Armor (Standard)  - Armor (Standard)  - Armor (Standard)  - Armor (Standard)  - Armor (Standard)  - Armor (Industrial )  - Armor (Industrial )  - Armor (Industrial )  - Armor (Standard)  - Armor (Standard)  - Armor (Standard)  - Armor (Standard)  - Armor (Standard)  - Armor (Standard)  - Armor (Standard)  - Armor (Standard)  - Armor (Standard)  - Armor (Standard)  - Armor (Standard)  - Armor (Standard)  - Armor (Standard)  - Armor (Standard)  - Armor (Standard)  - Armor (Standard)  - Armor (Industrial )  - Armor (Industrial )  - Armor (Industrial )  - Armor (Standard)  - Armor (Standard)  - Armor (Standard)  - Armor (Standard)  - Armor (Standard)  - Armor (Standard)  - Armor (Standard)  - Armor (Standard)  - Armor (Standard)  - Armor (Standard)  - Armor (Standard)  - Armor (Standard)

I count 134 instances of an item being left, totaling 67 tons of abandoned cargo which should be impossible. If I run it as 'balanced' instead of armor, I end up with well over a hundred tons. Something is probably procuring items instead of tonnages, and something is also probably not seeing all of the convoys as 60 tons of cargo space vs a 50 ton request should equal more armor getting to the warehouse, or at least that is what I suspect. Back of napkin math suggest 50 tons of standard armor should equal 800 points, though some is industrial so maybe this accounts for the difference.

If I set to balanced, I couldn't see any appreciable increase in inventory on any category, weapons, armor parts, etc so there may be other issues lurking as well.

### Steps to Reproduce

1. Load save.
2. Verify TOE convoy space total
3. Advance day.
4. Select convoy type and verify sizes
5. check daily log for abandoned items, compare prior day inventory to today's inventory.

### Operating System *

Windows 10

### Java Version *

17

### MekHQ Suite Version *

None

### Custom MekHQ Version

12/18 Logistics Artifact - 0.50.02 SNAPSHOT

### Attach Files

[logs.zip](https://github.com/user-attachments/files/18204443/logs.zip)

### Final Checklist

- [X] I've checked to make sure that this issue has not already been filed
- [X] I'm reporting only one issue in this ticket for clarity and focus

**Comment by IllianiCBT** [comment] 2024-12-20 16:26
Just a small thing: if you encounter stuff on day's end, we need the save from the day that ran into the issue, not the next day (i.e. if the issue is from when we advance from New Years Eve to New Years Day, I need a save from New Years Eve). As I'm unable to replicate the exact circumstances that caused the issue if you provide the save from the next day.

**Comment by IllianiCBT** [comment] 2024-12-20 16:28
The archive is missing a save

**Comment by OrbMonky** [comment] 2024-12-20 16:58
[Hel's Vanguard30261231.cpnx.gz.zip](https://github.com/user-attachments/files/18213307/Hel.s.Vanguard30261231.cpnx.gz.zip)
Here's one with a save from new years eve

**Comment by IllianiCBT** [comment] 2024-12-20 18:20
Closing as resolved

**Closed by IllianiCBT** 2024-12-20 18:20 UTC
