### ISSUE TITLE
[49.20] Scrolling issue with academy list with some themes

### ISSUE THREAD

**Issue by gsparks3** [MegaMek/mekhq#4338] opened 2024-07-04 19:24 UTC
Reported from Discord:
![image](https://github.com/MegaMek/mekhq/assets/59574316/1f502763-8d92-4322-b508-23720cbfb4b7)

Confirmed to be unintended by Illiani. User also reported that they were unable to scroll the pop-up menu; cause unknown. 
User OS: Windows 10

**Comment by IllianiCBT** [comment] 2024-07-04 19:30
To be clear (so I know what I'm looking for on Monday): the unintended behavior was the report that 'out of jump distance' was still displaying when hide invalid academies was selected.

Regarding the lack of scrolling: this is either an issue with the theme or a windows only issue. I'll need to investigate more, because scrolling is possible on Darcula on Mac. So I'm at a loss as to why it's not available here.

**Comment by gsparks3** [comment] 2024-07-04 19:36
Oh, hold on ... may have been a miscommunication here, the image above was from before they turned off "Show ineligible academies" in Campaign Options, i.e. they were _not_ hiding ineligible academies. The scrolling issue should probably still be looked into; title updated to reflect this.

**Comment by gsparks3** [comment] 2024-07-04 19:43
Just tested on Windows 10: the scrolling works on any of the Flat themes, but fails on Metal, Nimbus, CDE/Motif, Windows, or Windows Classic. Definitely a theme issue.

**Comment by IllianiCBT** [comment] 2024-07-04 20:10
Ok, cool. I did suspect that might have been the case. Unfortunately, theme issues are beyond my expertise to resolve.

**Comment by IllianiCBT** [comment] 2024-07-14 20:45
Marking this as "won't fix" as this is just a characteristic of specific themes and not actually a bug.

**Closed** 2024-07-22 10:23 UTC
Labels: Bug, Won't Fix, GUI

**Comment by IllianiCBT** [comment] 2024-07-22 10:24
Closing as working as intended
