### ISSUE TITLE
45.2 ATB : Unable to assign lances to a mission

### ISSUE THREAD

**Issue by Question2** [MegaMek/mekhq#1026] opened 2019-01-01 13:23 UTC
Edit : Double checked, the problem is that mekhq is warning me that I have not fulfilled the deployment levels required by the contract, but I have not reached the contract start date yet so I should not be getting the warning.

When I try to advance to the next week, Mekhq warns me that I have not fulfilled the deployment levels, but it is Feb 13 and the contract starts on Feb 26.

![mekhq](https://user-images.githubusercontent.com/1191378/50573220-b08a2b00-0e23-11e9-8bae-b2b81ce2b02c.jpg)
[a.zip](https://github.com/MegaMek/mekhq/files/2719344/a.zip)

**Comment by sixlettervariables** [comment] 2019-01-01 13:43
I believe I saw this the other day, but I was messing around with a lot of settings. I'll look into it with your save. Thanks!

**Comment by sixlettervariables** [comment] 2019-01-05 12:47
This should be fixed in #1007, I'm unable to reproduce this after that PR landed in 0.45.3 (unreleased).

**Closed by sixlettervariables** 2019-01-05 12:47 UTC
Labels: bug
