### ISSUE TITLE
Dark Ages: Oriente Protectorate contract causes failure to generate units

### ISSUE THREAD

**Issue by Maelwys** [MegaMek/mekhq#1465] opened 2020-02-08 18:57 UTC
So I've tried this with 46.1 and updated to 47.3 and I'm still getting the issue. Not sure if its something I've done, or not. I was in GM mode when I accepted the contract.

https://bg.battletech.com/forums/index.php?topic=45803.msg1581480#msg1581480

There's the original report from 46.1

I updated to 47.3 and the Java nullpointer exception is gone, but in all the scenarios generated, the enemy BV is still gone. This time I started the mission and no enemy units showed up, so I automatically won.

[NeonKunoichiEnemyBV0Bug.zip](https://github.com/MegaMek/mekhq/files/4175001/NeonKunoichiEnemyBV0Bug.zip)

Updated so everything was zipped in 1 file

**Comment by Windchild292** [comment] 2020-08-17 18:31
Duplicate of #1455

**Comment by Windchild292** [comment] 2020-08-17 18:37
Wrong issue, my apologies. This one is a data issue relating to the Oriente Protectorate.

**Comment by Windchild292** [comment] 2020-08-17 18:40
Namely, in the Force Generator the Oriente Protectorate is active from 3087-3139, but still exists on the map in 3145. I'm personally not sure which side the issue originates on, but that's the cause of the failed generation. @HammerGS

**Comment by HammerGS** [comment] 2020-08-17 19:21
Technically the Oriente Protectorate reforms in July of 3139 with other former Marik areas to create the reformed Free Worlds League. The really issue around Dark Age into ilClan era is the MUL is still lacking solid data. Something I know the MUL team is working on.

**Closed** 2021-07-26 14:02 UTC
Labels: Bug, Data
