### ISSUE TITLE
Children Recruited with Schooling/Impacting Awards?

### ISSUE THREAD

**Issue by johnboyjjb** [MegaMek/mekhq#4322] opened 2024-06-30 18:13 UTC
49.20

Children used to be dependents and didn't get tracked as recruited until they enlisted. Now sending them to school counts as enlisting them. This could impact the Good Conduct and Longevity Awards.

"I was also noticing that children are now considered recruited the day you send them to school. Will that impact Longevity and Good Conduct Awards?
SimonLandmine (admin not dev)
 — 
Today at 7:28 AM
"But little Jimmy behaved very well at school this year!"
BczRetribution
Illiani
 — 
Today at 10:24 AM
It probably would, yeah. I’ll have to write a special handler for that. Not difficult. If you can put in an issue report that would be fab"

**Comment by IllianiCBT** [comment] 2024-07-11 18:44
I've been unable to replicate this. It seems that children are only considered 'recruited' if you give them a role other than Dependent, which is working as intended.

So long as you leave them as Dependents they are not considered to have been recruited, no matter what rank or status is applied.

Closing as invalid. If you think this has been done in error, please post a reply including a step by step process to replicate the problem you're experiencing. :)

**Closed by IllianiCBT** 2024-07-11 18:44 UTC
Labels: Bug, Personnel

**Comment by johnboyjjb** [comment] 2024-07-11 19:21
![image](https://github.com/user-attachments/assets/8da4492f-39a4-4c33-91af-d3e4d0a52232)
![image](https://github.com/user-attachments/assets/5771c53c-ff1f-446e-95d0-e22e547f1fde)
[Sample1.cpnx.gz](https://github.com/user-attachments/files/16182614/Sample1.cpnx.gz)

I also was unable to replicate this in a "New Campaign". I can't help but replicate it in my existing campaign.

**Comment by IllianiCBT** [comment] 2024-07-11 19:43
I'm seeing a lot of instances where dependents are being added to something called 'student cadre'. Would you be able to advise me what that is?

**Comment by johnboyjjb** [comment] 2024-07-11 22:19
I had created a custom infantry squad for students, assigned them as infantry, and then reverted them back to being dependents. The Student Cadre was the TOE group. This might have triggered the creation of a Recruitment Date that was then masked when they were roled back into being Dependents. I do a similar thing with my support units for my combat units:
![image](https://github.com/user-attachments/assets/d89d6316-6570-4700-9e74-86967f641678)

I thought that may have been it, so in my experimentation in a new campaign, I took 3 kids and made them soldiers and 3 for the control group, and then sent them all to school. None of them exhibited Recruitment Dates like in my primary game file.

I would guess this is the edgeist edge condition you'll run into on this and you can probably close it and get back to useful things. I can live with the weirdness of being weird.

Also, just and FYI, if one creates a personnel record for every jump for 15 years for all of the employees in a full tank regiment, one needs to up the ram allocation to 8GB and the save file gets quite large. Too large to upload. I'm working on cleaning that up, but it takes a long time with 6500 staff members.
