### ISSUE TITLE
49.20 Nightly - Cross Version Save - Enemy rolls rout but Briefing Tab still shows Normal & Generates Battles.

### ISSUE THREAD

**Issue by Thom293** [MegaMek/mekhq#4189] opened 2024-06-09 07:30 UTC
Title.  Save is from 49.19.1.  Screens from 49.20 nightly from last night.

![image](https://github.com/MegaMek/mekhq/assets/23645569/22a8bd08-4f5c-4a28-8397-247880b9c14c)

![image](https://github.com/MegaMek/mekhq/assets/23645569/bd6a92f2-e05f-4af2-b84c-c5644e557622)

[Crazed Profanity30701201a.cpnx.gz](https://github.com/user-attachments/files/15751026/Crazed.Profanity30701201a.cpnx.gz)

[Customs41424.zip](https://github.com/user-attachments/files/15751027/Customs41424.zip)

**Comment by IllianiCBT** [comment] 2024-06-09 07:33
You mentioned you had a save from before this message popped up; could you provide it? Will help me investigate, tomorrow.

**Comment by Thom293** [comment] 2024-06-09 07:38
[Crazed Profanity30701201.cpnx.gz](https://github.com/user-attachments/files/15751036/Crazed.Profanity30701201.cpnx.gz)
[Crazed Profanity30701127.cpnx.gz](https://github.com/user-attachments/files/15751039/Crazed.Profanity30701127.cpnx.gz)
Yes.  These are both from 49.19.1.  No guarantee that the 11.27 will reroll rout, but could try and see.

**Comment by IllianiCBT** [comment] 2024-06-10 05:37
After review I found that the `Enemy morale is now Rout on contract 3070 - FS - Ancha Relief Duty` was a message issued while the save was still in 49.19.1. mhq doesn't wipe the daily report when loading, so the message was preserved from the earlier version making it look like it had been issued by the 49.20 client.

The reason the enemy morale switched from `ROUT` to `NORMAL` is due to the rout status no longer existing in 49.20. As we move towards further incorporating CamOps I made the decision to update our enemy morale statuses to match the terminology in CamOps. As mhq couldn't find the 'rout' status it defaulted to normal, as intended.

Closing as 'working as intended'.

**Closed by IllianiCBT** 2024-06-10 05:37 UTC
Labels: Bug, AtB
